== Chapter 1

=== First Month, 1791

1st. This being the first day of a new year, I have felt new desires raised in my mind,
that I might double my diligence in pursuing those things which make for peace;
and spend each day allotted me here in the pure fear of Almighty God.
Though it hath been my practice for some years to retire almost daily,
to feel after renewed strength to walk uprightly,
as well as to see where I have missed my way,
and how my accounts stood with the Father of mercies (a practice
which I have cause to believe hath been blessed to me);
yet I thought it might not be unprofitable to keep some
little account in writing of my progress Zionwards.
The looking over past failures may tend to keep me humble;
and if blessed with some good days,
the remembrance may sometimes serve to revive my drooping faith.

2nd. Attended both meetings.
In the morning, after some conflict with a temptation,
which presented itself on my first sitting down, +++[+++I]
was enabled in some measure to overcome it;
and to approach Him in whose presence is fulness of joy: the afternoon +++[+++was]
rather dull, yet not without some degree of life.
On going to bed a sense of my manifold infirmities humbled me much.

4th. Went to meeting this morning.
Methought it was a low stripping season,
which though not pleasing to the creaturely part, is doubtless beneficial to our souls:
that seeing our own insufficiency,
we may with more fervency seek help where alone it is to be found.

10th. My mind is pained under an apprehension that
I have spoken too freely of an absent friend.
May it prove a lesson of caution for the future.

11th. Went to meeting under much discouragement, and seemed surrounded with infirmity;
when, contrary to expectation, the great Physician of value was pleased to appear,
to my help, and great refreshment.
What a favour!

19th. I was much humbled at meeting today,
under a prospect of some little service that I believed would be required of me,
and was desirous that I might be qualified for it:
well knowing that of myself I can do nothing right;
it seeming as if there was scarcely any so weak or poor.

20th. I found some evil dispositions arise today, which I had to war with for some time.
O,
that every plant which is not of my heavenly Father`'s
planting might be rooted up and destroyed;
that I might be made more pure than gold.
This is what my soul at times is led to aspire after, more than riches or length of days.

28th. My time so much taken up with nursing my dear father, and with family engagements,
that I have had scarcely any time for retirement these few days past:
yet was favoured to keep pretty much in a state of quiet.

=== Second Month, 1791.

1st. My mind was sweetly affected today, on looking over the journal of my beloved niece,
to see how honestly she mentioned her faults.
O may this employ be blessed to her,
and her mind influenced by divine wisdom to distinguish right from wrong;
and strengthened to pursue the things that make for peace.

2nd. Wrote some remarks to my dear niece,
encouraging her to proceed in so profitable an employment.
O, while I am overlooking others`' vineyards, that I may not neglect my own.

7th. Many trials of patience today.
Doubt I bore them with that meekness,
that becometh a professed follower of a crucified Saviour;
yet in the evening my mind was sweetly drawn to aspire after purity.

8th. Received some affecting accounts of the sudden death of some of my acquaintances.
May I be also ready, not knowing how soon the messenger may be sent to my house.
O, that it may be set in order.

18th. A heart-tendering season at meeting today.
How sweetly is that saying of our blessed Saviour verified,
even in this day of degeneracy and deep revolt,
"`Where two or three are gathered together in my name, there am I in the midst of them.`"
Oh, what a favour to feel this gathering arm of divine power extended for our help!

20th. A time of much poverty in the forepart of the meeting,
but as I abode in a good degree of patience, +++[+++I]
was favoured with a little of the inbreaking of light and life.

22nd. No time these two days for retirement; yet my mind was preserved, I trust,
in a good degree of watchfulness and patience; under some unpleasant circumstances.

23rd. Poor and weak; yet desirous of renewed strength and faithfulness.

24th. Some remindings of my heavenly Father`'s love.
How are his mercies renewed every morning.

25th. My mind too easily drawn into a wandering state at meeting today,
out of the hearing of the true Shepherd`'s voice;
which brought me into a state of mourning and abasement.

26th. A time of sweet refreshment in my retirement today.
May I be thankful enough for such a favour.

27th. Stayed at home from meeting today, from necessity,
not from choice; yet was favoured to feel Him near me, who is omnipotent,
and does not overlook his poor little ones,
who are hungering for the bread of life even in their solitary situations.
It is with fear and humility that I have thus dared to rank myself of that number;
though surely one of the hindermost of the flock.

=== Third Month, 1791.

2nd. Renewed affliction: +++[+++I]
was thankful to feel some degree of resignation,
and my hope and faith were a little strengthened in a sitting in the family,
in the evening.

3rd. Fresh accounts of a distressing nature.
O, may we be brought to an entire reliance on that divine arm of strength,
which can support and sustain through a sea of conflict:
surely else we should faint by the way.

5th. My afflictions renewed this evening by fresh intelligence of a distressing nature;
and, being deeply humbled, I was permitted to approach the throne of grace,
and sweetly refreshed under a belief that the Lord would
in his own time heal and bind up the brokenhearted.

6th. A favoured time at meeting this morning.
My mind +++[+++was]
deeply humbled with the consideration of the goodness of the Almighty towards me,
in his gentle dealings with me; not according to my deserts, but his adorable mercy.
Dull and heavy in the afternoon; yet trust the warfare was, in degree, maintained.

7th. I trust this day has not been spent wholly in vain;
having an opportunity thrown in my way of doing a poor neighbour some service.
I am thankful that ability was given.

9th. Many occurrences crowded in +++[+++during this]
day, and my poor mind, I doubt, too much resembled the inn of old,
being taken up with many guests,
yet I would hope not to the entire exclusion of the blessed babe.

12th. My mind a little strengthened and animated to press forward,
by reading the experience of a faithful servant of the Lord.

13th. A time of sore conflict at meeting; yet, being reduced to a child-like state,
methought I was permitted to approach Him who said,
"`Suffer little children to come unto me, and forbid them not.`"

16th. Taken up these few days past, attending a dying friend:
though my feelings were tried, yet I thought the Comforter was near,
preserving our minds in a degree of sweet composure;
believing that when the conflict with death was over, the grave could have no victory;
the sting being taken away.

18th. I was much humbled at meeting this morning,
under the prospect of desolation in our Zion.
How few, how very few, burden bearers.
Was desirous that I might be fitted for one, and not shrink from it.

20th. A time of much favour this morning at meeting; yea my cup was made to overflow.
The Lord`'s banner over me was love, and his fruit was sweet to my taste.
How unworthy +++[+++of]
such adorable condescension!
In the afternoon +++[+++I felt]
some conflict with the spirit of heaviness, but, through mercy, +++[+++I]
was enabled to overcome it.

24th. A day of much bustle, yet found a little leisure to retire out of it;
and centering down to the pure gift,
my mind was sweetly refreshed under a sense of the
Lord`'s continued goodness to one so unworthy.

27th. Our preparative meeting,
and though my mind was led into mourning at the low state of our discipline, yet +++[+++I]
thought it a season of renewed favour.

=== Fourth Month, 1791.

3rd. Our quarterly meeting began.
My mind was affected on seeing a remarkable change in a young man,
who I believe had entertained notions bordering on deism,
and I was led in silence to adore that goodness,
which had thus mercifully extended this extraordinary visitation to him.
"`Joy shall be in heaven over one sinner that repenteth more than
over ninety and nine just persons:`" and surely every sensible
mind that is witness to it is made a partaker in this joy.
Blessed privilege!

4th. Today, in the meeting for discipline, I was called upon to expose myself as clerk,
none else being willing.
It was with much fear and trembling that I submitted.

7th. My mind sweetly drawn this morning into silence,
where I was favoured to experience that "`They that
wait upon the Lord shall renew their strength;
they shall mount up with wings as eagles; they shall run, and not be weary,
and they shall walk and not faint.`"
O, to be enabled to hold on my way.

11th. Wrote a letter to a young woman,
who is apparently hastening fast to her dissolution.
Was fearful she did not think so herself.
She received it kindly.
O, that it may induce her to turn inward, and see how her accounts stand.

13th. Too much encumbered about many things, some of which did not materially concern me.
Was taken in the night with such a violent palpitation of the heart,
that I scarcely expected to survive the struggle; but thou, O Lord, wast near me,
and sustainedst me, and in adorable mercy heardest and relievedst me.
O, make me thankful enough, and humble enough.

14th. Low and humble today, and desirous of being kept so.
In the evening +++[+++I]
met with a severe shock to my feelings.

17th. A time of travail in the morning; yet secret counsel was vouchsafed;
for which I was humbly thankful.
They that would be espoused to Christ must be chaste, both in thought, word, and deed,
and entertain nothing that would defile the temple which he is pleased at times to visit.

18th. On a review of this day, I feel no condemnation;
but hope I have been enabled to step along safely.

21st. Conscious of some weakness.
Paid a visit to a friend in affliction, in which I had satisfaction.

22nd. While waiting this morning at meeting, as I thought, at Wisdom`'s gate,
an unexpected and strong temptation was presented to my mind by the grand adversary;
but I trust I did not in any measure join in therewith:
and my secret cry to the Lord was for preservation, and that he would be pleased,
in his infinite mercy, rather to cut short the thread of my life,
than that I should live to dishonour his holy name.
Oh, the distress it brought, lest I should be separated from the love of God!

23rd. My mind renewedly humbled, under a sense of my own weakness,
and the subtlety of the unwearied adversary; of which I had a painful proof yesterday.
O, to be enabled to draw near him, who can alone preserve from the devourer.

26th. This day +++[+++was]
much given up to family concerns and company,
I think I may say in a cross to my own will, feeling some pantings after heavenly bread.
A little refreshment before I retired to rest.
Oh, the privilege of reposing our cares in Him,
who alone is able to sustain the poor drooping soul
amidst the many conflicts it has had to encounter,
in its passage to (I trust) a better country!

30th. Though a silent meeting, yet to my mind a very favoured one, far beyond my deserts:
yet towards the conclusion, +++[+++the meeting was]
attacked with sleepiness; which I had reason to fear had prevailed with some,
much to their hurt.
Oh, the supineness and indifference of some who ought, from their advanced age,
to stand as pillars in the church,
and strengthen the weak hands of us who are so much younger!

=== Fifth Month, 1791.

3rd. A wrong disposition got up this morning,
(even something of murmuring and complaining) on comparing my situation with
some others who are more favoured with the company of valuable friends.
Was thankful to feel it corrected, and self brought into abasement,
on considering the many blessings I enjoy beyond thousands;
and that the best of teachers, who can never be removed into a corner, is ever near,
and all-sufficient to those that trust in him.
Surely he hath dealt bountifully with me, far beyond my deserts.
How ungrateful then to repine at his dispensations!
O, my soul, be thy clothing dust and ashes.

4th. More quiet and comfortable today,
but no time for retirement till after I went to bed;
when I sought Him whom my soul loveth; and he was pleased to refresh my wearied soul.

8th. A favoured time at meeting.
How is the Lord pleased, at times, to make the desert blossom as the rose!

9th. Poorly in health, and apprehensive by my feelings that I should be quite ill;
yet favoured with resignation to whatever the Lord shall be pleased to dispense,
either sickness or health, believing it will be all ordered in best wisdom.

10th. Better today, which is cause of thankfulness; and what is still more so,
that I was favoured to approach Him "`who is the health of my countenance.`"

11th. A beautiful morning!
I rose early, and methought my mind being perfectly calm, resembled the cloudless sky;
but meeting with some cross events, +++[+++I]
was not enough on my guard, but suffered it to be ruffled,
which brought me into humiliation; and I was desirous of repairing to the washing pool,
that I might be cleansed from every defiling and hurtful thing.

12th. Spent +++[+++a]
good part of the day in profitable reading, which tended to draw my mind heavenward.
How much of my time have I squandered in the forepart of my life,
in reading books of a pernicious tendency!

23rd. My mind too much outward,
which surely bringeth with it its own punishment--a
sensible deprivation of the presence of God.
What greater punishment!

24th. My mind, having suffered hunger, was led to pant after heavenly bread:
which was graciously vouchsafed in my retirement today.
Oh, this best of blessings!
Nothing short of it can satisfy the quickened soul.

29th. A time of labour in the morning: yet not deserted by the good Husbandman.
Went to meeting in the afternoon in great weakness; when quite unexpectedly,
the Lord was pleased to break in upon my soul with his life-giving presence,
and by removing the spirit of heaviness, to array it with the garment of praise:
and I believe others were made partakers of the same inestimable blessing.

=== Sixth Month, 1791.

1st. No time for retirement today; yet in my solitary walk +++[+++I]
met with the beloved of souls, who sweetly attracted me,
and melted me into tears under a sense of his goodness and my own nothingness:
feeling at that time that all good proceeded from him,
and that it is only as we receive ability from him, that we can do any thing aright.

5th. A time of sweet encouragement at meeting, this morning.
O, that such seasons may be rightly improved.
Stayed at home in the afternoon, from necessity.

7th. No time for retirement today; though I strove hard for it,
and was as often disappointed:
yet the sweet quiet I felt in the evening induced me to believe
that my desires were accepted by the Father of mercies.
How much better is it to spend one hour in thy courts than a thousand elsewhere,
yea preferable to the most refined delights this world can yield!

10th. A time of labour at meeting,
being humbly desirous of being directed aright in a little
service which I believe was required of me.

11th. Wrote a letter to a young man,
who I believed had been favoured with an extraordinary visitation,
and who I was fearful was going backward.
Found peace in discharging what I believed to be my duty, leaving the event.

12th. A time of digging deep, yet laboured not in vain,
being favoured to drink a little at the pure fountain of life.
+++[+++The]
afternoon +++[+++was]
an uncommonly laborious meeting;
and though my mind was deeply exercised for the arisings of life,
I could scarcely feel any.
Times and seasons are in the Lord`'s hand; and no doubt but these stripping,
proving ones, are intended for a trial of our faith and patience.

13th. The rest of this week confined by illness,
under which I was preserved in a good degree of composure
and resignation to the divine will;
and was favoured at seasons, to feel the Physician of value near,
whose heavenly presence can shed peace and comfort even on the bed of sickness.

19th. Well enough to get to meeting, which I esteemed a favour,
and which proved a precious heart-tendering season.

20th. A short, but sweet refreshing season today, which I thought helped to support me,
through an unpleasant conference with the young man to whom I had written.
I fear he is in an unsafe spot.

21st. My mind a little relieved (though by no means
wholly) from the burden thrown on it yesterday,
and is deeply humbled, fearing I have done wrong in giving him my advice;
yet thought I did it in much simplicity, and under an apprehension of duty.
O, to be rightly directed, is the sincere prayer of my heart.

22nd. Rather comforted under a belief that I did right in writing,
though it had not the desired effect.

25th. On a review of this day, +++[+++I]
think my mind has been too much outward, yet +++[+++I]
found time for a little retirement, in which it was drawn to aspire after a better state,
even perfect holiness.

28th. No suitable time for retirement.
Caught myself entertaining vain and silly thoughts.
Was desirous they might be taken from me, which was granted me; and, though in company,
my mind was sweetly attracted upwards,
feeling sensibly that all was lighter than vanity
when compared with the joys of God`'s salvation.

=== Seventh Month, 1791.

3rd. Our quarterly meeting, not large: I thought the forepart of the meeting heavy,
yet not wholly deserted by the great and good Husbandman,
who is still mindful of his little ones.

4th. The meeting this morning I thought a favoured season;
a fresh extension of heavenly regard to the backsliders in our Israel.
My poor mind was earnestly turned to the Lord for help and strength,
which was graciously given me to go through the service of the meeting as clerk.

6th. A close trial this morning in parting with a beloved sister;
and the prayer of my heart was to the Father of mercies,
that he would be pleased to be with her in the way that she goes,
and be unto her as a wall of defence on the right hand and on the left.

14th. Felt sweetly peaceful this morning,
and something of the hovering wing of ancient goodness,
even while employed in the business of the day: but, alas! for want of watchfulness +++[+++I]
missed my way; and though it is what many would esteem a small thing,
yet I felt it to be wrong.
O for more stability.
How doth the soul, measurably redeemed from the pollutions of the world,
feel even small crimes!
I am thankful to feel it so,
and earnestly desire that this swift witness against every appearance of evil,
may be my constant companion through time.

15th. A hard struggle with a spirit of indifference and lukewarmness,
which beset me at meeting today; but with thankfulness may acknowledge that, in degree,
I obtained the victory,
through the gracious assistance of Him who saw my feeble endeavours and blessed them;
to whom be the praise.

19th. Felt comfortable today notwithstanding some unpleasant circumstances.
Favoured with a little access to the throne of grace; where in deep prostration,
my poor wearied soul begged a renewal of strength to hold on its way.

22nd. A favoured season at meeting this morning; which, methinks,
should have proved a sufficient incitement to keep my heart with all diligence, etc.,
instead of which gave way in the afternoon to a wandering disposition,
and strong fights of imagination,
which surely led from that peaceful and quiet habitation,
which methought my soul enjoyed this morning.
O, may it be favoured to get again into the valley, where there is safety.

27th. Favoured in my retirement today, yet was guilty of a weakness in the evening,
in saying "`Sunday`" to a person not a Friend, for which I felt condemnation,
and desire to abide humbly under it.

28th. This day passed I trust in humility and fear;
and I was favoured in the evening far beyond my deserts,
with sweet access to the throne of grace,
where I implored forgiveness and more stability for the future.

29th. Was desirous this morning at meeting of sitting like Mary of old,
at the feet of Jesus; and to be taught of him;
when it was shown me that I was not enough pure; that the warfare must be continued,
and that daily.
O, that I might be thoroughly cleansed.

=== Eighth Month, 1791.

2nd. Was favoured in my retirement today to recur, as it were,
to Bethel (where the Lord was first pleased to visit my soul),
and gratefully to call to mind his gracious dealings with me.
Though his appearance was at first very low and small,
even as it is compared to a grain of mustard seed,
yet he was pleased to incline my heart to prize it,
and in abundant condescension hath been pleased to increase my store; and,
blessed forever be his holy name, hath kept me alive to this very day.
O, that I may never turn aside to the right hand or the left,
but deeply ponder the path of my feet, and let my eye look straight forward.

6th. A sweet refreshing season this evening,
being favoured to partake of that stream which makes glad the whole heritage of God.
How unworthy +++[+++of]
such goodness!
Did not choose to go out this evening, lest I should lose the sweet savour.

8th. Deeply humbled today under a sense of my own unworthiness,
and a fear that my love is not sufficiently pure and chaste towards Christ,
who is alone worthy of our affections.
O, to be more weaned from the world.

12th. A very favoured heart-tendering season this morning at meeting;
but towards the close a scheme of benevolence caught my attention; which,
though there was something specious in its appearance, drew my mind off its proper watch.
Thus can the enemy transform himself as into an angel of light, in order to gain his ends.

17th. Shook off sloth, and rose early,
that I might have a little time for retirement before the rest of the family were stirring;
that, waiting at Wisdom`'s gate,
my mind might be influenced so as to step safely through the day,
yet did not feel the divine presence so sensibly as many times.
May I be sufficiently humbled; not doubting but the deficiency was on my part.

23rd. A sweet cloudless morning.
I rose with a tranquil mind, being desirous of preservation through the day;
and surely I had need of it, finding fresh exercise for my patience.

24th. A refreshing time this evening,
under the belief that it was nothing short of the good hand of God,
that first inclined my heart thus to religious retirement.
It was not from any imitation, not knowing any, at the time I began,
that were in the practice; but I can with thankfulness acknowledge,
that it hath been abundantly blessed to me.

28th. I sensibly felt the divine presence this morning at meeting, and,
under a sense of my manifold infirmities,
was led to aspire after a greater degree of holiness and renewed strength to walk uprightly;
seeing some who had, I believe, made a good beginning, turning aside from the narrow way;
not being (I fear) humble enough to receive the babe Jesus in his lowly appearance;
but perhaps expecting great things,
and looking as some did formerly for signs and wonders.

31st. Very unwell in my bodily health,
yet favoured with a renewal of strength to press forward.

=== Ninth Month, 1791.

1st. A very trying day, and my spirits, being weak from indisposition,
could hardly bear up under it; yet +++[+++I]
earnestly desired an increase of patience and humble resignation under every allotment,
however trying.

2nd. A stripping time at meeting.
I felt weak, poor, and helpless, like a little child; having nothing of my own,
and scarcely strength to ask for a little help.

4th. A precious meeting in the morning.
In the afternoon, after labouring for about an hour,
without gaining what my soul longed for, these words opened livingly in my mind,
"`He trod the wine-press alone,
and of the people there was none with him,`" which tendered me exceedingly:
and the language of my soul was,
that I might not be like those formerly who followed
him for the sake of the loaves and fishes;
but that I might be willing to be his faithful companion in tribulation, believing,
that if ever I entered the kingdom it must be through suffering.

13th. Went a journey, and poorly in health,
so that I could not have retired but with difficulty:
and am fearful of appearing more in shew than in substance; yet thought I felt good near,
and was preserved in a degree of quiet and (I trust) innocence.

21st. "`The heart knoweth his own bitterness:`" and were it not that I am sometimes
favoured to partake of that joy with which the stranger cannot intermeddle,
surely my heart would have fainted long ago.

24th. A favoured season this morning!
Surely the oftener we repair to the fountain,
the more likely we are to keep our garments unspotted of the world.

25th. A time of labour +++[+++in]
the forepart of the meeting; yet being desirous of patiently abiding under it,
the clouds at length were dispelled,
and the Lord was pleased to arise with healing under his wings;
for which favour may all that is within me magnify his adorable name.

27th. A severe struggle this morning with indisposition.
What a favour, in such seasons of distress, to feel the Physician of value near; and Oh,
what an unspeakable favour to have a well-grounded hope,
that when this earthly tabernacle shall decay,
we shall have a better mansion prepared for us, even a house eternal in the heavens!

29th. No time for retirement today; yet felt my mind sweetly attracted upwards,
several times in the course of the day; especially in the evening when in company,
so that I could scarcely refrain from tears.

=== Tenth Month, 1791.

3rd. Our quarterly meeting at Esher.
A precious heart-tendering time at meeting this morning, after some conflict.
At the conclusion of the meeting for worship, +++[+++I]
received the affecting intelligence of the death of my beloved uncle Jeremiah Waring,
which affected most, if not all friends present:
his removal being considered a public loss.
Many said, "`We have lost a father;`" for such he was to the meeting he belonged to.
Alas, who is there likely to fill the vacant seats of the worthies removed!
May the Lord of the harvest be pleased to raise up some;
for surely the state of things in this quarter is lamentable!

6th. Have dwelt much in the valley these last three days;
though I met with some interruptions, from company, yet it hath seemed a weaning time.
O for a more perfect dedication of heart to the Lord and his service.

9th. Went to Alton, to the funeral of my beloved uncle; the company +++[+++was]
much smaller than it would otherwise have been, owing to the very wet weather.
The forepart of the meeting I thought much favoured; feeling that which is beyond words.
A solemn pause at the grave, notwithstanding the inclemency of the weather.

12th. Was at Alton week-day meeting;
at which though I found enough to do to keep my mind upon the watch,
yet I think on the whole it was a favoured season.
Returned home in the afternoon; found all well: +++[+++a]
fresh cause for thankfulness and lowliness!

14th. "`Stand in awe,
and sin not,`" was sweetly impressed on my mind soon
after my first sitting down in meeting;
and a refreshing season it proved, my soul being led as into fresh and green pastures;
yea, I was made to lie down and rest as at noon-day.
Oh, that one so unworthy should be favoured with this blessed experience!
Not withstanding; before the meeting closed, I got off my watch:
such is the instability of human nature when left to itself.

16th. A time of close exercise this morning at meeting, in which I had to believe,
that my feet would be turned into a narrower path than I had hitherto walked in,
and that the day of the Lord must come upon all pleasant pictures.
O, may I be enabled to dwell with the consuming fire,
and freely give up to the sword that which is appointed for destruction.

22nd. My strength a little renewed this morning in my retirement.
How sweet and profitable are these seasons!

23rd. A refreshing season at meeting this morning: yea,
I thought the stone was rolled from the well`'s mouth, so that my soul,
with some others present, was favoured to drink freely of the waters of life.
O, that all were gathered to this fountain;
then would there not be so many barren ones amongst us, as is now sorrowfully the case.

26th. Received the affecting account of the death of a relation,
who hath left a wife with four small children.
It hath shown to my mind the necessity of digging deep;
that when afflictions like these are permitted to come,
we may know a safe hiding place from the storm.

29th. Surely my mind resembles the dove after making
excursions from the ark (that place of safety);
but, finding no rest for the sole of her foot, returns wearied, yet with delight, to it.
And Oh, the adorable goodness of God!
How is he, as it were, putting forth his hand and receiving me into this quiet habitation!
O, that I may never stray from it.

31st. My mind a little animated to press forward in the heavenly race,
by reading a sweet account of a youth but sixteen years of age;
yet who had far outstripped me.
O, may it excite to increasing vigilance and circumspect walking;
that I also may at the conclusion of time, have an inheritance among the saints,
and spirits of just men made perfect.

=== Eleventh Month, 1791.

2nd. Company and visiting have taken up much of my time today:
yet could not go comfortably to bed without feeling after the divine healing virtue,
and taking a solemn review of the day, in which I felt no condemnation:
so went to bed in peace.

4th. Strengthened in my solitary sitting today;
being favoured to partake of the water which is freely offered to those that seek it.
Oh, that so many should slight so great a blessing!

7th. Have spent my time today in good and profitable company,
and my mind much occupied in an affair of some importance; yet upon a review, +++[+++I]
think I might have stolen a little time for retirement,
that I might have had the more full enjoyment of
his presence which I ought to prefer to every consideration,
and which I, sometimes, hope I do: but through the instability of nature,
ofttimes miss my way.

11th. A precious season at meeting this morning, though a silent one,
and but very few there;
yet surely we were favoured to feel that gracious promise verified,
that where two or three are gathered in the name of Christ,
there will he be in the midst of them.

13th. Another favoured meeting;, and notwithstanding, as Benjamin Kidd had to express,
many, considering our small number, are sick and weakly, and some asleep;
yet the Lord is still graciously remembering Zion, and satisfying her poor with bread.

20th. Confined these two last days by indisposition.
It was some trial to be kept from meeting; but knowing whence all good cometh,
and waiting in my solitary sitting to feel him, who is omnipresent,
near to sustain my feeble mind,
he was graciously pleased to revisit my soul with his life-giving presence.
In the afternoon +++[+++I]
had a little conference with a dear niece, in which I imparted some spiritual advice;
being anxiously concerned that she may seek the God of her Fathers,
now in her youthful days.

21st. Poor, weak, and low, both as to my outward and inward state.
How do I long, like the poor woman formerly, to touch but the hem of his garment,
that I might be made whole.

23rd. A little revived and comforted today,
in the belief that I am still preferring Jerusalem to my chief joy.
O,
may "`my right hand forget her cunning,`" and "`my tongue cleave to the
"`roof of my mouth,`" rather than I should desert a cause so precious.

25th. In my silent sitting at meeting this morning, +++[+++I had]
some clear openings.
How is the Lord hiding the mysteries of his kingdom now, as formerly,
from the wise and prudent of this world, and revealing them to babes and sucklings!
Forever blessed be his holy name!

27th. When I brought my gift to the altar today,
I saw that I had done something which was to be removed before it could be accepted;
yet +++[+++I]
endeavoured to reason it away, thinking it was too trifling to be required;
but it was clearly shown me, that I was not to look at the smallness of the sacrifice,
if the Lord saw meet to require it at my hands, who "`seeth not as man seeth.`"
I am thankful that I was enabled to take up the cross and yield obedience;
in which I found peace.
May I ever thus attend to the pure discoveries of this divine teacher.

29th. Spent the forepart of the day profitably; but walking out in the evening +++[+++I]
met with several acquaintances, with whom I conversed,
and my mind got too much into the spirit of the world
which separates from the spirit of Christ.
Feeling this to be my situation, +++[+++I]
endeavoured to turn inward and feel after that which crucifies to the world,
and was favoured to feel my strength a little renewed.

=== Twelfth Month, 1791.

3rd. Another affecting instance of the uncertainty of time,
in the sudden removal of dear Mary Merryweather, a mother in our Israel.
A stripping time surely!

4th. How frequently necessary are the operations of the sword of the spirit,
to separate betwixt the precious and the vile;
and though it is painful to the creaturely part, yet +++[+++I]
am thankful to feel this work going on.
O,
that it may remove (though it may divide as betwixt the joints and the marrow)
everything that is contrary to the pure mind and will of the Lord,
is the sincere prayer of my heart.

6th. My mind sweetened and refreshed by the renewed
visitation of the heavenly Father`'s love,
very early this morning before day-light, as I lay on my pillow;
so that I can say from some degree of living experience,
good is the Lord and worthy to be feared and served forever.

11th. A favoured season at meeting, both morning and afternoon.
It was shown me that I should dwell more in the meekness;
and my heart was affected with the recollection of our blessed
Saviour`'s example of meekness and patience under suffering.
O, that I might, indeed, be enabled to follow him whithersoever he is pleased to lead.

14th. Have been confined these three days by indisposition,
having had another attack of the palpitation.
The struggle was so violent; that had not the arm of the Lord been underneath,
I think I never could have survived it;
but though the billows rose high they were not permitted to overwhelm me.
I still feel weak and low every way, yet +++[+++I]
have not cast away my confidence, believing the Lord is still near,
though he is pleased at times to hide, as it were, his face from me.

15th. A sweet refreshing season today,
attended with an earnest desire that I may not be found
in an unprepared state to meet the Bridegroom of souls.
O, that I may be preserved chaste in my love to him is the earnest breathing of my soul.

18th. In the forepart of the meeting the enemy was near spreading his snares,
and seeking to draw my poor mind off its watch; but my eye and cry being to the Lord,
who beheld the conflict, he was pleased, in gracious condescension,
to appear for my help, and the renewal of my strength.
May I walk more worthy +++[+++of]
such unmerited goodness.

19th. "`Strait is the gate, and narrow is the way,
which leadeth unto life,`" I find it so; but, O,
may I never grow weary of striving to enter in, nor faint in my mind;
ever keeping in remembrance that the crown is at the end of the race.

21st. Let the day pass over without retiring, suffering little things to prevent me:
but not feeling easy under this omission, when I retired to rest,
I besought the Lord to forgive me,
and strengthen me in future to follow him more faithfully,
being desirous to wash mine hands in innocency, that so I might encompass his holy altar.

26th. Oh, the daily warfare that must be maintained,
if we would run the Christian race! nothing short of a frequent
supply of divine nourishment can enable us to endure the combat.

31st. And now I am come to the close of the year.
On looking back I am a little revived with the hope,
that if I have not made much progress I have not been going backward;
and though I still feel myself a poor weak creature,
yet I have abundant cause of thankfulness that I
am still preserved in the land of the living,
notwithstanding the many assaults of an unwearied enemy.
Though I know not what trials may await me,
yet I desire not to be anxious about the future; but rest in firm reliance on the Lord,
that whatever he may see meet to dispense, will be for my good, even as for daily bread.
May I be preserved in it, and then let come what will come,
I believe it will be well with me.
Oh! this state of humble dependance is very precious in my sight.
