== Chapter 2

=== First Month, 1792.

4th. I am truly desirous that I may not be more in show than substance.
A specious outside may impose on men, but the Lord is a heart-searching God; yea,
"`he trieth the reins.`"
Search me, O Lord, and know my ways, and if iniquity be found within me,
be pleased to take it away; it is in thy sight I desire to stand acquitted,
let others think of me as they will.

6th. A silent meeting, yet to me a season of refreshment,
being favoured with a little of the celestial rain.
How precious are these watering seasons! surely they are intended to increase fruitfulness,
may mine bear some proportion to the labour bestowed by the good husbandman,
who is so frequently raising good desires in my mind; but,
alas! how are they often weakened by the lowering concerns of this world!

12th. My mind was led in my retirement today, to press after heavenly treasure,
which alone can enrich, and is not subject to decay;
nor will it ever wax old like a garment.
Oh, the excellency of divine love:
how far doth it transcend even the most refined delights of this world; ancient,
yet ever new!
May I dwell under its holy, preserving, sweetening influence.

16th. "`He which soweth sparingly shall reap also sparingly,`" "`but the
hand of the diligent maketh rich;`" may I be of this number.

18th. How do I love to feel self-abased, and my soul reduced to a child-like state,
believing it to be acceptable in the sight of the Father of mercies!

20th. A humbling time at meeting, under a belief that something would be required of me,
which would be a great cross to my natural disposition; yet am desirous of dwelling low,
and, if the concern should continue, that I may be enabled to do it faithfully,
though it should cost me the regard of the person reproved.

24th. A dreadful alarm of fire in the night on our premises;
but through the unspeakable goodness of Providence,
it was got under without any material damage.
O,
how do I desire to be made thankful enough for this renewed instance of divine preservation!
But alas!
I feel so poor and exhausted, both in mind and body,
that I fear my gratitude is not enough lively and fervent:
yet a little hope revives my drooping soul that our merciful Creator,
who knows the weakness of our frame, will be pleased to accept the integrity of my heart.

25th. Still indisposed and poorly from the late shock;
yet having been favoured with a little of the fresh incomes of heavenly love,
which is sweeter to my taste "`than the honey and
the honey-comb,`" I could desire nothing further;
this enjoyment being more than a counterbalance for every trial.

28th. Have been taking a review of the former part of my life,
which was mostly spent in folly and vanity, few, I think, exceeding me therein,
as far as I dared; yet, I remember I frequently felt remorse,
and had at times good desires raised in my mind after a better state,
but having a wrong example in some unprofitable associates,
I became greatly estranged and wandered far;
yet in unspeakable love the good Shepherd remembered me,
when I had forgotten him days without number;
and about the twenty-seventh year of my age he stretched forth his crook,
and gently drew me back into his fold.
How is my heart tendered with a sense of his goodness as I write,
that he should preserve my life until he had brought me acquainted with himself,
and shown me the joys of his salvation.
May these things sink deep in my heart, frequently pondering how much I owe to the Lord.

=== Second Month, 1792.

1st. Suffered my mind to be ruffled and soured by some cross occurrences this morning;
which, however, I strove to suppress, and believe it was not discovered by others;
but that did not satisfy me,
not feeling that sweet peace which I prize above every other enjoyment.
I retired awhile, and, centering down out of the cumbers and cares which had perplexed,
was favoured to feel something of that healing virtue, which now, as formerly,
heals every malady, and alone restores peace and tranquillity within our borders.

2nd. A pretty comfortable day, and I hope not spent in vain.
Agreeable tidings in the evening of some ministering friends likely to come this way;
which humbled me under a sense of the goodness of the Almighty,
who had thus inclined their hearts to visit this poor spot.

5th. When I brought my deeds to the light in my silent sitting at meeting this morning,
methought I discovered in myself an eye too quick-sighted to the failings of others,
and not enough to to my own; and begged that eye might be plucked out,
with everything that is of an offensive nature.

11th. On a review of this day I think I may venture
to say it hath been usefully and profitably spent.

13th. A bustling day, being that of Godalming fair,
yet I endeavoured to keep my mind as much out of it as I could; and,
finding a little leisure, took a solitary walk out of the noise and bustle;
in which my mind was sweetly impressed with a lively
sense of the many blessings I enjoyed beyond thousands.
It melted me into tears,
and my heart overflowed with gratitude to the bountiful Author of them to one so unworthy.
The day being very fine, and these impressions rendering my walk truly delightful,
it was with reluctance I quitted the tranquil spot for the hurry and noise of the town.

17th. I found it hard work this morning at meeting to keep
my poor weak mind from roving hither and thither,
nor could I find a resting place, though I sought it with many tears,
till near the conclusion, when I got more stayed,
and felt a degree of sweetness cover my mind.

23rd. Rose this morning a little after two o`'clock to watch with my dear uncle Kidd,
who having several fine sleeps,
I was desirous of improving this season of solemn quiet to my own advantage,
by repairing to the inexhaustible fountain of all effectual help,
feeling afresh my inability to do any thing aright, even to direct my own thoughts;
for alas! are they not evil continually unless preserved
under the pure influence of his holy fear?
O, that my soul might be arrayed therewith as with a garment,
to defend it from the various assaults of an unwearied enemy.
My mind +++[+++was]
sweetened and refreshed by this opportunity.

24th. In our little silent gathering today my mind was replenished with celestial showers,
yea, I was enamoured with the goodness and lovingkindness of God,
thus extended to the meanest of his works.
What an unspeakable favour, that we finite creatures, should, while in the body,
be permitted to feel in degree the weight of that glorious
crown which is reserved for those that hold out to the end;
but these seasons are rare, and intended doubtless to animate our faith;
not that we should tabernacle here, but press forward for the _mark._
O may I move on in fear and humility,
and so witness preservation in heights as well as in depths.

=== Third Month, 1792.

4th. When I sat down in meeting this morning a prayer arose in my heart,
that I might be preserved from forming to myself any likeness or image,
and that I might be enabled to worship the living God in spirit and in truth,
which petition, I trust, was measurably granted.
The afternoon I thought rather heavy, yet not altogether uninstructive,
it being shown me that there is but one path which leads to life.
Oh, what need then of increasing watchfulness!

5th. Though by no means an idle day,
yet I let trifling thoughts put by my retiring awhile to feel after a renewal of strength.
Felt uneasy at this omission on going to bed, nor could I give sleep to mine eyes,
till I had humbled myself before the Almighty,
and craved the continuance of his fatherly protection.

8th and 9th. Comfortable as to the outward:
when that is the case I have often had to remark the enemy is most busy with his assaults;
yet by frequently retiring inward to Him, whose name is a strong tower,
I hope he hath not prevailed so as to destroy the good seed of the kingdom:
strong have been my cries to the Lord that he would
be pleased to preserve me from this devourer.

11th. A searching time this morning at meeting.
Oh, how did I desire that every unclean thing might be brought forth and slain:
that nothing might be spared, which was appointed for destruction;
that the temple of my heart being made clean,
the Lord might delight to take up his abode there!
I felt his love afresh extended towards me;
and my soul was prostrated before him under a sense of his matchless goodness,
and my own unworthiness.

14th. Was thankful to feel a wrong disposition corrected.
O, may I ever attend to the secret reproofs of this divine Instructor,
who would assuredly lead out of all error and guide me into all truth; but, alas,
how often do I miss my way, for want of a more steady adherence thereto;
and so multiply crosses and difficulties, which more watchfulness might prevent!

23rd. My mind affected this morning with the account of the dangerous illness of a relation,
who, I fear, is not fully prepared for the solemn change; and the prayer of my heart was,
that she might be spared a little longer;
in hopes she might improve so great a mercy to her everlasting benefit.

24th. Felt weak and poor in my solitary sitting today, yet no room for repining,
believing it my due, having idled away several hours before in frivolous reading.

27th. The quarterly meeting at Alton;
which I believe was a season of renewed favour to many minds:
but being indisposed with +++[+++a]
head-ache, and meeting with many Friends, unsettled my mind.
I found it hard work to keep on the watch,
so that I partook but in a small degree of divine good:
yet in the meeting for discipline, +++[+++I]
was sweetly tendered at the reading of the testimony concerning dear Mary Merryweather;
and living desires arose in my mind to that gracious Power,
which had preserved her through the vicissitudes of time,
and at length centered her out of the reach of the enemy,
that he would also be pleased to preserve me to the same happy conclusion.
Nor can I doubt his watchful providence,
who hath hitherto supported me and poured unnumbered blessings on my head;
it is my own weakness I fear, knowing the frailty and deceitfulness of my own heart,
lest I should one day or another fall by the way.

29th. My mind sweetly refreshed in my silent sitting today
on reading the two last chapters in the Revelations,
as it hath often been.
O,
that I may so walk as to become an inhabitant of that excellent
city where nothing that is defiled or can annoy shall ever enter.

=== Fourth Month, 1792.

1st. Our quarterly meeting begun.
Soon after I sat down in meeting I was made sensible that Divine Good was near,
by the sweet quiet I felt my mind drawn into,
which holy covering I believe spread over many minds, if not all, in the meeting,
so that it proved a heart-tendering season.

2nd. In the meeting for worship the extending of heavenly regard was renewedly felt,
and I believe some whose minds were deeply centered,
went away richly laden; I also partook in degree, but being too much like Martha,
encumbered about many things, I found it hard work to keep my mind stayed,
so that I believe I suffered loss:
yet was enabled to get through the business of the meeting to admiration,
which is cause of thankfulness, that I should be at all fitted,
or in any degree qualified, for service in the church;
yet I well know from whence my help cometh.

6th. Our monthly meeting, which I attended, and in it my strength was a little renewed,
notwithstanding the confirmation of a painful occurrence,
the grievous fall of one who had been signally favoured.

10th. A little encouraged to hold on my way,
having had renewedly to believe that the Lord is
still graciously near for my preservation and help.
A fresh incitement to love, fear, and trust in him.
In the evening falling into company my mind was too
much leavened into the spirit of the world.

11th. Went to Guildford to meet two Friends in the ministry.
They were led (in meeting) in close searching testimonies.
O, that it might awake the careless and lukewarm,
some of whom seem settled as on the lees.
An encouraging time in a friend`'s family to the young folks.
In the evening meeting here, as well as in several sittings,
they were led to encourage and animate us to press
forward for the mark for the prize of the high calling,
which is Christ Jesus.
Oh, how was my soul prostrated in deep reverence and thankfulness,
under a renewed sense that the Lord had not forgotten Zion,
but was thus sending his faithful servants to comfort her waste places,
and cause the solitary to rejoice:
my soul was nearly united to them and humbled that I should
ever be counted worthy to feel this precious unity,
which is surely the bond of peace, and still remains the badge of discipleship.

13th. Another favoured heart-tendering season in our little gathering today; yea,
my cup was made to overflow;
but before the meeting closed I let in a fear that some trial might
succeed this enjoyment (having before found it so),
and so it proved; but keeping near the centre and safe-hiding place,
my mind was preserved in a good degree of peaceful quiet under it,
so that I hope the enemy had no advantage.

15th. A heavy meeting;
in which my mind was much exercised that I might not give way to the slothful disposition
which I believed too much prevailed over the meeting in general (a very few excepted),
and I was strengthened to maintain the watch for some time, but afterwards lost ground,
and before the meeting closed got from the true centre into a wandering disposition.

25th. Gave way too much to a roving disposition, for which I was humbled in the evening:
in other respects a well-spent day.
Surely it is profitable thus often to retire and see whereabouts we are.
I find it so, and believe it has been blessed to me;
yet how many do I see running on days, months, and years,
without seeming to take any account how they spend their time.
Alas!
I often think how will they be able to stand so long a reckoning
with that God whom they have forgotten days without number!
I find enough to do to keep my accounts clear by short reckonings.

27th. A season of renewed favour in our little silent gathering today.
O, that some of our careless profession would come, taste, and see for themselves,
how good the Lord is to them that fear him.
Then would they not let trifling things hinder them from attending week-day meetings,
as is now sorrowfully the case.

29th. I sat down in the afternoon meeting under discouragements,
thinking we had a poor company;
but my eye and cry being to the Lord (who is alone able to help
us) that he would be pleased to enable me to maintain the watch,
he, in great condescension, granted my request,
and sweetly tendered my spirit before him.
May I walk worthy +++[+++of]
such unmerited favours.
I sometimes think when I sit thus broken in our meetings,
that I am as a gazing-stock to those who,
for want of coming under the operation of truth on their own minds,
are ready to account it a strange thing; but, O,
may I ever count it matter of rejoicing to be thought a fool for Christ`'s sake.

=== Fifth Month, 1792.

6th. Called on dear uncle Kidd before I went to meeting,
who is confined to his bed by indisposition.
He enquired if I was going to meeting; I told him I was;
he then desired I would think of him when it was well with me;
which greatly humbled me even to tears, considering my weakness and infancy,
and how much more I stood in need of his prayers,
who appears near the end of his pilgrimage, while I poor creature,
have made but few advances in the heavenly race.
Under these considerations I went to meeting, which proved a season of encouragement.
In the afternoon +++[+++I]
felt something that would have exalted self, for which I felt gently corrected.
Oh, how did it humble me! and yet I secretly rejoiced
to find the best of guides and instructors so near,
inclining mine ear to hearken, and mine heart to receive instruction.
With what delight did I sit under his teachings!

13th. Deborah Darby, Rebecca Young, and Frederick Smith attended our meetings,
both morning and afternoon.
In the former they bore living testimonies to the
excellency of the truth as it is in Jesus;
encouraging those in whose hearts the day-star had arisen to follow on,
and not shrink from suffering; and inviting, in persuasive language,
those who were at a distance to come and see for themselves how good the Lord is.
The meeting concluded in heart-tendering supplication.

14th. Accompanied our beloved friends to Guildford.
Another favoured meeting, and a precious opportunity in a friend`'s family, not soon,
I hope, to be forgotten by some present; and by one in particular,
to whom I believe a merciful invitation is extended.
I gave up to what I believed a small pointing of duty in cautioning the person
in question not to suffer his present impressions to be easily effaced.

16th. Preparing for attending the yearly meeting,
my mind was unexpectedly tendered under the consideration,
that though I was now leaving home in full health and strength,
yet I might never live to return; which thought, however, was not distressing to me,
but the prayer of my heart was that I might be preserved in innocence,
and prepared to meet the awful summons whenever it should
please the Father of mercies to send it to my house;
that so the solemn messenger may not prove a king of terrors.

21st. Our women`'s yearly meeting began this afternoon; and, I think,
I never felt the divine covering more evidently spread over a meeting +++[+++than]
soon after our first sitting down,
so that many were broken into tears before a word was spoken.

=== Sixth Month, 1792.

4th. No suitable time for retiring today, yet +++[+++I]
was preserved in much quiet; and, I trust, in a good degree of the Lord`'s holy fear.

11th. A busy day;
yet I still retain a lively sense of a sweet impression with which
my mind was favoured while employed in outward occupations.
A circumstance occurred,
which led me a little to look forward to some trials which might await me;
and the thought struck me, how I should be supported under them;
when I felt such an unusual sweetness cover my mind
as seemed to remove every anxious fear,
and my faith was strengthened to believe, that the Lord,
who was thus graciously caring for me,
would not permit any thing to befall me but what he would enable me to bear.

12th. On setting down the above remark, which I had no time for yesterday,
my mind has been renewedly humbled, under a sense of the Lord`'s goodness;
and methought I could do no less than set up, as stones of memorial,
such signal blessings vouchsafed to one so unworthy.
O, may they never rise in judgment against me.

21st. A busy morning: went in the afternoon to Guildford to meet dear Martha Howarth,
and Priscilla Hannah Gurney, who had an evening meeting there,
which to me was rather a laborious one; partly owing perhaps to a bad sick head-ache,
which I had to struggle with.
Martha Howarth was led to describe the true foundation,
and the advantage of building on it,
and how unhappily some had missed it for want of digging deep enough,
and so had built on the sand, which could not stand the day of trial.

25th. A beautiful morning.
Rose early, yet found the tempter near,
spreading in my view pleasant pictures never likely to be realized.
May they be stained in my view,
and every roving thought and imagination bounded by the Lord`'s pure fear.
Oh, this daily warfare!
I desire not to shrink from it, but to be renewedly strengthened to maintain the combat.

=== Seventh Month, 1792.

1st. Went to Croydon and attended the quarterly meeting.
According to my feelings it was a season of renewed favour,
believing the crook of divine love was still held out to a backsliding people.
O, that they might be wise enough to close in with such repeated gracious invitations,
while the day of mercy is lengthened out.

8th. A humbling season at meeting;
not only under a renewed sense of my manifold weaknesses,
but my former sins being set in order as it were before me.
I saw afresh that where ill habits had taken deep root,
it must be a work of time entirely to extirpate them;
yet a little encouraged with the belief that this work was gradually going on.
O, may the Lord (who is alone able) be pleased to perfect it to his own praise,
whatever sufferings I undergo in order for its completion.
My mind +++[+++was]
sweetly tendered in the evening on hearing that some of our young folks,
who are setting out in life, are taking up the cross, not only in their appearance,
but also in the furniture of their houses, coming back to primitive simplicity.

10th. Poor and weak, yet have believed at this time,
that it is good for us to be thus stripped and abased,
that no flesh may glory in the presence of the Lord,
seeing our sufficiency is alone of Him, who is worthy of all praise and adoration.

12th. This day I think not unprofitably spent,
and my faith a little animated to press forward, though nothing to boast of.

18th. Too easily put by retiring, yet endeavoured to step safely along,
though in much weakness.

28th. A busy day, my mind too much encumbered,
and pettish with a dear child who was somewhat untoward;
yet a little sweetened this evening under the precious influence of Truth.
How do I love to hear as it were the voice of the Lord in the cool of the day;
nor do I wish, like Adam, to hide myself from his pure eye,
desiring to bring my deeds to the light;
and to feel judgment pass over the transgressing nature: for, Oh, he is rich in mercy!

=== Eighth Month, 1792.

13th. Have given way too much to a roving disposition today, which I feel wrong, and Oh,
how have I desired, in this my retirement,
to be enabled to mount a little upward above this low and lowering world;
to shake myself from the dust of the earth,
and feel my mind renewedly strengthened to press forward,
laying aside every weight and burden!
This surely is a great attainment, yet it is what my poor soul,
amidst all its weaknesses and imperfections often aspireth after.

14th. I trust a well spent day.

15th. Have renewedly experienced the truth of that assertion,
"`A man`'s foes shall be they of his own house;`" having
been much tried today with a wrong disposition of mind,
which, I fear, I too much yielded to in the first place;
but feeling the gentle reproofs of my good guide, who enabled me to turn to him,
through his gracious assistance, they were measurably put to flight.

26th. Our preparative meeting, previous to the quarterly meeting.
When I sat down I felt so poor and destitute of divine good,
that the enemy would have persuaded me it was in vain to press after it; but,
as he was a liar from the beginning so I found him in this instance;
for after some conflict with a lukewarm spirit,
I was enabled to draw near to the fountain of living waters, and was sweetly refreshed.

=== Ninth Month, 1792.

4th. A painful feverish night.
Rose weak and languid; yet after a while got better: renewed cause of thankfulness!
O, that I may be made enough so, for even this disposition is not at our command,
but as we receive it from God who is the giver of every good and perfect gift.

5th. Some unpleasant circumstances; and my mind not so comfortable as at many times,
having let in some doubts;
yet I trust desirous of being directed aright even in what may appear trifling things.

6th. Still embarrassed; yet have concluded to do what appears safest,
though contrary to my inclination.

7th. My mind seems relieved by doing what I believed right, yet +++[+++I]
found it hard work this morning at meeting to get at the spring,
but was at length favoured with a little refreshment, which my soul panted after.

10th. Rose with fresh desires after heaven and heavenly treasure,
and that I might be preserved from every appearance of evil.
In the afternoon, when I sat down to work,
I felt my spirit unexpectedly contrited before the Lord; thankful for this favour,
I laid it aside, and sat in much tenderness before him a considerable time,
for sweet indeed is his love.
O, that I was a more worthy partaker.

12th. Have been led this morning to admire with humble thankfulness,
the continued kindness and long suffering of a gracious God towards one so unworthy,
and that in all my wanderings,
he should be pleased to watch over me with a father`'s love,
and bring me gently back again into his fold.
How can I do less than +++[+++thus]
commemorate his goodness, who hath dealt so bountifully with me, a poor worm!

16th. Made myself work today by suffering my mind to go after trifling things,
before I went to meeting, so that I was obliged to labour to get clear of them; yet,
after awhile +++[+++I]
was favoured far beyond my deserts,
even with the liftings up of the light of the Lord`'s countenance upon me.
O my soul,
how vast is the debt thou owest! mayest thou walk in deep humility and fear before him.

20th. Nothing particular has occurred these last few days;
a portion of each has been spent in retirement, and, I may with gratitude acknowledge,
that in these solitary sittings, I have felt the overshadowing of the Divine wing,
to my great refreshment and encouragement;
yet I also retain a humbling sense of my manifold weaknesses.

30th. After some conflict with a wandering disposition,
both in the morning and afternoon meetings +++[+++I]
was favoured to partake of the hidden manna which
can alone nourish the soul up to eternal life;
and was led a little to behold the beauty and excellency of that
state of innocence in which our first parents were created,
and to aspire after it.

=== Tenth Month, 1792.

1st. My mind disquieted and uncomfortable at meeting with a disappointment,
for want of that true resignation with which we ought to meet every event.

2nd. More comfortable,
yet do not feel that entire resignation of my will
to the Lord`'s will which I have laboured after,
having no doubt but every dispensation is ordered in unerring wisdom;
yet nature is sometimes ready to start aside.
O, that mine may be brought into true subjection, is the sincere prayer of my heart.

3rd. Am comforted to feel my mind restored to its wonted tranquillity.
Being in company in the evening, +++[+++I]
gave way too much to the vivacity of my disposition, so that it bordered on levity,
for which I felt condemnation.

4th. As soon as I awoke this morning the recollection
of last evening presented itself painfully,
so that I was humbled under a sense of my weakness before the Lord,
who I believe accepted my penitence and restored peace to my soul.
How unmerited +++[+++was]
this favour!

5th. Our dear friends Martha Howarth and Priscilla
Hannah Gurney came to pay us a religious visit;
my heart rejoiced to see them; they attended our week-day meeting,
which was also our monthly meeting; the former had a very close time in testimony,
apprehending the feelings given her that there was unfaithfulness amongst us;
and was led to speak of the parable of the sower,
and the different kinds of ground the good seed was sown in,
and the various things which prevented its growth, etc.

7th. The above-mentioned friends attended our meeting,
Martha Howarth again led in a close manner to expostulate with some amongst us,
who she believed were not grieved for the afflictions of Joseph,
but were settled down in a state of carnal security.
My mind was much humbled under the consideration that the Lord should in great
condescension thus permit his chosen servants to plead with the gainsayers.

24th. My soul hath adopted the language of one formerly; "`If I forget thee, O Jerusalem,
let my right hand forget her cunning.
If I do not remember thee, let my tongue cleave to the roof of my mouth;
if I prefer not Jerusalem above my chief joy.`"

31st. The morning taken up with family affairs and attending my scholars,^
footnote:[She for some years kept a school for about eight or ten poor children.]
and the afternoon in visiting, so that I could find no time for retirement,
which I regret, having doubtless suffered loss.

=== Eleventh Month, 1792.

4th. I felt the renewed extension of the heavenly Father`'s
love soon after I sat down in meeting this morning,
and Oh, with what joy did I meet the beloved of souls!
How vast is the debt I owe him!
May I manifest my gratitude by a more steady obedience and unreserved dedication of heart.
I desire to do so, but I fear my own instability.

6th. My time so fully taken up that there seemed no time for retiring these two days;
yet I trust the general disposition of my heart hath been right.
Received an instructive lesson last evening by the departure of one (of whom I had entertained
a far different opinion) from the simplicity which once adorned her.
My heart was sorely pained on her account, and with tears I besought the Lord on my own,
lest I should also fall by the way,
and I felt a willingness to be stripped of every earthly
delight rather than forfeit this best of blessings,
his favour, which alone can truly enrich.

14th. A fresh scene of trial and affliction opened
in the alarming illness of my dear sister Lettice;^
footnote:[Wife of Jeremiah Waring, Alton, Hants.]
and Oh,
the prayer of my heart hath been that it may be brought into a
perfect resignation to every dispensation of unerring wisdom;
for "`shall not the Judge of the whole earth do right.`"

18th. A humbling time at meeting this morning,
feeling afresh my inability to take one step aright, without divine assistance;
yet my faith and strength +++[+++were]
a little renewed in the all-sufficiency of that arm
of power which had hitherto preserved me.

22nd. My soul bowed under a sense of the Lord`'s goodness
in permitting me still to approach his holy footstool,
amidst my manifold infirmities.

26th. Much affected this morning by my beloved father`'s
finding something of a paralytic affliction,
looking on it as a gentle warning.
O, that I may be truly resigned, and patiently submit to the Lord`'s will,
without a repining thought.

27th. Abundant cause of thankfulness today; my dear father better,
and a more favourable account from Alton.
May my gratitude bear some proportion thereto.

30th. Our week-day meeting.
A baptizing season.
Methought my lamp was afresh trimmed, and replenished with heavenly oil.

=== Twelfth Month, 1792.

1st. A busy day; yet +++[+++I]
found time to visit the sick, and administer a little help.
I am thankful that ability was given.

6th. Have been led to look back a little and recount the Lord`'s mercies,
and my heart hath overflowed with gratitude for all his blessings,
both spiritual and temporal.

7th. Went to our monthly meeting, which proved an instructive season,
notwithstanding I had something to war with,
having too much given way to a wrong disposition.
O, that I may sufficiently profit thereby.

11th. My strength a little renewed this evening in my solitary sitting in my chamber.
Precious to me are these seasons: yea more than the increase of corn, wine, or oil.

16th. An instructive season at meeting: was desirous of sitting in poverty and dryness,
rather than offer any thing polluted.
O, to be preserved clean-handed.

18th. A well spent morning.
In the afternoon +++[+++I]
did something with a good intent,
yet am not quite satisfied in my mind that it was right,
which brought heaviness and a cloud.

19th. More comfortable, yet the cloud not totally removed.
O, that every motive as well as action may be brought to the measuring line.

21st. A humbling season at meeting, and trust I felt something of the healing waters.
O, to be washed clean, that no impurity might remain.
This was the prayer of my heart.

29th. These two days have passed quietly away, and I trust, have been spent profitably,
yet in my retirement uncommonly poor and stripped;
under which I felt in a good degree resigned.
An affecting account of the increasing indisposition of my dear sister Lettice.
