== Chapter 3

=== First Month, 1793.

1st. Another year begun, and I doubt but small advance in the heavenly race;
yet it is cause of humble thankfulness, amidst my manifold weaknesses as a creature,
that I am still preserved alive in the truth.
Have retired twice today to feel after that blessing which alone can enrich the soul,
but felt uncommonly stripped and poor; so that a sigh and a tear were all I could offer:
yet +++[+++am]
preserved in a good degree of quietude.

4th. Oh, my self-love!
I have had cause to mourn on this account today.
How many actions, which appear specious in the sight of men,
spring from this corrupt root!
Great are the advantages of a daily examination.
What numberless foibles have I discovered in myself
since I have been in the practice of it,
which before passed unobserved.

9th. Paid a visit to a relation, who showed me much kindness; but,
alas! my heart was pained at beholding the deviation from the simplicity of truth,
and what a snare there is in riches: how few can withstand them,
or are watchful enough to prevent their undue influence.

13th. Went to Longford meeting, where, after waiting at Wisdom`'s gate,
my soul was sweetly refreshed with the fresh flowings of Shiloh`'s streams: yet I,
poor unstable creature as I am! got off my watch,
and in a great measure lost the sweet savour thereof.

19th. My time fully occupied in attending my dear sister: and,
though I have had no suitable time for retirement, yet +++[+++I]
have frequently felt the tendering influence of truth on my mind while thus engaged;
which leads me to believe that the Lord prefers mercy to sacrifice.

24th. These several days taken up (as heretofore) in a close attention to my dear sister;
yet a fresh temptation hath presented, to which my mind has too much yielded at times,
it being pleasant to look at; but at others,
by retiring inward I have been favoured with ability to get from under it;
and the prayer of my heart has been, that I might feel every desire limited,
and ask nothing but what the Lord saw meet in his infinite wisdom to dispense.
O, that I could rest here,
humbly thankful for the many blessings I enjoy beyond thousands,
and how unworthy thereof I cannot but acknowledge with confusion of face.

=== Second Month, 1793.

2nd. Came home, on hearing my dear father was confined with the gout:
found him better than I expected, which calls aloud for gratitude.

9th. Another week passed away, yet I hope not spent in vain.
My time has been pretty fully occupied in attending my dear father and my scholars,
visiting the sick, and in family affairs: yet amidst these various occupations +++[+++I]
have not lost sight of that better part which Mary chose; having my mind, at seasons,
sweetly attracted to feel after that living spring,
which can alone furnish with ability for every good word and work.

14th. Felt the pure influence of truth on my mind this morning as soon as I awoke,
for which I felt thankful,
and was desirous of retaining this precious savour through the day;
but the many encumbering things have too much prevailed, so that I feel poor and dry,
yet quiet, and I hope humble: much need have I to be so.

21st. Came to retire with a heart panting after the refreshing stream of Shiloh; but,
alas! dryness and poverty is my portion.
I desire to be humble and patient under this dispensation,
and learn what it is to want as well as to abound.

22nd. After struggling awhile this morning at meeting, +++[+++I]
had to set up my Ebenezer, and say,
"`hitherto hath the Lord helped me,`" blessed be his worthy name forever.

26th. Amidst all my weaknesses fresh aspirations after purity
and perfect holiness arose in my retirement today,
and I was favoured with a little access to the fountain of living waters.

=== Third Month, 1793,

3rd. A precious season at meeting this morning.
May this renewed favour excite to more vigilance and circumspection,
for surely the Lord looketh for fruit proportionable to labour bestowed.

9th. A day I think profitably spent as to action,
and I trust my mind pretty much preserved from hurtful things; yet +++[+++I]
am truly desirous that every motive may be brought
under the purifying operations of truth.

14th. Answered my dear father impatiently.
Surely I, who have so many weaknesses of my own,
ought to bear with patience those of an aged parent.

16th. Too unguarded in my conversation, speaking censoriously of an absent person,
not enough keeping in view the golden rule of doing as I would be done by.
O, for more watchfulness that I might escape condemnation, yet +++[+++I]
am thankful to feel the reprover near.
May he never leave or forsake me.

21st. Hastened to Alton to see my dear sister Lettice; found her rather better again,
but in the evening she altered for the worse, and a trying night succeeded;
she was for a considerable time speechless and convulsed; but after awhile, reviving,
called us separately to her, and took an affecting farewell;
saying as she pressed us with fervour to her bosom, it was like rending her asunder,
and that it seemed, from the nearness she felt for us,
"`as though she could drink in our spirits.`"
She gave much advice to the servants, respecting their care of the dear children,
begging them not to leave them to strangers;
adding "`Oh how they cling around my heart!`"

22nd. A most trying day: my beloved sister`'s pain excruciating;
but getting easier towards evening we ventured to go to bed, as she requested it.

24th. Called up between three and four o`'clock this morning,
my dear sister altering for the worse, and as we apprehended dying:
yet the all-wise Disposer of events, who cannot err,
though to us his ways are unsearchable and past finding out,
did not see meet to finish the work: she again revived a little,
and took nourishing things.
In the evening sitting in silence round her bed,
our minds were made sensible of the overshadowing wing of heavenly love,
when a friend was engaged in supplication by the bedside: soon after this,
the dear suffering creature was deeply tried with a severe conflict of spirit,
fearing the hope she had entertained was not well grounded,
which was very exercising to our minds, when these words, +++[+++alluding to Isaiah 54:8th.]
sprang livingly in my mind, and also in my brothers,
"`for a moment I hid my face from thee,
but with everlasting kindness will I return unto thee,`" which was a relief to us,
although she was permitted to struggle with her fears for some time:
but after awhile broke out thus, "`O, praise the Lord,
I shall now soon have to rejoice with joy unspeakable and full of glory.
Oh, the peace that I feel, it passes all understanding!
O, sing praises, sing praises.
To feel this rock, at such a time, how comfortable, etc.`"

25th. Sister Lettice lay pretty quiet most of the day;
in the afternoon asking her to have a little wine, she said, "`No, my dear sister,
no more wine, till I drink the new wine.`"
Was nearly cold for several hours, yet again revived.

26th. A dull quarterly meeting-day,
several afflictive events rendering it unusually small;
and all of us engaged in the solemn employment of
watching round the dying bed of my beloved sister,
who could not clearly articulate, yet made us sensible of her wants,
and frequently prayed to be released;
which awful event took place about five o`'clock in the evening,
leaving on our minds no doubt of her glorious change
from pain and sorrow to everlasting joy and rejoicing:
which administered to us, who had seen her inexpressible sufferings,
rather cause of humble thankfulness than excessive mourning;
though we painfully felt the separation.

29th. The remains of my beloved sister interred;
and cannot but acknowledge it a favour that we had the company
of some valuable friends on this solemn occasion,
particularly dear Job Scott, whose company was truly acceptable.

=== Fourth Month, 1793.

1st. Our quarterly meeting (at Guildford).
Dear Job Scott bestowed much labour.
May the fruits appear after many days.
I was enabled to get through the business of the meeting as clerk,
to my humble admiration.

4th. I trust, amidst my manifold weaknesses as a creature,
I still love the appearance of our blessed Redeemer, however small and lowly;
either as a reprover or comforter.
May I ever cherish it as the best of blessings.

10th. A fatiguing day; yet think, in the evening, I might have found time for retirement,
if I had not been lukewarm.
Content not thyself, O my soul, with making this remark,
but be willing to abide under condemnation.

11th. What an inestimable favour that there is, to this day, a Bethesda,
for the Lord`'s children to repair to and wash;
that they may feel their health renewed as from day to day!

14th. Seasons of conflict between nature and grace,
both in the morning and afternoon meetings; yet trust I may add, with thankfulness,
that the latter prevailed in some degree.
Oh, how was my poor mind tossed from wave to wave!

16th. Too much outward in my mind, and dwelling on things unprofitable; but,
retiring awhile in the evening, +++[+++I]
have endeavoured, with divine assistance, to shake myself a little from earthly desires,
and to cast my whole care on Him who hath hitherto blessed me;
indeed far beyond my deserts.
Oh, the sweet peace which I feel when enabled to repose
all my cares on him! every anxious thought subsides.
O, that I could dwell in this quiet habitation: but alas, how great is my instability!

23rd. How beautiful does the outward creation appear!
What resemblance does my soul bear to it?
I trust there is a little greenness, which is a sign of life at the root;
though I doubt but little fruit.
O, that increasing faithfulness may appear.

24th. Felt a wrong disposition rising this evening, but was enabled to suppress it:
envy at hearing the praise of another, at which I ought to rejoice; and I hope I now do;
at least, I desire to do it.

30th. Another busy morning, and the afternoon spent in visiting some relations;
and though far from unprofitable company,
yet I always find visiting about dissipates the mind.

=== Fifth Month, 1793.

1st. Was at the week-day meeting +++[+++at Alton], this morning,
in which I trust the watch was in a good degree maintained;
yet think I scarcely ever remember a more exercising time;
a sigh and a tear seemed all I could offer.

3rd. Came home.
My poor thirsty soul abundantly replenished this morning, in our week-day meeting,
with celestial rain.
It is, I trust, with a degree of humble gratitude, that I make this remark.
May I ever be enabled to number the blessings which I am favoured with,
and may it be my daily concern to improve them.

8th. Still struggling with my frailties.
What an unspeakable favour that the Lord should still
condescend to aid me with his Spirit;
in limiting the desires and thoughts of my vain heart.
O, that it were wholly conformable to his divine will, and my will wholly slain.
Then "`instead of the thorn would come up the fir-tree,
and instead of the brier would come up the myrtle-tree, etc.`"
Blessed exchange!

10th. A fresh scene of trial and affliction opened on us today,
under which I was favoured to feel a degree of humble resignation.

15th. My poor weak mind disquieted with some cross occurrences this morning,
for want of keeping on the watch: never, sure,
had I more need of it than at this juncture,
when adverse winds blow from different quarters.
O, to keep in the patience.

25th. Since the last remark, +++[+++I]
have been to London to attend the yearly meeting, which I esteem a great favour:
and though my poor mind has at times been greatly
depressed on account of a very afflictive event,
and prevented from much enjoyment in company, even of valuable friends,
whom I loved and esteemed,
yet I have with sincere gratitude to acknowledge
that the staff hath evidently accompanied the rod;
and some seasons of sweet refreshment +++[+++have]
been mercifully vouchsafed.
May renewed vigilance and circumspection denote the
deep sense I retain of such unmerited favours.

=== Sixth Month, 1793.

3rd. Have been favoured, in my solitary sitting this evening,
to see some of the various stratagems of an unwearied enemy
to destroy and lay waste the good seed of the kingdom.
How cunning, how subtile is he, transforming himself at times into an angel of light!
O, may I dwell near that divine Power, who alone can preserve from this devourer.

5th. Have been led this evening to look back a little,
and number some of the many blessings received.
A humbling yet profitable employ; as it tends to reduce self,
and strip it of every fancied excellence.

8th. Took a walk.
Was too light and airy in my conversation, for which I quickly felt gently corrected,
which humbled me; and when I returned, +++[+++I]
sought retirement; when I was enabled to approach Him whom I believe I had offended;
and believe my penitence and tears were accepted.

14th. Indisposed.
Stayed from meeting; but did not let the time pass unimproved:
during my silent sitting before the Lord,
the remembrance of my dear departed sister Lettice was unexpectedly brought to my mind,
with so much sweetness and brokenness,
that it seemed as if our spirits were afresh united.
The impression left is pleasant.

20th. Sat up last night with a sick friend; which was an instructive season to me.
O, my soul, mayst thou sufficiently improve by these lessons; line upon line, etc.
Am thankful in believing that my faith and confidence in the Lord does increase.

21st. A sweet refreshing time at our week-day meeting, though silent.
Oh, what an unspeakable favour to feel an evidence at times
that we are not following cunningly devised fables,
but the eternal living substance!

30th. Went to our quarterly meeting at Wandsworth;
thought the morning meeting rather dull; the evening and next morning +++[+++were]
favoured seasons:
and though dear Samuel Emlen and Richard Baker were led in close searching testimonies,
yet they seemed fully to believe that the arm of divine compassion
and regard was afresh extended to a backsliding generation.
Marvellous love and condescension!
O, that it might prevail on some,
who I believe have strayed far from the true sheep-fold,
to return while the day of mercy lasts.

=== Seventh Month, 1793.

3rd. Have felt the attacks of an unwearied enemy to draw my mind from its true centre,
and to lay waste every good resolution;
insinuating that a state of perfection is unattainable:
but was he not found a liar from the beginning?
So doth he still remain.

9th. Have felt the attractive influence of truth divers times today; and once,
in particular, suppressing a wrong disposition,
and enabling to flee to that name which is a strong tower.
O, that I could dwell ever there; then would nothing be suffered to annoy.
But, alas, I have often to mourn my instability!

23rd. Fresh trials of patience, under which +++[+++I]
was preserved in a good degree of quiet; which I esteem a favour: and +++[+++I]
have also had, this evening, renewedly,
to believe that it was nothing short of divine regard
which first drew my mind to these frequent retirements;
and am well convinced that it hath been a means of preservation.

29th. Sat up last night with a sick child.
My mind, both then, and today, was too much inclined to dwell on a subject which I think,
if too much indulged, may be hurtful to me; yet +++[+++I]
have frequently breathed to the Lord for preservation within the limiting power of Truth.

=== Eighth Month, 1793.

2nd. Went to our monthly meeting:
which proved (notwithstanding some unwatchfulness) a baptizing season.
Among other things, dear uncle Kidd was led to mention, in the course of his testimony,
that passage in scripture, "`And I will turn my hand upon thee,
and purely purge away thy dross, and take away all thy tin.`"
How did it prostrate my soul before the Lord,
with fervent desires that he would indeed thoroughly
purge my heart of every defiling thing!
Often am I made sensible of its impurity.

13th. Not idly spent, as to action; but my mind too much outward,
and too easily yielding to anxious thoughts.
How much work does unwatchfulness make!
Humbled this evening with the retrospection of my various infirmities as a creature;
and how often they get the ascendancy over my good resolutions.

18th. A precious watering season this morning at meeting.
What can I render unto the Lord for all his benefits?
Stayed at home from meeting the afternoon from necessity, not choice.

25th. The rest of last week confined by illness; yet was gently dealt with;
and so far recovered as to get downstairs today;--renewed cause of humble thankfulness.
Am fearful I have not yet learned sufficient meekness and patience under suffering.
O, for an increase of it and every other virtue.
What a poor creature am I when left to myself,
and from under the seasoning virtue and efficacy of truth,
which can alone preserve from the snares of death.

30th. These last few days have been much taken up in preparing and coming to Bristol;
yet my mind has, at times, been enabled to retire to the true centre,
where I have felt quiet.

=== Ninth Month, 1793.

11th. Spent too much time today in unprofitable reading.
Was made renewedly desirous this evening, in my little solitary sitting,
of having my will made subservient in all things to the divine will.
Oh! this is a great attainment;
but am thankful at times to feel my soul pressing after it as the first of blessings.

14th. Met with a circumstance which tried my poor weak mind;
yet laboured after a state of true resignation and quiet,
which was in some degree attained to.

15th. I trust truly abased in my sittings at meeting this day,
under a renewed humbling sense of my weaknesses; yet, in the evening meeting,
my poor vessel seemed for a season the sport of wind and waves;
but was at length favoured with a calm,
which led me to believe that the good pilot was still
near in order to preserve from wreck.

26th. The greater part of this day spent in company;
so that I was glad when the evening came to go to meeting,
where my thirsty panting soul was replenished with celestial rain.

29th. Rather poorly in the morning: felt relieved after I got to meeting,
which I hope I was truly thankful for;
as well as for renewed assistance to approach the alone Physician of value.

=== Tenth Month, 1793.

12th. Reached London after a fatiguing journey all night;
yet favoured to get along without accident:
and the forepart of the journey rendered pleasant,
by my mind being profitably engaged in a retrospection
of the Lord`'s gracious dealings with me;
and in a renewed belief that he was still caring for me, and watching over me for good.

24th. Was at Devonshire-house meeting; which, though nearly silent,
was an instructive season to my poor soul.
I was made thankful in believing that my will was
in some degree conforming to the divine will.
O, that I was wholly conformed.
What encouragement have I to trust in the Lord, who is dealing thus graciously with me!

25th. Was afresh enamoured with the beauty of holiness,
in our little silent gathering today; so that I thought it was good to be there.

31st. These last few days have afforded but little time for religious retirement;
but though I fear some part of them has not been
spent so profitably as it might have been;
yet at times I have found my mind secretly attracted by divine love to its proper centre;
and can thankfully acknowledge,
I have been preserved in a good degree of quiet dependance on Him,
who can alone preserve from the various snares which hourly await us;
and who best knows how to dispense suitably to his dependant creatures.
He is indeed an inexhaustible fountain;
and in his hand are the hidden treasures of wisdom.

=== Eleventh Month, 1793.

7th. This last week confined by illness;
which I fear I did not bear with that full resignation
and meekness of spirit which I should have done;
though it was often the concern of my mind to press after it,
even in the silent watches of the night.
During this time of my confinement I met with a trial which none knew of but the Lord,
whose compassionate eye is over all his works (yea, the very meanest of them,
or else I had perished long ago).
He sustained my poor feeble soul and enabled me in some
degree to adopt the language of "`Thy will be done.`"
Gracious condescension! of myself I was wholly unequal to this attainment.
It is thou alone, O Lord, who canst set bounds to the ocean that it cannot pass;
and say "`hitherto thou shalt come and no further,
and here shall thy proud waves be stayed.`"
Hadst thou not graciously superintended the vessel, how often would it have been wrecked.

9th. Got out again to our week-day meeting;
in which my poor mind was sweetly replenished with celestial rain.
At the close of it, a committee was held to nominate women overseers,
at which I was proposed as one.
Oh it brought great weight over me; and I ventured to object to it,
but do not know whether my objection will be accepted.
If I am chosen, I desire, with much sincerity,
that I may be enabled to set a double watch over my conduct, while watching over others;
that I may so walk as to preserve my garments free from spot or any such thing.

15th. Went to Staines to see my dear relations there, an opportunity offering;
yet it being our week-day meeting, +++[+++I]
was not quite easy about it:
but feeling that my mind was sweetly centered and contrited on my return,
I hope I do not presume too far in believing that I did not offend Him,
whom I desire to love above all.

21st. A refreshing time this afternoon in my chamber;
in which I was led to view the excellency of truth and its peaceable fruits.

24th. Gave way today to anger, about a trifle in itself; as I have several times of late;
yet was thankful to feel myself corrected.
O, for more sweetness of disposition,
and strength of mind to bear the cross occurrences of life.
This I often labour after; and sometimes, when I keep on the watch,
am enabled to bear trials of patience without quitting my quiet habitation: would +++[+++that]
I could always dwell there!

26th. Much affected with the sorrowful tidings that
Job Scott had taken the small-pox in Ireland;
and it is supposed that he is by this time removed.
He was a valiant in Israel; one whose bow abode in strength.
I cannot but mourn the church`'s loss, and his dear children`'s, though unknown to me:
yet we must not call in question the dispensations of Providence, though,
to us finite creatures, they may be past finding out.

=== Twelfth Month, 1793.

6th. Oh, the crucifying power of Jesus, how hard to flesh and blood!
But remember, O, my soul, that is the part which can never inherit the kingdom.
Yet I can truly say, with a servant of the Lord formerly (to wit, Mary Peisley),
that so frequent and necessary are the operations of the sword of the Spirit,
to separate betwixt the precious and the vile,
that at times it makes me weary of this embodied state.
The Lord alone knows my secret probations; no mortal is acquainted therewith:
and it is he alone that can sustain through every conflict and give victory.
Praised be his name! a degree of living faith at this time arises,
that as I keep my eye single to him, he will be near,
and preserve me from the fury of the devourer.

10th. My mind sweetly refreshed, and animated to press forward,
by reading an account of dear Job Scott`'s triumphant exit.

15th. A precious season at meeting this morning.
Was led to believe that the work of the new creation was carrying on,
even new heavens and new earth; and that the old were passing away.
O,
that this glorious work may be perfected to the praise
of Him who alone is able to perform it.

20th. Stayed from meeting today to nurse my little niece,
who lies ill with the scarlet fever and sore throat:
and though I am very apt to take disorders of this kind, yet +++[+++I]
feel easy and quiet about it; having, I hope, my trust in the Lord;
who can sustain through every dispensation which he is pleased
to allot to the workmanship of his hands.
Can I doubt Him who hath so abundantly blessed and sustained to this very hour?
Oh, no!
I feel my confidence renewed; for which I bless his holy name.
