== Chapter 4

=== First Month, 1794.

3rd. Attended our monthly meeting today.
Though held in silence, the meeting for worship was, to my poor thirsty soul,
a season of consolation and refreshment: a favour I esteemed myself unworthy of.
A committee from the quarterly meeting attended this meeting.
The appointment of overseers took place.
O, that the importance of such an appointment may dwell weightily on my mind.

5th. Though the good Shepherd of Israel was near today,
both in our morning and afternoon meetings, yet I found the enemy also present,
endeavouring to draw my mind from its proper centre,
spreading alluring pictures to catch its attention; and he too much prevailed;
under a sense of which I was humbled,
and prayed that I might be enabled to maintain the warfare.

11th. A day for the greater part spent profitably; yet was desirous, in the evening,
that I might attribute nothing to the creature;
for if I was enabled to do any thing aright, the sufficiency was of God.
O, my soul, be willing to be stripped of every filthy rag of thy own righteousness,
that thou mayest be like the king`'s daughter, "`all glorious within.`"

13th. Our quarterly meeting at Kingston;
Samuel Emlen and James Graham appeared in testimony;
the latter inviting the backsliders to return to their first love.
I was humbled under a sense of the continued kindness of a long-suffering God,
in thus sending his faithful servants amongst us.
In the meeting for discipline an appointment of women friends took place,
to join a committee of men friends to visit the monthly meetings; when,
in compliance with my friends wishes, and from a fear of discouraging others,
I was prevailed with to set down my name; yet, alas!
I feel very unequal to such an undertaking; and expect, if I do go, to go as a fool.
O, that I may be preserved in simplicity, and singleness of heart;
that self may be laid low; that so I may move in the fear of the Lord.

20th. Took leave of my dear friends and returned homewards:
found my dear parents and sister well;
and some relations who had been visited with sickness, on the recovery;
so that I have renewed cause of thankfulness:
yea! what hour of my life does not afford it?

25th. A time of sweet solace in my chamber; so that my soul had to acknowledge,
Good is the Lord, and worthy to be praised; and that by the whole house of Israel.

28th. Went to the week-day meeting at Guildford.
Here was painfully brought to my remembrance my having spoken enviously of a person;
and with confusion of face was I humbled before the Lord, beseeching forgiveness,
and that he would be pleased to enable me to walk more perfectly before him in future.
O, may my sins ever go before-hand to judgment.
Being at this time made willing to come under his purifying hand,
I was favoured with the return of sweet peace.

31st. The parable of the publican and pharisee was
brought to my remembrance this morning at meeting;
and the prayer of my heart was,
that the pharisaical disposition might never be entertained by me: pour creature as I am,
much more need have I to exclaim with the publican, "`God be merciful to me a sinner.`"

=== Second Month, 1794.

2nd. Felt the overshadowing of heavenly love,
soon after I sat down in meeting this morning; yet, through unwatchfulness,
suffered my mind to be scattered; +++[+++I]
recovered in some degree my strength before the meeting concluded, but not wholly.
Read this afternoon an excellent little book written by George Keith.
"`What need have they, who think they stand,
to take heed lest they fall;`" since one who made so good a beginning,
and even suffered imprisonment for the testimony, did grievously fall.

3rd. Much of my time devoted to the service of others.

5th. A quiet tranquil day, both to body and mind.

10th. Confined with a sore throat and fever these several days past: +++[+++I]
had the disorder very favourably; for which have been humbly thankful:
yet have been uncommonly tried with poverty of spirit; yea,
I sought him whom my soul loveth; I sought him on my bed, but found him not.

12th. Pretty much spent in profitable reading:
fresh desires arose after a more perfect establishment on the Rock of ages,
against which neither death, hell, nor the grave shall ever prevail.

20th. Mostly devoted to the poor and sick; so that I hope it has been well spent:
yet am fully sensible there is nothing due to the creature.

23rd. Favoured with the fresh descendings of heavenly rain at meeting this morning.
O my soul, let not the recording of the Lord`'s mercies satisfy thee,
but let it incite thee to a more earnest pursuit after heavenly treasure:
that so increasing faithfulness may appear.

26th. So much taken up with visiting, and divers other engagements,
that I could find scarcely any time for retirement.
How tasteless and insipid is every enjoyment, that is not crowned with thy presence,
O Lord!--I am thankful to feel it so.

=== Third Month, 1794.

1st. Wrote a letter of advice to a friend;
in doing which I have discharged an apprehended duty:
the rest of the day much taken up in serving others.

2nd. On my first sitting down at meeting, +++[+++I]
got musing on a subject, which, though a profitable one, was beside the proper business:
yet no sooner did I endeavour to dismiss it, and get on my watch,
than I met with Him whom my soul loveth,
graciously waiting to bless the workmanship of his hand.
May he be pleased to instruct me how to make suitable returns.

3rd. Doubts and fears have been the companions of my mind today,
about sending the letter which I had written; so +++[+++I]
concluded to wait, and try it longer;
have also been afraid of spreading too much into branches,
and not dwelling enough in the root.
O, may this jealously increase.
Under the pressure of these feelings I have poured out my soul before the Lord,
beseeching him to preserve me on the right hand and on the left.

8th. Ventured with fear to send the letter I had written; so must leave the event.

23rd. Much discouraged at the prospect of the approaching visit to the monthly meetings;
and the more so as my companion Sarah Birkbeck is likely to be prevented, by illness,
from going with me.
This is no small trial of my faith.
O, that it were as a grain of mustard seed, pure and unmixed;
then doubtless it would lessen, if not remove, this mountain.
Had a visit from a kind sympathizing friend: and dear Elizabeth Moline,
seeing my extreme weakness, voluntarily offered to accompany me.
Oh, what a poor creature am I, how unworthy +++[+++of]
such unmerited favour!
Awoke in the night, and felt my mind sweetly bounded by the fear of the Lord;
yet methought something like a gentle reproof for giving way so much to my fears.

26th. Went to Dorking to join the committee.
I hope our going was not altogether in vain.

30th. A refreshing season at meeting this morning, though not unattended with labour:
the afternoon was the preparative meeting.
Some weighty counsel dropt; yet I thought the queries answered too fully.
In the evening +++[+++I]
spoke detractingly of an absent person; to my shame I mention it.
O my soul, when wilt thou learn wisdom?

31st. Low, and I trust humble, under a sense of my failing yesterday;
with renewed desires after more stability.

=== Fourth Month, 1794.

11th. A renewal of strength at our silent Weekday meeting.
How do I love these seasons!

15th. Company, etc. again today: something is certainly due to our friends;
yet I should gladly have retired awhile to feel after
that meat which the world knows not of.

16th. Renewed desires after divine preservation;
yet but little time for religious retirement.
Am thankful to feel, when this is sometimes the case,
the limiting power of truth near me; preserving me in a watchful frame of mind.

17th. It was opened to my understanding, in my silent sitting,
how offensive a lukewarm state is in the sight of God; and the prayer of my heart was,
that I might be preserved from it, and I was led a little to number my blessings.

18th. Renewed encouragement to follow the Lord in the way of his leadings,
at our week-day meeting.
What a loss do those sustain who miss these opportunities!

20th. Beset with vain thoughts, to which I too much yielded; so that,
when I went to meeting, I thought myself unworthy to approach Perfect Purity:
yet such was his gracious condescension, that he stretched forth his sceptre,
and drew me near to him; and blessed me with his life-giving presence.
Unmerited mercy!

24th. Was truly desirous that the work (which I believe the Lord
hath graciously begun in my heart) might not be marred on the wheel;
but there is surely no safety but in unceasing watchfulness.

=== Fifth Month, 1794.

3rd. This morning rose early; and spent some hours in my chamber,
profitably and pleasantly, in reading, writing, and communing with my own heart:
favoured with the fresh descendings of heavenly rain.
Precious privilege, and delightful employment!
O, that the votaries of pleasure could but taste these refined and superior enjoyments;
surely,
they would be willing to part with their perishable and
sin-pleasing gratifications for this pearl of great price.

14th. Sat up part of last night with my beloved parent;
and my feelings much tried with an apprehension of his disorder settling in childishness.
I have endeavoured to labour after an entire resignation to the divine will,
under this trying allotment; and though I cannot say I have attained to it perfectly,
yet methinks I feel the sustaining arm of divine power underneath,
as an anchor to my wearied soul.
May I be thankful enough.

15th. My dear father something better today,
having in a great measure recovered the use of his faculties.
O, may I be thankful enough; but it is the Lord alone who can enable me so to be.

16th. My dear father gradually recovering; so +++[+++I]
ventured to meeting today,
where my poor exhausted mind was led as into fresh and green pastures.
What can I render unto the Lord for all his blessings?

26th. A sweet contriting season in my chamber.

30th. Though I travelled for awhile as in a wilderness; yet at length +++[+++I]
was favoured with the springing up of the well of life,
to my great refreshment this morning at meeting.

=== Sixth Month, 1794.

3rd. Felt sweetly peaceful when I awoke this morning;
methought the good Shepherd was near; notwithstanding which favour +++[+++I]
was too unguarded in my conversation in the evening: to my shame I record it.

5th. Went to Guildford to meet Phebe Blakes and Elizabeth Copeland,
two friends travelling in the work of the ministry: +++[+++I]
was made renewedly sensible of my own insufficiency for every good work.

6th. The above mentioned friends +++[+++were]
at our monthly meeting today: Phebe Blakes led in a close line; yet +++[+++I]
believe was much favoured: as for poor me, to struggle with my own weakness,
seemed all I could attain to: perhaps my mind was too outward; yet +++[+++I]
endeavoured to set a double watch on that hand.

7th. Have been desirous this morning of arising and
shaking myself from the dust of the earth:
for surely we are often clogged with it in our passing along.
How does it retard our progress Zionward!

10th. My close attention to my dear father these several days,
with other family engagements, have left me but little leisure for retirement; yet +++[+++I]
trust I have endeavoured to keep near my good guide,
who hath graciously stayed my mind under some inquietudes which have occurred.

12th. Our dear friends Mary Ridgway and Jane Watson came;
an unpleasant evening owing to an illumination: the people very noisy and riotous.
Was favoured with much quietness and calmness on the occasion,
though they broke many of our windows.

13th. Our week-day meeting, which the aforesaid friends attended,
and a precious season it proved to my mind, and I hope to many others:
Mary and Jane appeared excellently, especially dear Mary,
who laboured in much gospel love amongst us,
inviting those who stood idle in the market-place,
to enter into the vineyard of their own hearts and work.

15th. Went to Guildford to meet our dear friends Mary Ridgway and Jane Watson,
yet felt rather uneasy in leaving our own meeting, which brought me into deep contrition.
O, may I ever cherish this religious sensibility.
The Lord was pleased in great condescension to visit me in my low estate,
reviving my faith and hope in him.
Dear Mary and Jane appeared excellently, though in a close line.
Returned to our evening meeting, which also proved a season of refreshment.

18th. I accompanied my dear father to Alton,
where we again met with our dear friends Mary Ridgway and Jane Watson.

19th. Was at a meeting appointed for the aforesaid friends:
I sat down in much weakness and emptiness; yet being enabled to maintain the warfare,
truth arose into dominion in my heart before silence was broken.
Before we parted +++[+++we]
were favoured with a sweet cementing opportunity,
in which dear Mary appeared in testimony,
and heart-tendering supplication that the Lord would be
pleased to be with them in the way they should go,
and also with us that stayed behind;
and that we might be as epistles written in each other`'s hearts.

21st. Came home, had a pleasant safe journey; renewed cause of thankfulness.

25th. My dear father not quite so well: my fears +++[+++were]
much alarmed; yet +++[+++I]
endeavoured to keep quiet, and near that Rock, which alone supports under every trial.

27th. My beloved father feeling himself poorly, +++[+++he]
concluded not to go to meeting; but afterwards went, and I with him: though late,
it proved a season of divine refreshment; silent as to words.

30th. Tried with the heat of the weather:
yet several times in the day felt the attractive influence of divine love;
so that I trust I am not forsaken.
Encouraging belief!

=== Seventh Month 1794.

1st. Some trials of patience occurred;
which I did not bear with that meekness I might have done: O,
for an increase of it as well as of every other virtue;
surely I stand much in need of it,
and it is often the engagement of my mind to press after it.

6th. Set off at half past four o`'clock for our quarterly meeting;
got there but a little before meeting, had not time sufficient to refresh ourselves,
and the weather +++[+++was]
extremely hot,
so that it was no easy matter to get my mind sufficiently abstracted from outward things:
yet +++[+++I]
was not wholly forsaken by the Shepherd of Israel,
who is still watching over his little ones with a fatherly kindness; +++[+++we]
were favoured with the company of several valuable friends.

7th. A precious season today to my poor soul:
in which my strength and confidence in the Lord was renewed:
notwithstanding the extreme heat of the weather and smallness of the meetinghouse.
Dear Thomas Scattergood attended with many other valuable friends:
I was enabled to get through the business to my humble admiration,
yet trust the praise was rendered where it was alone due,
well knowing from whence ability was received.
Set out for home in the evening, which we did not reach till midnight.

13th. Though I sat down much emptied of all good this morning at meeting,
yet was the Lord graciously pleased as formerly to fill the empty vessel.
The evening meeting poorly attended, and alas! but too few of the few, I fear,
spiritually awake, so as to unite in labour for the arising of life.

15th. Feeling the bubblings up of the wellspring of life this evening,
I retired into the garden, where I was enabled to sing unto it: inestimable favour!

=== Ninth Month, 1794:

27th. Have been confined eight weeks this day with a nervous fever;
seven of which to my chamber, and mostly, to my bed.
The forepart of my illness was tried with poverty of spirit;
my mind seeming to partake of the weakness of my body,
so that I had scarcely strength to look towards the Lord`'s holy habitation.
Yet I have reason to believe he was not unmindful of me;
for one night when I could not sleep from extreme restlessness, and feeling,
as I apprehended, the disorder increasing on me,
I felt more than common anxiety as to the event: desiring if the solemn change was near,
I might have an evidence of it.
In that trying season, it was graciously intimated that, however my sickness terminated,
it would be well with me.
I write not this boastingly; but +++[+++I]
then, as well as now,
was deeply humbled under a sense of my own unworthiness of so great a favour.
Yet it was an anchor to my soul, not only at that time,
but during the rest of my illness, forbidding every anxious thought,
and increasing my faith and confidence in His holy name,
who is forever worthy to be feared and praised.
And now he hath been graciously pleased to restore in some degree my health and strength,
which increases daily; may I be enabled, through his holy assistance,
to live to his honour, who hath thus poured unnumbered blessings on my head:
yet I am often led to feel, and at times to mourn,
my lukewarmness and my proneness to enter too much into the spirit of this world;
so that I see our blessed Lord`'s injunction, to watch and pray,
was never more necessary than at the present time.

=== Tenth Month, 1794.

6th. (Alton) Several days have again elapsed without any remark,
partly owing to indisposition, partly to want of suitable opportunity.
I have still, at times, to lament my lukewarmness,
at others have been favoured with the fresh descendings of heavenly rain,
to the great refreshment of my weary mind.
O, that increasing fruitfulness may appear.
During this time my dear aunt Townsend departed this life, at Edinburgh,
where she was on a religious visit.

13th. This day my beloved father was seized with an apoplectic fit;
under which severe trial I was supported beyond expectation: and through divine favour,
before night, he was so far recovered as to speak.

14th. My dear father much better.
Thomas Scattergood paid a religious visit to our family;
which was a strengthening opportunity to my poor weak mind;
what abundant cause of thankfulness does each day afford!

16th. Have been humbled today under an apprehension that
my gratitude for past favours has not been enough lively,
and that I have been too much off my watch today.

31st. Favoured with near access to the throne of
grace this morning in our silent gathering at meeting;
and comforted in the renewed belief, that the glory is not yet departed from our Israel.

=== Eleventh Month, 1794.

2nd. Sat down at meeting this morning in much poverty and weakness;
yet He who was pleased formerly to fill the empty vessels,
and remains to be the joy and song of many generations,
also graciously condescended to make my cup to overflow.

7th. A humbling season at meeting this morning; yet +++[+++I]
think I hurried over the business too fast; and divers friends calling in,
my mind too much dissipated,
so that on a review of this day I feel much dissatisfied with myself.

13th. Though a sense of some weaknesses attended me in these last two days, yet +++[+++I]
think they have not been spent vainly or wholly unimproved.

16th. I did not eat the bread of idleness this morning at meeting;
though have no doubt but my labour was increased
by my unwatchfulness at first sitting down,
suffering my mind to wander hither and thither;
so that I could not easily get it centred; yet the Lord was not unmindful of me.

24th. This day spent mostly in the service of the poor.
I mention this not as any thing meritorious,
being well convinced how imperfectly I perform my duties, both religious and social.

28th. Favoured with the fresh descendings of celestial rain,
in our little silent gathering this morning.

=== Twelfth Month, 1794.

3rd. "`Let him that thinketh he standeth take heed lest
he fall;`" never was this advice more necessary to me,
than at this juncture;
who but yesterday was comforted in the belief that
through the assistance of divine grace,
I was gaining some ascendency over the adversary of our souls`' happiness,
not only in a more circumspect walking, but in watching over my mind,
naturally prone to a roving disposition.
But alas! +++[+++I]
am renewedly convinced, that the warfare is not completed.

5th. Dwelt much in the valley; yet methought the dew rested on my humble habitation.

9th. These two days much occupied with company, waiting on my dear father,
attending my girls,
etc. so as to leave but little time for religious retirement.

12th. Stayed at home from meeting with my dear father; and the Lord,
who is not confined to place or space,
broke in upon my soul with his life-giving presence, to my great comfort and refreshment.
Forever praised be his excellent name, who is alone worthy.

15th. Fresh cause to moan my instability.
O my soul, when wilt thou learn wisdom?

16th. Peaceful and quiet.

19th. My dear father seized with another apoplectic fit;
but not so violent as the former, nor of so long duration.
I was favoured to feel calm under this trying dispensation.

20th. Sat up with my dear father last night; in which season my mind enjoyed sweet solace.

22nd. My beloved father favoured with a good night; awoke refreshed this morning,
and his faculties much restored.
O, that I may thankful enough for this renewed favour.

24th. My beloved father very low this evening;
fearing the work had not kept pace with the day: my mind +++[+++was]
sweetly contrited before the Father of Mercies,
and encouraged in the belief that he would find acceptance.

28th. Measurably owned by Him (who is the crown of all our religious assemblies),
both in our morning and afternoon meeting; but got off my watch too soon in the latter.

31st. And now I am come to the close of another year.
What progress, O my soul, hast thou made in the heavenly race?
What increase of spiritual strength?
I fear not much;
yet am thankful in believing I am preserved in a good degree of spiritual health:
and thus much can I say on behalf of a merciful Creator, that hitherto,
notwithstanding my manifold weaknesses, he hath helped me.
