== Chapter 6

=== First Month, 1796.

6th. These two days well spent as to action; but my mind in too lukewarm a state.

7th. Took a solitary walk in the field, where the mildness of the season,
and the beauty of the creation gilded by the rays
of the setting sun (notwithstanding it was mid-winter),
awakened my soul to gratitude in contemplating the
various blessings bestowed on poor fallen man,
by the bounteous Author of all good; who is so little seen and acknowledged in his works.
And though contemplating his perfections made me feel my own nothingness,
yet there is something so inexpressibly sweet in this humble
state of mind (and the tears which accompanied it),
that I am often led to covet it in preference to any other; for it is not at our command.

8th. Was desirous this morning, as is frequently my concern,
to be weighed in the balance of the sanctuary,
that so I might be favoured to see my various deficiencies, and improve the future;
that at the solemn close I may not be found wanting.

10th. In my silent waiting before the Lord this morning at meeting,
I was comforted in the belief that notwithstanding my various weaknesses,
love to him and his cause, had the preeminence above every worldly consideration.

15th. I believe there were a few gathered in the name of Jesus today at meeting,
who were favoured to feel him preside amongst them.
How much to be lamented that any should miss so great a
privilege for want of centring to the pure gift in themselves!

17th. The morning not spent profitably; and, having company to dinner,
my mind was so dissipated that when I sat down in
meeting I found it hard work to get it stayed.
Mourning and self-abasement were my portion;
in which humbled state I was favoured to feel the healing waters flow,
to my great consolation and encouragement.
An unmerited mercy!

20th. On recounting the varied blessings I enjoy (this morning), the query revived,
What lackest thou yet?
The grateful acknowledgment of my heart was, Nothing, Lord,
but a more perfect dedication to thee, and resignation of my will:
in which I am fully satisfied our peace and safety consist.

22nd. My dear father sleeping while the family were at meeting,
I had a comfortable time in retirement in his chamber.

24th. Had a lukewarm spirit to combat with the forepart of the meeting;
but after wrestling a while +++[+++I]
was enabled to flee to Him, whose name is a strong tower.

29th. Have been much indisposed this week, and my dear father very restless;
yet my faith and strength +++[+++were]
a little renewed this morning at meeting, which I esteem a favour.

=== Second Month, 1796.

2nd. Attended our monthly meeting, which proved a sweet instructive season,
though held in silence.

6th. My dear father had another alarming seizure this evening, under which trial +++[+++I]
was favoured to feel divine support.

11th. Came to Wanborough, in order to recruit a little my health;
having suffered by long confinement and close attention to my beloved father.

15th. On reviewing the last few days +++[+++I]
find nothing to boast of, but my many infirmities both of body and mind;
my feelings having been uncommonly trying.

20th. Have spent the last few days pleasantly in the society of my kind friends,
and feel myself better: cause of thankfulness!

23rd. A small company of us today at meeting; but +++[+++I]
was renewedly convinced of the truth of that declaration,
"`Where two or three are gathered together in my name, there am I in the midst of them.`"

28th. Was favoured this morning, in our silent meeting,
to sit under the teachings of the great Minister of the sanctuary,
who is verifying his promise of teaching his people himself.
Gracious condescension!

=== Third Month, 1796.

6th. My dear father visited with another attack.
That the afflictions which surround us, and are doubtless allotted in infinite wisdom,
may all work together for good; and patience have its perfect work,
is the sincere prayer of my heart.

11th. Was in hopes while the family were at meeting
to have communed with my own heart and been still;
but was so much indisposed, that I could not get my mind centred.
Poor creature as I am!

13th. Not wishing to eat the bread of idleness,
I laboured according to my measure this morning at meeting,
and my hungry soul was satisfied with the presence of him, who is invincible.
In the afternoon +++[+++I]
was beset with roving thoughts to which I too much yielded.

17th. A sweet solitary walk in the field this evening,
rendered so by feeling something of the divine unction resting upon my mind.

18th. Sat at meeting this morning in a good degree of holy silence,
where secret instruction was conveyed to my hungry soul, to my humble admiration.

26th. This week hath been so fully taken up with company,
etc. as to leave me but little leisure, yet +++[+++I]
trust the better part has not been wholly neglected.

27th. On a review of this day, +++[+++I]
do not feel satisfied with myself,
though favoured with a degree of divine enjoyment in both our meetings, yet +++[+++I]
did not keep steadfastly on the watch.

=== Fourth Month, 1796.

1st. A precious baptizing season in our little week-day meeting,
may I walk worthy of such unmerited favours.

3rd. Found it hard work to get my poor weak mind to any degree of settlement,
so that on looking over the day +++[+++I]
find that nothing was due to the creature, but blushing and confusion of face.

4th. At meeting this morning my mind was favoured to renew its strength,
and enabled beyond expectation to get through the business,
I hope to tolerable satisfaction.
No praise due to the creature, well knowing from whence my sufficiency cometh!

8th. An humbling sense of my manifold infirmities is the companion of my mind this day.
How unable we are to preserve ourselves one moment!
Surely then there is need to watch unto prayer.

12th. I often feel the imperfections of my nature so forcibly,
that the enemy is ready to suggest that it is in vain to maintain the warfare;
but I remember he was a liar from the beginning,
and that he is still seeking whom to betray.
The good Shepherd, whose mercy is over all his works,
still graciously extends it to me (the meanest of them I am at times ready to conclude),
and animates my faith to press forward,
through the many encumbering things that retard my progress Zionward.
What return can I make for all his benefits?
O, that he may be pleased to enable me to make straight steps to my feet,
for he well knows my inability to take one aright without his assistance.

21st. My dear father much worse for a week past; and having company almost daily,
my time has been much engrossed; yet +++[+++I]
think it has not been spent vainly.

22nd. Found a little leisure this morning while the family were at meeting,
and my dear father asleep, to retire to the Fountain of all good:
when my mind was mercifully replenished with the sweet influences of divine regard.

29th. An humbling season this morning at meeting to my poor, very poor mind.

=== Fifth Month, 1796.

2nd. A thoroughly busy day.
How often do I turn disgusted from the world, meeting with insincerity!
May it have its proper effect and wean me from it,
and induce me to press with more earnestness after a city which hath foundations.

4th. Sweetly and profitably spent!
My mind being preserved in a watchful state, +++[+++I]
was favoured to feel the good hand near.

8th. My beloved father gradually drawing towards the solemn close.
In this time of trial +++[+++I]
am thankful to feel my mind preserved in awful quiet.

9th. This day at half past four in the afternoon, the solemn scene closed;
and the spirit of my beloved father forsook its afflicted tabernacle; and is,
I doubt not, become an inhabitant of that city where sighing and sorrow cease.
Blessed exchange! How consoling is the prospect!
This belief sustained my mind amid the pangs of separation;
but hearing in the evening the weak state my dear sister was in,
it increased the tide of grief so much, that my feeble nature seemed almost overwhelmed.

13th. Graciously permitted access to the healing fountain this evening,
from whence I was sweetly refreshed.

14th. Several of our relations and friends came in
order to attend the funeral of my beloved father.
After supper George Dillwyn appeared in an encouraging testimony,
informing us of the sweet persuasion he entertained
that he was landed safe in the heavenly mansions,
exhorting those present so to keep their eye to the divine compass,
that in the end we may all arrive at the same port.

15th. Took an affecting leave of the remains of my beloved father,
whose placid countenance looked sweet even in death.
It was followed to the grave by a large number of relations, friends, and acquaintance.
The forepart of the meeting I thought uncommonly solemn,
considering the mixed company it was composed of.
The silence which prevailed was remarkable;
yet my poor mind was much deserted till towards the conclusion;
and at the grave the healing balm was dispensed to my humble admiration and thankfulness.
After dinner our dear friends left us,
parting under a solemn covering in sweet fellowship,
my mind being deeply bowed under a sense of the manifold favours conferred on us.

18th. These several days spent in quiet; I believe the good Shepherd hath been near.
I have felt something of the extension of his divine crook both in my uprisings,
and lyings-down.
O, that I was more worthy of such continued condescension.

20th. Our week-day meeting, a season I longed for; yet on my sitting down +++[+++I]
felt encompassed with poverty; but after a patient waiting,
the stone was graciously rolled away from the well`'s mouth, and as +++[+++the spring]
arose, I was enabled to sing unto it.
I write not these things boastingly:
but as memorials of the lovingkindness of the Lord to such an unworthy creature.

31st. Went to Guildford to our monthly meeting, where, after a time of drought,
my soul was sweetly refreshed, as by a brook by the way.

=== Sixth Month, 1796.

5th. The forepart of the meeting sat in dryness, but having my eye single to the Lord,
he was graciously pleased to make the desert rejoice and blossom as the rose,
by his life-giving presence.
The afternoon +++[+++was]
a dull heavy meeting.

12th. Though not favoured with so sensible an enjoyment
of the divine presence as at some other seasons;
yet +++[+++I]
was preserved in a quiet frame of mind, and in a good degree of watchfulness:
in which I believe I was accepted.

18th. Though I have had but little leisure for retirement this week past, yet +++[+++I]
have been favoured to feel good near me at times.

19th. Seasons of renewed favour, both +++[+++the]
morning and afternoon meetings;
in the former something of the vision of the holy waters was opened to my understanding.

22nd. Feel low and poor every way.

26th. Methought the spring lay low, requiring deep labour to get at it;
which however was blessed, being favoured with a little of its arising.

=== Seventh Month, 1796.

3rd. Thomas Scattergood, with other friends,
attended our quarterly meeting today +++[+++at Wandsworth],
which was a deeply baptizing season, not soon to be forgotten by some present.
Oh, the long-suffering of a merciful God,
who is still extending his visitation to a backsliding generation!
How was my soul bowed under a sense of it!

4th. The divine sweetness which attended my mind,
soon after my sitting down today at meeting, I thought was worth coming so far for;
had I been favoured with no other enjoyment;
and the prayer of my heart was that I might be preserved under its precious influence,
during the sittings of the meetings both for worship and discipline;
which was in good measure the case.

5th. Came to town in the evening, called on George Dillwyn to take leave of him,
before his embarkation for Germany.
We had a sweetly contriting season together, and parted, I trust,
under the influence of best love; not knowing we should ever meet again in mutability.

6th. +++[+++Went]
to Chelmsford in the afternoon,
desirous to retain a grateful sense of the favours I have been made a partaker of.

10th. Was very desirous that the great work of redemption might
be carried on to the praise of Him who is able to effect it.

18th. Went to the monthly meeting at Colchester; which appeared, like many others,
in a weak low state; yet +++[+++I]
was favoured with a quiet refreshing season in the meeting for worship.

22nd. Went this evening to Stortford,
to attend a public meeting appointed for Thomas Scattergood,
the silent part of which was a season of sweet solace to my mind; yea,
it seemed for a short space, as though it was swallowed up in the divine immensity;
and +++[+++I]
was, like Peter formerly, desirous of tabernacling there,
unwilling to return again to earth and earthly things, to a state of warfare.

23rd. Thomas Scattergood came to Stansted, I had some of his company,
but was so unwell I could not enjoy it as I should otherwise have done.
I began to consider the enjoyment I had been favoured with the evening before,
as a prelude to a severe illness, or my final change,
under which I was favoured with a quiet resignation.

24th. Feel much better than I had reason to expect from the violence of the seizure.
May I be sufficiently thankful.

28th. Thomas Scattergood (with George and Elizabeth
Gibson) came again to Stansted this morning,
and had a public meeting with the neighbours,
and was favoured in a more eminent manner than I had before heard him.
How did the bowels of divine compassion seem to yearn towards the people!
The gospel was truly preached to the poor in spirit; but Oh!
I found it was to many only like a pleasant song.
How discouraging this must be to the poor exercised messengers;
who are thus evidently sent to the highways and hedges with an invitation to the marriage-feast.
I think I sat amongst them in humility and fear,
desirous that if I was not in any degree able to assist
these favoured instruments by the exercise of my spirit,
as I concluded I was not, that I might not add to their burden by unwatchfulness.
Spent the rest of the day in sweet society.

=== Eighth Month, 1796.

6th. Came home, and found all relations generally well, which,
with the many other favours bestowed on me, I desire to live under a grateful sense of,
and improve to my eternal advantage.

11th. On a retrospection of the last few days; +++[+++I]
think they have not been spent altogether unprofitably; yet +++[+++I]
have sometimes given way, as usual, too much to a roving disposition; at others +++[+++I]
have felt the restricting power of truth near, sweetly bounding my thoughts and desires.

12th. Was enabled this morning at meeting, through adorable mercy,
after a time of labour,
to offer up the sacrifice of thanksgiving for mercies both ancient and new.

18th. Afresh humbled under a sense of my weaknesses;
and sincere desires arose for preservation and renewed
strength to walk uprightly before the God of my life.

23rd. Having a word of reproof to hand to a delinquent, it induced me to turn inward,
and see how things stood there, which humbled and contrited my spirit before the Lord,
desiring him to search out everything offensive in his pure sight:
being afresh convinced that the work belongs to him,
for without him we can indeed do nothing.

31st. Feeling some wrong dispositions arising, +++[+++I]
found it safest to recur to the Fountain of living mercies for strength to subdue them,
and to implore the continuance of his protecting providence.

=== Ninth Month, 1796.

14th. These several days pretty much taken up with company, and preparing for a journey,
and my mind too much occupied with trifles.

16th. A temptation presented on my first sitting down at meeting,
which my weak mind was too much inclined to join in with; but happily seeing the snare,
I was enabled to flee to Him, whose name is a strong tower,
who graciously condescended to bless my feeble endeavours,
and give ability to mount a little upward, and render him the praise of his own work,
who is forever worthy thereof.

25th. After some exercise,
my mind was gathered in a good degree into the silence of all flesh;
where the Father was, I humbly trust, worshipped in spirit and in truth.

=== Tenth Month, 1796.

6th. Had humbling views of myself today at meeting; yet, if I know my own heart,
I love these stripping seasons, love to see self laid low, and of no reputation at all,
that the Lord may be alone exalted, who is worthy thereof forever.

8th. Have felt something of an unusual sadness this day or two past,
which hath caused some searching of heart.
O, that it abode more fully under divine influence, that its goings might be established.

12th. Sitting down in a good degree of humility and nothingness,
my vessel was replenished with heavenly oil, which greatly cheered my drooping mind,
and encouraged me to hold on my way.

16th. Though I went to meeting in much poverty, and beset with unprofitable thoughts,
yet +++[+++I]
was soon favoured to feel an awful solemnity cover my mind, under which +++[+++I]
was preserved the greater part of the meeting.

23rd. Think I did not eat the bread of idleness today at meeting,
having to struggle with my manifold weaknesses:
yet am thankful at times to feel the warfare maintained.

26th. Reached Bristol late this evening after a fatiguing journey.

=== Eleventh Month, 1796.

3rd. Dear Sarah and Hannah Stephenson called on us,
and we had a comfortable sitting together in my dear sister`'s chamber.
Sarah was led in an encouraging manner,
and had to mention the blessing which rested on the head of Joseph,
desiring it might be ours.

6th. Was enabled to break through a host as it were,
and drink a little of the water that is +++[+++by]
the gate of Bethlehem; for which unmerited favour my soul praised the Lord,
who is alone worthy forever.

10th. At the evening meeting, my poor soul +++[+++was]
much encompassed with weakness and infirmity;
but waiting patiently and humbly at Wisdom`'s gate, the clouds were at length dispersed,
and the Lord, in his great goodness,
blessed me with the lifting up of the light of his glorious countenance.

15th. A time of poverty and desertion this morning at meeting;
so that my poor soul was led to crave the crumbs that fall from the table,
like the poor Gentile formerly, if unworthy to partake as a child of the heavenly family.

25th. Having omitted to minute down the several last days for want of +++[+++a]
suitable opportunity, I do not recollect particulars; but this I know,
that I never had more humbling views of myself than of late;
and strong desires have been raised at times,
that I might be enabled to walk more faithfully in
the path of self-denial and the daily cross.

28th. Called on several friends, intending to leave Bristol in a day or two,
and spent about an hour profitably and pleasantly
with dear Hannah Stephenson and her aged mother.

=== Twelfth Month, 1796.

8th. These last few days spent pleasantly in the society of beloved relations;
and would hope not altogether unprofitably.
My brother and sister Waring left us,^
footnote:[It should seem that her brother and sister returned with her from Bristol.]
my dear mother and self, now sitting down together in our quiet habitation, thankful,
I trust, for the many favours we are made partakers of.

15th. These last few days spent well as to action, as far as I know; but +++[+++I]
have given too much latitude to my roving mind.

16th. A time of great desertion and poverty this morning at meeting; which, I trust,
profitably humbled my poor mind.

25th. A trying time this morning at meeting.
It seemed as if the severity of the weather had chilled all hearts.
Mine was too lukewarm, I fear:
under an humbling sense of which I went to the afternoon meeting,
which unexpectedly proved a sweet, contriting season.

28th. Part of this week hath been much taken up in endeavouring
to establish a fund for the relief of poor women in child-bed;
and hitherto have met with encouragement and success, beyond expectation.
It hath been humbling to my poor mind, that my feeble endeavours should be blessed,
and that so mean an instrument should find favour with the people;
which I considered the Lord`'s doing,
and have earnestly desired that I might not attribute any thing to the creature;
but might be preserved from this snare, well knowing that I can do nothing aright,
without the assistance of that wisdom, which is alone profitable to direct.
