== Chapter 7

=== First Month, 1797.

1st. I was enabled this morning at meeting to cast
down every crown as at the footstool of Jesus.
The afternoon was a season of poverty: owing, I fear, to lukewarmness.
Poor unstable creature!

5th. This week, like the last,
has been mostly spent in the service of the institution
I have been endeavouring to promote;
and which has been successful beyond my most sanguine expectations.
It has been truly pleasant to see with what cheerfulness
most of the subscriptions have been given.
Yet even here I have found abundant cause of watchfulness.
Self, busy self, would fain put in for a share: which hath caused, I trust,
a godly jealousy, lest I should attribute any thing to the creature;
and a fear hath also prevailed, lest I should, in any respect,
balk my testimony in my frequent intercourse with the gentry;
which must necessarily occur in the establishment of such an institution;
but think I have hitherto been enabled to steer pretty clear (though
not without my buffetings) which is cause of humble thankfulness.

9th. Attended our quarterly meeting at Kingston, which was very small, and, I thought,
an affecting low season, the weakness of our situation being so apparent,
and yet no way seemed to open to mend it.
It seemed to me as if the few sincere-hearted amongst
us were not sufficient for these things.

15th. A season of encouragement this morning at meeting;
being favoured with a renewed evidence that I had an interest in Him,
who is the beloved of souls.
The afternoon, the little while I got my mind stayed, was humbling.

17th. This week hath mostly been devoted to the service of others,
and I would hope not spent unprofitably;
yet fears and doubts do at times so encompass my
poor mind that I am ready to fear I do nothing aright.

22nd. Times of proving again today, both morning and afternoon,
yet my mind a little relieved from the pressure it lay under.

25th. I have endeavoured to perform the duties of these several days past faithfully,
in lowliness and a good degree of fear.
That I may be preserved so to the end of time is my sincere desire.

27th. A time of sweet encouragement afforded me this morning at meeting,
so that my soul leaned, as it were, on its beloved.
Inestimable favour!

29th. My strength and faith in the Lord renewed,
so that I could put my trust under the shadow of his wings;
yet the close exercises of mind, which have of late attended,
have not yet wholly left me, nor do I wish it (I think) till the Lord`'s time,
which is ever the best.
Too unwatchful in the afternoon meeting.

=== Second Month, 1797.

3rd. Though I had to wrestle awhile for the blessing this morning at meeting, yet +++[+++I]
was not sent empty away: such is the continued kindness of a gracious Providence to,
I am often led to think, the meanest of his works.

5th. Again plunged into the deeps.
May these frequent baptisms tend to my purification;
and enable me to endure with patience and resignation
every dispensation of unerring wisdom;
until I am made conformable to his holy will in all things.

9th. Methought the language of the poor publican became me best this morning at meeting;
yet at times my mind has been a little cheered with the belief, that He,
whom I desire to serve, hath not only seen my lowly walking before him of late,
but that his blessing hath rested upon me;
though at other seasons I could not discern it.

19th. My thirsty soul replenished with a little of the wine of the kingdom this morning.
How unworthy +++[+++of]
such a favour I esteemed myself!

26th. The meeting I thought measurably owned by Him,
who is the crown of all our assemblies; and the prayer of my heart was,
that he would be pleased to enable me to walk before him with acceptance.
This is what at times I am led to aspire after more than any temporal blessing.

28th. I fear I have not so fully borne the cross as I should have done.

=== Third Month, 1797.

2nd. My mind more tranquil and comfortable; yet +++[+++I]
have daily to experience that weakness and infirmity are my companions.

3rd. Though I could only touch the hem of his garment today at meeting,
yet I found virtue in it;
and thought it an unspeakable favour that I should
be permitted to approach the Beloved of souls:
one so unworthy and so remote from his infinite perfection.

5th. A season of poverty in the morning meeting;
though I was enabled to keep pretty much on the watch.
In the afternoon, on my first sitting down, a temptation presented itself,
to which I too much yielded for a time; but the good Remembrancer being near,
soon brought me into the valley of deep contrition,
where I was favoured to experience reconciliation.

9th. My mind hath been much in the valley these last few days;
where I find it safest to keep.

10th. Was comforted today (at meeting) in the renewed belief,
notwithstanding the desolation which prevails,
that there are still a remnant who are preferring Jerusalem to their chief joy.

15th. Am still made to feel my weakness and insufficiency for every good work:
yet frequent are my desires to be directed by a wisdom superior to my own;
even that wisdom which comes from above,
and is alone profitable to direct through this state of probation.

19th. My mind felt this morning like the barren heath in the wilderness,
insensible when good comes; or, at least, not in a capacity of receiving it.
In the afternoon the searching wine was dispensed,
yet not wholly unaccompanied with consoling oil; to my humble admiration,
thinking myself unworthy +++[+++of]
such a favour.

24th. A precious baptizing season in our little week-day meeting,
in which my soul was enabled to sing of mercy and of judgment.

=== Fourth Month, 1797.

2nd. My mind gathered into a sweet quiet soon after I sat down in meeting, which,
in a good degree, remained during the sitting, notwithstanding some interruption.
The afternoon +++[+++was]
a painful season, +++[+++I]
wishing to feel life more than words.

3rd. Dear Sarah Stephenson +++[+++was]
much favoured today (I thought) in testimony,
and upon the whole it was a season of renewal of strength.

4th. Accompanied dear Sarah Stephenson and Mary Jefferys to Guildford,
in order to attend a burial and our monthly meeting.
Sarah Stephenson appeared largely and excellently,
and I thought the crook of divine love was once more, in abundant mercy,
stretched forth to the wanderers.
O, that they would be gathered.

14th. Have spent this week much alone in tranquillity, and have, at times,
felt my mind clothed with the incomes of that peace
which passeth the understanding of the natural man.

16th. A time of wading this morning,
yet was enabled to maintain the watch with a good degree of faithfulness,
and had to remember an expression of dear Thomas Ross,
"`Expect not to rise high when the seed lies low;`"
which I believe was the case in this meeting.

23rd. Having my mind unsettled before I went to meeting I fared but poorly there.
In the afternoon, going with full purpose of heart to settle down in the quiet,
and mind my own business, +++[+++I]
was favoured with a little of the refreshing streams of that river,
which maketh glad the whole heritage of God.

=== Fifth Month, 1797.

11th. I fear this week hitherto has not been so much improved as it ought.

12th. I found the tempter near today, on my first sitting down at meeting; but,
after struggling a while, was enabled to close my eye, and shut my ear,
to his false suggestions,
and repair to Him who is the healer of breaches and restorer of paths.

14th. This morning proved a season of sweet refreshment,
though humbled under a sense of my unworthiness, to approach perfect Purity.

21st. Attended Gracechurch-street meeting both morning and afternoon,
which were measurably owned by Him, who is the crown of all our religious assemblies;
though I suffered loss for want of more watchfulness in the latter meeting.

24th. A precious season this morning at meeting,
in which the baptizing virtue of truth was eminently felt
to attend the gospel labours of divers of the worthies present.

25th. Attended two sittings +++[+++of the yearly meeting]
and a committee.
My mind +++[+++was]
humbled under a sense of my dwarfishness,
seeing the beauty and dignity with which the Lord hath adorned many of my sisters,
who have trodden with more unerring feet the path of self-denial,
and more faithfully followed him in the way of his requirings.

28th. Attended Gracechurch-street meeting morning and afternoon,
the latter particularly favoured, through the ministry of divers friends;
yet my poor mind so stripped that I could partake
but in a very small degree of the good extended:
which was humbling.

=== Sixth Month, 1797.

7th. Came home and found my relations well,
which I esteem an additional favour to those already received; may I walk worthy thereof.

16th. Under a sense of the manifold blessings and benefits conferred upon me,
the language of my soul today at meeting was, What can I render unto thee, O Lord,
for them?
and I returned sweetly refreshed,
believing his continued regard was still extended towards me;
though such an unworthy creature.

22nd. This week hitherto spent mostly in the service of the poor;
and though my mind has not been so inward as it ought,
yet the better part has not been wholly neglected.

23rd. I sat down at meeting this morning in a sweet quiet frame of mind,
from which I hoped +++[+++for]
a good meeting; but felt some obstruction, whether in myself or others I know not, +++[+++so]
that I could not move forward until near the close;
when the sceptre was in gracious condescension extended,
and my soul was admitted into the presence of its best beloved, to its humble rejoicing.

25th. Had to struggle again this morning a considerable time,
before the stone was removed from the well`'s mouth; yet when that is,
through divine assistance, effected,
we can acknowledge it is well worth all we can do or suffer for it.
In the afternoon my mind was much humbled and contrited,
under a fear that I should not hold out to the end;
not from any doubt of the sufficiency of a merciful and kind Providence,
but from a deep sense of my manifold frailties.
I was led to crave preservation from the devourer.

30th. Was enabled to turn into the vineyard of my own heart,
where I found still much to do;
and also to look over what I apprehended the state of some others,
where I found cause of mourning on their account as well as my own.

=== Seventh Month, 1797.

3rd. Our quarterly meeting at Wandsworth, which I thought a season of precious favour,
though I was led as into the stripping-room; yet +++[+++I]
never find I get through the business of the meeting so well,
as when unclothed of all self-sufficiency;
which was in a good degree the case at this time;
being made sensible that I performed it in a strength superior to my own.

7th. Our monthly meeting.
The meeting for worship +++[+++was]
rather a low time to my feelings;
which was perhaps owing in part to suffering my mind
to be disquieted about trifles before I went to it.

14th. An humbling stripping time today at meeting;
wherein my righteousness appeared as filthy rags,
and I saw a deficiency I had been guilty of as overseer;
which I endeavoured after meeting to rectify, and though in much weakness, +++[+++I]
felt a degree of peace attend this little discharge of duty.

24th. My walk this evening rendered truly delightful,
by some unexpected proofs of gratitude in some poor people; yet +++[+++I]
desired to attribute nothing to the creature, but felt thankful for +++[+++the]
ability afforded to render any little services to those of that class.

28th. After struggling a while today at meeting with a lukewarm spirit, +++[+++I]
was favoured with access to the throne of grace,
where my soul was renewedly enamoured with the beauty and excellency of perfect holiness,
and led to aspire after it, as the greatest of all attainments.

=== Eighth Month, 1797.

9th. The spring of life I thought lay low today at meeting, +++[+++so]
that it required labour to get at it;
but when so favoured we can acknowledge it an abundant recompense, far, very far,
beyond our deserts.

12th. Felt the divine presence near me this evening in a solitary walk,
which brought every faculty of my soul into sweet quiet, and reverent thankfulness.

16th. My soul replenished with heavenly bread today at the little week-day meeting;
for which favour I desire to be made thankful enough.

27th. Sitting down today in a good degree of passiveness to the divine will,
my vessel was replenished with a little of the wine of the kingdom.

30th. Was enabled to say today at meeting, from a degree of living experience,
"`I know that my Redeemer liveth.`"
Forever blessed be His name who is dealing thus bountifully.
That he may be pleased mercifully to carry on and perfect his own work,
is what my soul craves.

=== Ninth Month, 1797.

2nd. How are the Lord`'s mercies renewed every morning!
I was favoured to feel his sustaining arm near me in the morning meeting;
and a comfortable hope attended that he was redeeming from every corruption.
O, that I may be preserved from marring his excellent work.

7th. I do not know that my actions have been condemnable;
but the state of my mind has seemed little else than weakness and folly.

17th. The morning meeting +++[+++was]
a low season to my own particular.
In the afternoon +++[+++I was]
bowed under a sense of weakness and imperfection; yet enabled to crave help,
and a little encouraged in the belief that amidst all,
love to the divine excellency had the preeminence in my heart.

22nd. Was favoured to sit as under my own vine today at meeting.
Inestimable privilege! may I ever prize it.

29th. Endeavoured to press through the crowd of encumbrances
today in our little silent meeting,
which I found hard work; yet towards the conclusion my labour was measurably blest.

=== Tenth Month, 1797.

14th. My reflections on myself humiliating;
yet I trust my desires after more stability were and are sincere.

15th. Found it not an easy matter to get my mind
centred beyond the fluctuating things of this life;
yet my labour was not altogether in vain, blessed be the name of the Lord.

17th. That the Christian`'s life is a continual warfare,
is often verified in my experience.
It seems to me that mine will never cease on this side the grave;
yet I sometimes think if I am but enabled so to maintain it as to reach the desired port,
all afflictions and trials will seem but as the dust in the balance,
compared with the joys of eternity.

22nd. It appeared to my weak faith and patience like the third watch,
ere I could meet with the Beloved of souls, today at meeting:
and even then but a small manifestation of his being near;
yet that was and is ever precious.

25th. I sat down today at meeting in a lukewarm disposition,
with which I had to struggle a considerable time;
but the good Shepherd of Israel being near,
at length extended help to those who had no might of their own.
Forever blessed be his holy name, he was pleased to remove the spirit of heaviness,
and clothe with the garment of praise.

=== Eleventh Month, 1797.

1st. I think I can with sincerity say,
that I love to meet the Lord in the way of his judgments,
because they have hitherto been mixed with mercy, so that they are sweet to my taste.
Thus though it was a season of inquisition, today at meeting,
yet it was precious to my soul,
which aspired after that complete redemption which can alone
fit me for the society of the spirits of the just made perfect,
and qualify to sing the praises of redeeming love.

5th. Though enabled in a good degree to maintain the watch this morning, yet +++[+++I]
sat in much poverty of spirit, under which I desired to be resigned to the divine will,
not doubting but it was most convenient for me.
In the forepart of the afternoon I was so unwatchful as to give way to a roving disposition,
which brought sorrow and contrition;
though I believed weakness and lukewarmness prevailed mournfully over the meeting:
yet that was no excuse for me, but ought to have excited to double diligence.

7th. On recounting my blessings I am led to believe that I am favoured
with both spirituals and temporals beyond thousands.
O, my soul,
it does indeed highly behoove thee frequently to ponder how much thou owest unto thy Lord.

9th. Though a season of some conflict today at meeting
(feeling the tempter near to draw me from my watch);
yet witnessing preservation, +++[+++I]
was enabled, I trust,
to perform that worship which is alone acceptable in the sight of God,
because it is of his own preparing.

15th. Sat under the teachings of the best of Ministers,
who verily teacheth as never man taught: even the precious anointing.

28th. Our monthly-meeting:
in which I was led into a state of mourning over
the desolation which prevails not only in the land,
but in our highly favoured society.

=== Twelfth Month, 1797.

1st. Sat in our little silent week-day meeting, in a good degree of self-abasement.

14th. This week +++[+++was]
much devoted to the service of others, mostly the sick and poor; yet +++[+++I]
have had at seasons to feel my own manifold weaknesses.

17th. A little renewal of strength today at meeting,
yet humbled in the evening under the consideration how far I loitered behind many,
in the heavenly race.

24th. Still buffeted with weaknesses,
and ashamed to appear a fool in the eye of the worldly wise.
May strength be graciously afforded to give up to what I believe is required of me;
though I doubt not but it will appear to some like straining at a gnat;
yet obedience can alone bring peace in small as well as great things.

29th. A trying week to my feelings divers ways hitherto;
yet methought a little light sprang up today at meeting.

30th. My state of mind today seemed comparable to poor Jonah`'s when his gourd was withered;
but more tranquil in the evening.

31st. My strength and faith in the all-sufficiency of God a little renewed, in my silent,
and I think I may add humble, waiting before him at meeting.
Thus closes the year 1797.
