== Chapter 11

=== First Month, 1801.

1st. Felt more tranquil and calm than for several days past.

2nd. Think I missed my way today, which was a source of humiliation.
O, to be enabled to make straight steps to my feet.

6th. Attended the quarterly-meeting at Esher.
We sat down a poor company, and I felt much discouraged;
yet I thought truth arose into some degree of dominion:
which I esteemed an unmerited favour.

16th. This week hath mostly been devoted to the service of others;
in which I hope I have borne the cross, with some degree of faithfulness.

18th. My mind much encumbered,
so that I fear instead of being benefited by going to meeting, I incurred condemnation.

24th. Often am I ready to adopt the words of the poet, "`O,
for a lodge in some vast wilderness,`" etc.

25th. The petition of my heart this day has been that the
Lord would be pleased to cut the thread of my life,
rather than suffer me to live separated from him.

30th. Favoured with some access to the "`fountain opened to the house of David,
and to the inhabitants of Jerusalem.`"
Inestimable privilege!

=== Second Month, 1801.

3rd. Our monthly meeting, where though I had to mourn over the desolation of our Zion;
yet was also favoured with a renewed evidence that my Redeemer liveth:
an experience more precious than the increase of corn, wine and oil.

8th. Methought I felt something like a renewed call to holiness,
and more unreserved dedication of heart, to which I desired to yield.
In the afternoon meeting +++[+++I felt]
shamefully lukewarm.

19th. Jacob Bell had a meeting with us.
He was dipped into the low state of things amongst us, and led to warn the rebellious.

26th. Much indisposed most of this week:
yet my mind has centered far too much in earthly things,
which at seasons have led me to mourn over my state, and crave deliverance.

=== Third Month, 1801.

6th. Though poor and weak, and altogether unworthy,
the Lord in great condescension contrited my spirit before him, and sweetly refreshed it.

8th. Felt so stripped and destitute of good,
that I had little more to offer than a sigh and a tear.

13th. Though I thought I went to meeting today in a proper frame of mind, yet +++[+++I]
felt little but leanness and poverty.

18th. Being free from inquietudes of late,
my mind has been uncommonly prone to centre in outward comforts;
yet at times I have felt desirous of watching over myself with a godly jealousy.

22nd. Was renewedly desirous of being redeemed from a groveling disposition;
and that my affections might be fixed on the alone substantial good.

26th. Felt something of that peace which the world can neither give nor wholly destroy:
a blessing far above rubies.

29th. Think I sat in a good degree of nothingness today at meeting.

31st. Attended our monthly meeting at Guildford, though poorly in health, in which,
I think, I laboured according to my small measure.

=== Fourth Month, 1801.

4th. Our dear friends, Mary Sweat and Charity Cook, from America,
came in very unexpectedly; which I esteemed a favour.

5th. A precious season in the morning, in which Mary Sweat,
Charity Cook and Deborah Moline appeared encouragingly.
A public meeting in the evening which I thought a favoured one,
the people uncommonly still and attentive.

6th. Accompanied our dear friends to Guildford, where we had a public meeting.
Mary Sweat particularly addressed a tried state.

7th. Our quarterly meeting,
in which my spirit was contrited under a sense of
my own insufficiency for every good word and work;
yet +++[+++I]
was enabled to get pretty comfortably through the business, I hope,
to the satisfaction of my friends.

26th. Still poorly in health,
though my spiritual strength was measurably renewed in the morning meeting:
the evening meeting +++[+++was]
inexpressibly trying.

=== Fifth Month, 1801.

3rd. Was renewedly convinced that it would not do to feed upon yesterday`'s manna,
and I desired not to eat the bread of idleness.

4th. Took a sweet meditative walk this evening.

9th. Turned over some of the past leaves of my life,
and numbered part of the many blessings bestowed upon me,
by a merciful and bountiful Creator.
O my soul, how much owest thou?
May this be thy frequent inquiry.

10th. Had this morning renewedly to set up my Ebenezer, and say,
"`Hitherto hath the Lord helped me.`"
"`Keep thy foot when thou goest to the house of God,`"
was the watchword as I sat down in the afternoon,
but I lost ground, and gave way to a roving disposition,
which brought deserved condemnation and sorrow.

12th. Peaceful and tranquil.

15th. Some renewal of my Spiritual strength.
Came to Alton in order to set my sister at liberty to attend the yearly meeting.

17th. Precious heart-tendering seasons both morning and evening,
which I esteemed an unmerited favour.

20th. A trying day from indisposition; but divine good was not wholly withheld at meeting.

22nd. I think the duties of this day have been measurably fulfilled.

27 A snare thrown in my way this morning to which I too much yielded;
but humbling myself before the Lord, whose compassion faileth not,
he was pleased to restore health to my soul: an unmerited mercy indeed!

29th. A trying day to my feelings; yet +++[+++I]
laboured after resignation, which I was favoured measurably to attain to.

31st. A trying day, from indisposition; but not without divine refreshment.

=== Sixth Month, 1801.

11th. Days of trial from extreme heat and debility.

12th. John Abbott and Samuel Rundell were at our week-day meeting:
Samuel Rundell was led in a close line to the earthly-minded,
and afterwards had a word of encouragement to the mourners in Zion, as had John Abbott.
A public meeting in the evening,
which I think was more satisfactory than such opportunities often are.

20th. "`The King`'s daughter is all glorious within,
her clothing is of wrought gold,`" impressed my mind at meeting this morning;
which led to an examination to see how far I resembled her.
I fear there is yet much alloy, much work for the fire and hammer.
May I stand resigned to their purifying operations.

26th. Was renewedly desirous of washing my hands in innocency;
that so I might compass the altar of God.

28th. The Lord is still blessing Zion and satisfying her poor with bread.
Though this was my blessed experience in the morning
meeting I was in the afternoon lukewarm,
partly owing to the oppressive heat of the weather.

29th. Retired pleasantly a while this evening out
of the encumbering things of this world,
which I find engross too much of my precious time.

=== Seventh Month, 1801.

3rd. Rather a low time at meeting today.

4th. My niece was this day married.
I was so much indisposed that I could feel little ability for any thing more,
than some aspirations for her preservation.

9th. Reached Bristol about noon: found our dear relations well.

10th. Attended the week-day meeting.
In the afternoon +++[+++I]
went to Pill to see if our dear friends Samuel Smith and Sarah Stephenson had sailed,
+++[+++and]
found them on shore at John Grace`'s. Spent a pleasant evening with them.
They were led in an encouraging line, in an opportunity after tea;
sweetly exhorting to an increasing faithfulness and patient enduring to the end.

13th. Their week-day meeting +++[+++was]
silent, but a season of sweet solace to my poor feeble mind.

19th. A trying day from indisposition.

21st. Week-day meeting; dear Hannah Stephenson appeared acceptably.
I was too lukewarm myself.
Came in the afternoon to Weston.

23rd. Walked for some hours on the beach, admiring the majesty and beauty of the ocean;
and the power and wisdom of Him who created it;
setting bounds and limits to its proud waves, saying "`Hitherto shalt thou come,
but no further.`"

25th. Sweet and peaceful in this humble cottage,
where I see how few things are really needful.
A sense of multiplied blessings hath bowed my spirit this morning.

26th. Walked on the beach before breakfast.
After it +++[+++I]
retired into a field to commune a little with my own heart and be still.

27th. Retired a while;
but could feel little of that life and love which sustains and comforts the soul.

31st. Came to Bristol, +++[+++and]
attended the week-day meeting, which was a season of favour to my soul.
I was consoled in the remembrance that the servant who gained but two talents
to those committed to his care was accepted as well as he who had gained five.

=== Eighth Month, 1801.

2nd. A contriting season at meeting this morning during the time of silence.
Came to Weston in the afternoon.

4th. How are the Lord`'s mercies renewed from day to day; sustaining, consoling,
and instructing the attentive mind!

8th. The rest of this week spent in peaceful retirement at Weston: I hope not unimproved.

10th. A day to be remembered for the fresh descendings of heavenly dew,
and pure aspirations after holiness.

14th. Renewed my spiritual strength today at meeting.
What a favour!

18th. Shamefully lukewarm at meeting this morning, which brought deserved condemnation.

23rd. Some life attended the morning meeting; the evening I thought painfully dull.

25th. Favoured with sweet access to the throne of grace;
where I craved the continuance of divine regard,
and preservation from even the appearance of evil.

30th. A time of searching of heart;
and the petition of it was that the Lord would be pleased to do my work in me and for me,
seeing my insufficiency even to regulate my thoughts aright.
Dear George Dillwyn ministered unto us clothed with best authority;
and I thought divided the word aright.
Had a sweet little opportunity after supper at Ann Till Adams`'.

31st. Spent the day in sweet society: dear brother Samuel with us.

=== Ninth Month, 1801.

12th. The rest of this week confined by a cold and fever;
yet fear it has not been much improved.
Attended the morning meeting, in which my spiritual strength was sweetly renewed,
George Dillwyn appeared largely and acceptably, and also Phebe Blakes.
Phebe Blakes and Sarah Lynes dined with us.
The latter addressed my dear mother in an extraordinary manner,
and after much encouragement told her,
that she believed that after the warfare was completed,
she would be gathered as a shock of corn fully ripe into the heavenly garner.
Then she encouraged poor me to hold on my way; believing,
though I was permitted to pass as through the waters, the waves should not overwhelm me;
and through the fire, the flames should not kindle upon me, etc.

16th. The quarterly meeting +++[+++for Bristol and Somersetshire]:
I thought it a time of gathering.
The wing of ancient Goodness was sensibly spread over us,
to the rejoicing of the spirits of some of us;
dear Sarah Lynes and Phebe Blakes appeared acceptably among us;
and were again exercised in the meeting for discipline,
to call the youth to come home and build upon the alone sure foundation,
Christ Jesus the Rock of ages.

18th. Took leave of my beloved relations and friends; and came to Salisbury.
I was very ill the greater part of the day and the night following;
yet came on to Alton next day.

20th. Again laid upon the bed of sickness.
Have renewedly desired that my will may not in any wise oppose the Lord`'s will.

25th. The quarterly meeting +++[+++for Hampshire]. Some
degree of favour I thought attended the meeting today.
I think I felt thankful that I was permitted to sit with my dear friends.

26th. Returned home after an absence of three months.

29th. Received the affecting intelligence of the removal of my sweet nephew John Waring;
yet think it an unspeakable consolation that he is
gathered with the beauty of innocency upon him.
Attended our Monthly meeting, a contriting season.

=== Tenth Month, 1801.

3rd. A day of joy to thousands: peace being once more restored to this guilty land;
in addition to the blessing of a plentiful harvest.
It has renewedly bowed my spirit before a gracious and long suffering God;
desiring such unmerited mercy may not pass unacknowledged, or unimproved.

5th. Methought the dew of heaven rested upon me this day,
which sweetly contrited my spirit before a merciful God.

10th. Have desired to bear my allotted portion of suffering with patience and resignation.

11th. Was desirous that my offering this morning might not be polluted with self,
but of the Lord`'s preparing, well knowing it is his own works,
which alone can acceptably praise him.

14th. Have had my time pretty fully occupied for several days,
and my mind at times beset with a temptation, from which I craved deliverance:
at other times +++[+++I have been]
sweetly tranquil and resigned.

18th. Instructive seasons +++[+++were]
both +++[+++the]
morning and afternoon meetings.

23rd. Went to meeting with a mind encumbered with care and anxiety,
expecting but little consolation;
yet the Lord was pleased to lift up the light of his countenance upon me,
which encouraged me to repose my all in him; who assuredly is a God nigh at hand,
and a present help in the needful time.

=== Eleventh Month, 1801.

1st. My soul sweetly replenished with celestial rain,
which qualified to offer the sacrifice of praise to an all bountiful God.

8th. Sweetly called to mind the Lord`'s mercies in visiting my poor soul,
when dead in trespasses and in sin, saying, "`Let there be light and there was light.`"
O may the work of the new creation go on, breathing continually glory to God,
and good-will towards man.

12th. This week, like the foregoing, pretty much occupied with an afflicted relation.

13th. Repaired this morning to the healing waters,
which I was favoured to feel flow like a stream to my thirsty soul.

20th. Another trying week;
yet was favoured this morning to rise a little above these encumbering things,
and press through the crowd, and touch the hem of His garment, in whom is living virtue.

27th. Was favoured resignedly to lean upon the beloved of souls,
who remains a covert from the wind and the storm.

=== Twelfth Month, 1801.

3rd. Poorly and disquieted with trifles; yet was enabled to overcome it in a good degree.

11th. Spent most of this week at Guildford, I trust not altogether unprofitably,
feeling frequent aspirations after a state of purity and holiness.

13th. Was afresh dipped into close exercise on account of the wanderers;
earnestly breathing for the restoration of such,
and the salvation of mankind universally.

16th. David Sands came to our house, and had a public meeting in the evening,
which I thought a solemn one.
He was strengthened to preach Jesus, inviting the people to come to him,
the fountain of living waters.

19th. I accompanied David Sands to Issington, +++[+++and]
dined at Wanborough.
An opportunity occurred in which he sweetly addressed the family.
My mind was deeply bowed on their account.

20th. Came to Alton.
Attended the two meetings, which I thought favoured seasons,
and David Sands was led to speak to the state of those present.

31st. Confined from an accident, which I fear I have not sufficiently improved;
though I believe +++[+++the time]
not idly spent, yet my thoughts have not been sufficiently under divine regulation.
Indeed it has seemed, at times, as if I was left to myself,
to show me what a very weak creature I am.
Yet some aspirations after a better state have ascended at seasons.
