== Chapter 12

=== First Month, 1802.

1st. Our monthly meeting.
The meeting for worship +++[+++was]
a season of deep abasement to me,
thinking myself unworthy to approach the Purest of Beings,
yet sensible I was indebted to him for the many blessings with which I was surrounded.
In the meeting for discipline desired leave to withdraw as clerk;
not from a wish to be less serviceable to society,
but from a belief that some diffident minds should be brought forward into service.

3rd. Was enabled to rise above the corruption of
my nature and centre a while in the supreme good.
Great indeed is the compassion of God towards the meanest of his works.
O, that I was more worthy.

4th. Our quarterly meeting, a dull time.
The meeting for worship +++[+++was]
short; and so many words, that my mind got hardly stayed.

10th. Trust I was enabled this morning to worship
the Father of spirits with some degree of acceptance.
What a favour!

17th. The desire of my heart this day has been that we of
the middle-aged might be as way-marks to the beloved youth,
inviting them, in the language of example, +++[+++to]
"`Follow us as we`" are endeavouring to "`follow Christ.`"
A deep sense of the depravity of +++[+++a]
great part of the human race affected my mind,
and raised cries to the Father of mercies that they might
be brought to the knowledge of himself and be saved.

19th. Have been turning over some of the past leaves of my life;
and entering afresh into the chambers of sorrow in my dear father`'s illness and my own,
under which trials the Lord mercifully sustained me.
A sense of his unmerited goodness to me, all my life long unto this very day,
and of my own continued unworthiness has at this time bowed my spirit before him.

31st. I was mercifully enabled this morning to rise above the things of this life,
and favoured to partake, according to my measure, of the joys of God`'s salvation.
In the afternoon a sigh and a tear were all I had to offer;
yet believed it profitable to know how to want, as well as to know how to abound;
and to be renewedly convinced that the latter is not at our command.

=== Second Month, 1802.

2nd. Our monthly-meeting at Guildford, in which +++[+++I]
was renewedly desirous of repairing to the ancient foundation,
yet found it hard work to get to it.

10th. The last few days much devoted to the service of others,
though I fear not much spiritually improved.

12th. I went to meeting this morning in a comfortable frame of mind;
but the enemy of all good soon caught its unwary attention,
and led it into the fields of imagination, where it remained for some time captivated;
but the good remembrancer, who was also near, drew it in mercy towards himself,
showing me my folly; which cost me many tears, and in, I trust, true contrition of soul,
measurably effected the work of reconciliation:
I record it under an humbling sense of unmerited condescension,
and of my own unworthiness.

13th. That the Christian life is a continual warfare was confirmed in my experience today.
I trust it was in a good degree maintained in both meetings.

18th. Shook off sloth, and rose early,
desiring a sense of the divine-presence might preserve me in innocence, in thought, word,
and deed, through the day.

20th. My mind exercised on account of several whom I love;
and was led to petition for them the blessing of preservation from every hurtful thing,
and that they might be favoured to see and embrace
the things which will ensure their everlasting peace.

21st. The morning meeting +++[+++was]
a precious season, the unction from above resting upon the minds of some of us,
which were in a good degree gathered into the silence of all flesh.
A painful circumstance occurring before the afternoon
meeting which I thought struck at the best life,
my mind was so involved in it that I could rise but little above it.

23rd. Renewedly desirous of keeping the word of the Lord`'s patience,
that so I might be kept from the hour of temptation.

24th. Sweet and tranquil: every care, and unprofitable desire,
measurably bounded by the limiting power of truth.

26th. Desired to be preserved from shrinking from the crucifying power of truth,
which can alone qualify for an admission into the rest that is undefiled.

28th. Low stripping seasons today at meeting,
probably for want of a more unremitting watch;
yet thought I laboured according to my small ability.

=== Third Month, 1802.

5th. Our monthly meeting.
Methought it was a time of wading.
Can the true Israel sing when the seed is in captivity?
Verily nay.

10th. A dissipating day, spent much among the gentry,
respecting a benevolent institution in hand, yet +++[+++I]
do not recollect but the cross was pretty fully borne by me.

12th. "`Ponder the path of thy feet,`" and "`let thine eyes
look right on,`" was the watch word today at meeting.
O, that I may be enabled so to do, in all my steppings, through the vicissitudes of time.

14th. A circumstance occurred which called for the exercise of that Christian meekness,
which we as a people profess.
May we be preserved in it, and enabled when smitten to turn the other cheek also.
The prayer of my heart has been, that I may be so preserved, and, if opportunity offered,
return good for evil.

15th. My mind much encumbered with the foregoing circumstance.

16th. Rose a little above it, by repairing to the Healer of breaches.
What a mercy to have such a Rock to retire to from the wind and the storms!

21st. Deeply humbled under a belief that I had not fully acknowledged
the Lord in all my ways as I ought to have done.
In the afternoon +++[+++I]
think the watch was in a good degree maintained,
being sincerely desirous that the days work might keep pace with the day.

25th. My time fully occupied in serving my neighbours, even to weariness.

28th. I think the duties of this day have been in a good degree performed,
through divine assistance; no merit due to the creature.

=== Fourth Month, 1802.

2nd. Was enabled to rise above the encumbering things of this life:
and to aspire after that communion which is with the Father and with the Son:
of which I was measurably made to partake.
Adorable condescension!

4th. A time of digging this morning.
In the afternoon +++[+++I]
could once more set up my Ebenezer, and say, "`Hitherto the Lord hath helped me.`"
What shall I render unto him for all his benefits?

6th. Our quarterly meeting.
I thought the silent part of the meeting for worship
measurably owned by the great Master of assemblies.
The meeting for discipline was trying to my feelings.
+++_______+++ appeared, endeavouring to rouse the lukewarm,
and encourage the youth to more faithfulness.

13th. Read some letters from those to whom I was once nearly united;
and who of later years have deserted the precious cause of truth.
My soul was deeply prostrated,
under a humbling sense of the continued kindness of a merciful God,
who hath hitherto preserved me alive amidst so much weakness;
and renewed desires were begotten in my heart for the recovery of these strayed ones.

16th. Our week-day meeting was to me a stripping time,
in which I had renewedly to acknowledge that in me as a creature dwelt no good thing;
and that, if I did any good, the sufficiency was of God: in whom dwells the fullness.

18th. Think the warfare was in a good degrees maintained today,
nor were my feeble endeavours unowned by condescending Goodness;
whose mercy is assuredly over all his works.

22nd. I think the last few days have not been spent vainly, or idly;
yet perhaps they might have been more improved.

23rd. I laboured today at meeting, I believed according to my small measure;
yet for want of more united exercise of spirit the work lies heavily on a few,
who I trust are preferring Jerusalem to their chiefest joy.
Taken suddenly ill.

26th. Had a trying night, and was very ill this morning.
The prospect looked awful.
I desired that nothing might arise in my heart to oppose the Lord`'s will,
whether life or death: believing he would order all things aright.
Under this sustaining conviction I felt calm and quiet,
which I esteemed an unmerited mercy; towards evening the symptoms were more favourable.

=== Fifth Month, 1802.

4th. My strength nearly restored.
How is the debt of gratitude increased within the last fortnight!
May I dwell under an humbling sense thereof; deeply feeling my unworthiness,
and the gracious condescension of a merciful God towards one of the meanest of his works.

6th. Had a letter from my precious niece--which gave me
reason to hope that the good seed is not only sown,
but likely to produce fruit.
May the Lord in his wonted goodness,
be pleased to preserve this tender plant from every noxious thing;
that it may flourish and yield the peaceable fruits of righteousness,
which are quietness and assurance forever.

12th. This week +++[+++was]
much taken up with the company of my brother and sister, and though truly pleasant,
I was comforted to feel that nothing short of heavenly
communion could satisfy the immortal part.

14th. Favoured with some access to the sovereign Good in our little silent meeting.

19th. This day the yearly meeting began.
I thought the overshadowing wing of that goodness which
is ancient and ever new was measurably spread over us.

27th. Again laid upon a bed of sickness; to which I was pretty much confined this week.
My feelings at times +++[+++are]
almost overwhelming; at others more comfortable.
Many kind friends came to see me,
yet I have with shame to record that my eye was not
sufficiently single to the great Physician of value;
but centered too much in outward comforts.

=== Sixth Month, 1802.

3rd. Returned home, bore my journey better than could have been expected.

4th. Ventured to meeting, though weak, which proved a contriting season to my poor mind,
which was deeply humbled under a sense of my manifold deficiencies.
Thomas Clarke +++[+++was]
there, who paid me a visit in the afternoon,
in which he had to hand forth a word of encouragement to me.

8th. Still weak both in body and mind;
yet some aspirations after redemption from all evil have
at seasons ascended to the Fountain of all our sure mercies.

12th. Was favoured today with a renewed evidence that I am not forsaken:
an experience more precious than rubies.

18th. An humbling season today at meeting,
where the language of the poor publican was adopted, as applicable to my state.

23rd. Sadness was much the covering of my mind today from several causes,
one of which was the account of dear Sarah Stephenson`'s removal from works to rewards,
while engaged on a family-visit in Philadelphia.
Yet +++[+++I]
believe there is no cause to sorrow on her account,
but much need to look to our own standing,
that we may also die the death of the righteous.
O, that my latter end may be like unto hers, full of sweet peace.

25th. Discharged my duty as an overseer to the best of my ability;
in other respects weak enough.

26th. Returned from meeting this morning as from a washing-pool, sweetened and refreshed;
but not watchful enough in the afternoon.

28th. Am renewedly convinced that the way to the kingdom is straight and narrow indeed.
O that I may be enabled to walk therein with unerring feet; but, alas! few, I believe,
are so weak, and prone to what is wrong.

29th. Temptations of various kinds have beset my path of late, to which I have too much,
far too much, yielded at times; at others, measurably resisted,
and craved deliverance from them.

=== Seventh Month, 1802.

2nd. Afresh assaulted by the enemy of all good,
who sought to lay waste every heavenly desire; but in matchless love and condescension,
the Lord once more enabled me to set up my Ebenezer, and say,
"`Hitherto hast thou helped me.`"

5th. Our quarterly meeting.
I thought a good degree of solemnity was over the meeting,
particularly the forepart of it.
The meeting for discipline was trying to my feelings,
yet dear Sarah Hack was strengthened to kneel down and supplicate
the Lord to carry forward his own work.

10th. Wrestled, as in the night season, and obtained but little:
the afternoon meeting more lively.

13th. Felt something of the refreshing dew rest upon my poor wearied mind.

17th. Had renewedly to number my blessings, and acknowledge they were far, very far,
beyond my deserts.
In the afternoon +++[+++I]
gave way unprofitably to a roving disposition,
for which I was favoured to feel a degree of true contrition.

21st. The last few days much devoted to the service of the poor,
and I think I have been preserved in a good degree of watchfulness.

22nd. Shamefully lukewarm at meeting,
which produced some conflict and sorrow towards the close of it.
Missed my way in the evening.

23rd. Much in the valley, fearing I should one day fall a prey to my potent enemy.

21st. Some renewal of spiritual strength today: a favour I esteemed myself unworthy of.
May it excite to a more faithful walking before the Father of mercies.

27th. That the Lord is rich in mercy, and plenteous in redemption, I firmly believe.
May it deepen my gratitude, and make me careful not to offend him;
yet I am daily made sensible that I cannot take one step
aright in the heavenly race without his divine aid;
for assuredly it is his own works alone that can praise him acceptably:
nothing that we can do as creatures.

=== Eighth Month, 1802.

4th. My spirit contrited under a grateful sense of present, as well as past,
multiplied blessings bestowed upon me by a merciful Creator.

11th. How weak and inconstant is the human heart!
One day I think I am preferring Jerusalem to my chiefest joy;
and that the enemies of my own house are measurably slain;
then I find that I am again taken captive by them,
that they are not only alive but powerful.
Again I seek deliverance from them, and again they allure my unwary feet,
yet the warfare is still, through divine assistance, in some degree maintained.
This hath been much the state of my mind the last few days.
May my eye be single to the Lord, who can alone give victory.

15th. The morning meeting I thought not very lively: the afternoon,
contrary to expectation, proved a precious season,
wherein divine instruction was vouchsafed to my waiting soul.
May this renewed and unmerited favour excite to a more circumspect
walking and unreserved dedication of heart.

18th. Think I have stepped along the last three days with a good degree of watchfulness.

19th. Dear Mary Sweetapple removed, after a few days illness:
a lovely flower early transplanted to a better country,
where I trust she will bloom to eternity.

20th. "`Make clean the inside of the cup and the platter,`" was
what impressed my mind soon after my sitting down in meeting,
and earnestly did I desire it might be the case;
and the petition of my heart was that the Lord would
be pleased to renew his heavenly image in my soul,
until there was an entire conformity.

24th. Renewedly desirous of having my goings established
and my feet fixed on the immoveable Rock of ages.

29th. The morning meeting I thought rather dull.
In the afternoon missed my way, which produced deep contrition.
I was favoured in the evening meeting to feel something
of the healing water dispensed to my poor soul.

30th. On a retrospection of this day +++[+++I]
fear it has passed away wholly unimproved: to my shame I record it.

31st. Have endeavoured to keep my mind more on the watch:
which I have been favoured with some ability to perform.

=== Ninth Month, 1802.

2nd. Had to lay aside all self-sufficiency:
in which lowly state the Lord was pleased to own
me with the overshadowing of his life-giving presence.
Unmerited mercy!

6th. Gave way unprofitably to a roving mind this morning;
afterwards endeavoured to keep it more stayed.

7th. The bent of my mind this day has been in a good degree towards the Sovereign good.

8th. The morning not spent profitably:
in the afternoon felt something of a real hunger after the bread of life.

9th. A precious heart-tendering season in the silent week-day meeting.
There is no want of words where the best of ministers preside.

15th. The monthly meeting at Uxbridge, a precious, favoured season!
I thought Sarah Lamley favoured with near access to the throne of grace.

19th. Renewed aspirations after perfect purity.

23rd. Received the affecting tidings of the removal of Elizabeth Heath.
It seemed like a renewed call, "`Be ye also ready.`"

25th. A season of sweet solace in our little silent gathering.
Oh, that any should be slighting so precious a privilege!

26th. Instructive seasons, both morning and afternoon, to my waiting soul.
Thomas and Elizabeth Ashby appeared acceptably in the morning,
and the latter also in supplication.
Spent the evening at Robert Moline`'s.
A sweet opportunity after tea,
in which Thomas Ashby had to encourage a state present to faithfulness.

28th. Our monthly meeting at Guildford,
which I thought measurably owned by the great Master of our assemblies.
After dinner Thomas Ashby sweetly addressed John and Mary Sweetapple,
recurring to their late loss,^
footnote:[See 19th of Eighth month.]
and expressing his desire for their advancement in the path of religious usefulness.

=== Tenth Month, 1802.

1st. Enabled to wrestle a little for the blessing; which in great mercy was not withheld.

5th. Our quarterly meeting, which proved an exercising time to my feelings.
Again chosen for clerk;
nor could I get at that state of quiet my soul earnestly desired and breathed after.
It was perhaps permitted for my humiliation.

8th. Some renewal of my faith and confidence in the divine All-sufficiency,
in our little gathering.

10th. Methought I was brought today as to the measuring line, and shown my deficiencies;
which humbled and contrited my spirit before the Father of mercies.

11th. Though a busy day, +++[+++I]
found a little leisure to retire out of the cumbers,
and feel after that power which can alone preserve from falling.

15th. My feelings somewhat tried, under which I was preserved in a good degree of quiet.

17th. Found it hard work to get at the spring this morning,
and I believed it was for want of a more united exercise of spirit;
yet the blessing was not wholly withheld.

21st. The cloud appeared to me to rest upon the tabernacle,
so that there seemed but little ability to move forward;
yet was favoured with some degree of quiet.

24th. Much beset with weakness and temptation;
yet was favoured to rise for a while above it, and repair to the Healer of breaches.

31st. Went to Guildford to meet my friend David Sands.
Attended the afternoon meeting,
in which he had a word of encouragement to hand to the mourners in Zion.
A public meeting in the evening to good satisfaction.

=== Eleventh Month, 1802.

5th. Attended our monthly meeting.
David Sands appeared largely in testimony, +++[+++which]
was close to the lukewarm, but encouraging to the sincere-hearted.
Spent the day at brother Kidd`'s:
David had an opportunity in the evening with the young folks,
and was drawn forth excellently in supplication.

7th. Accompanied David Sands to Issington, +++[+++and]
had a sitting in the family in the evening.
First-day +++[+++we]
came to Alton, attended both meetings,
and had a sweet opportunity in the family in the evening,
in which the young folks were tenderly addressed, with which they seemed affected.

8th. Went to Issington in the afternoon, a public meeting being appointed in the evening.
About two hundred people attended from the neighbouring villages,
who appeared well satisfied, and some affected with David Sand`'s doctrine.
I thought him remarkably clear and favoured in testimony.

9th. Returned to Alton: another public meeting the evening,
in which David Sands was led to explain the nature
of the gospel dispensation and true ministry.

13 We parted from our beloved friend in near affection;
my dear mother and self returning home, David Sands intending for Basingstoke.

14th. Was thankful to feel that the dew of heaven was not withheld;
notwithstanding my mind had been too much outward and centering in worldly comforts.
May it excite to more vigilance and circumspection.

18th. Much of a Martha this week, having many things to attend to,
and my mind unprofitably outward.

21st. A day of some conflict of spirit, and deep humiliation.

23rd. Sat a while as at Wisdom`'s gate, when the petition of my heart was,
that the Lord would deign to be my portion,
and the God of Israel the lot of my inheritance forever;
and then let come what will come, all will be well.

25th. Think I may venture to say this day has been well spent as to action;
but my poor mind has seemed left a prey to its own weakness and frailty,
so as to be almost overwhelmed.

26th. Notwithstanding I sat down at meeting, and seemed a while stripped of all good;
yet, after some struggling, +++[+++I]
was enabled to sing a little of mercy and judgment.
What a favour!

28th. Through divine assistance the warfare was in good degree maintained this morning;
though not without considerable conflict.
In the afternoon and evening +++[+++I was]
too unwatchful, which brought the deserved punishment of sadness of heart.

29th. Methinks my dwelling has been much in the valley where I desire to continue:
believing my safety consists in a state of humble watchfulness.

=== Twelfth Month, 1802.

3rd. My hope and confidence in the Lord sweetly renewed
in my silent waiting this morning at meeting:
for which favour I desire to bless his holy name.

5th. Notwithstanding some weakness and besetment, +++[+++I]
was favoured to rise for a while above it,
and approach Him who is the health of my countenance, and my God.

8th. Gave way to the suggestions of my cruel enemy, which brought deserved condemnation;
and, like poor Peter, I wept bitterly.
May I, like him, be favoured to witness perfect reconciliation and forgiveness.

12th. Renewedly convinced from a degree of blessed experience,
that there is still "`Balm in Gilead,`" and "`a Physician there,`"
willing to heal the wounds made by sin and transgression.
How lamentable so few should avail themselves of so precious a privilege!

13th. A day not wholly unimproved,
as I have been enabled to afford some relief to my fellow creatures and think
my mind hath been measurably bounded by the preserving fear of the Lord.
What a favour!

17th. My poor mind sweetly refreshed today, at our little silent meeting.

19th. My mind so beset with perplexing circumstances,
that I reaped but little benefit by going to meeting;
though I made some efforts to press through the crowd;
yet a sigh and a tear were the poor offerings I had to make.

24th. Have spent this week with my friend Sarah Birkbeck (of Guildford) who is ill,
and required my attention; and though a consciousness of some weaknesses is my companion;
yet trust I have not incurred much condemnation.

30th. Have had my mind encumbered this week with many things; yet trust +++[+++I]
have not lost sight of the better part.

31st. A refreshing season at meeting,
in which my hopes and confidence were sweetly renewed in the Lord.
Thus ends another year of my pilgrimage.
That I may so run the remainder of it, as to obtain, in the end, the answer of well done,
is the petition of a heart humbled under a sense of its manifold infirmities.
