== Chapter 14

[.centered]
=== First Month, 1804.

1st. The vision of Jacob`'s ladder, and the angels ascending and descending thereon,
opened sweetly on my mind, pretty early in the meeting:
which appeared to me a lively representation of the
communion between the soul and its Creator,
when favoured to ascend this heavenly ladder,
leaving all transitory things at the foot of it;
and the prayer of my heart was that it might be fitted
more and more for so precious an enjoyment.

8th. Many things crowding in since my last remark,
I forget particularly what has occurred, but this I know,
that goodness and mercy have followed me from day to day;
and though I may not always have improved these blessings as I ought to have done;
yet on a retrospect I feel not much condemnation.

14th. Came to Guildford to spend a few days with my dear Sarah Birkbeck,
who is in a declining state of health.

15th. I think I was enabled to centre for a while in the silence of all flesh,
this morning at meeting.
In the afternoon stayed with Sarah Birkbeck, our time not spent unprofitably, I trust.

17th. A precious contriting season in sitting with the little handful at this place.
After it, met with an exercise of Christian patience; which, I trust,
I bore with becoming meekness.

20th. Not so watchful as I should have been, from which I suffered loss.

21st. My dwelling hath been much in the valley this day: a lowly, but a safe situation.

22nd. Sitting down this morning at meeting, in much abasement,
I was favoured to feel something of the healing waters dispensed to my thirsty soul:
a favour I esteemed myself unworthy of.
+++[+++In]
the afternoon, +++[+++I]
did not maintain the watch so steadily as I ought to have done.

25th. Have been too much dissipated and in the mixture;
yet have at times mourned my thraldom and breathed for deliverance.

26th. "`Day unto day uttereth speech, and night unto night showeth knowledge.`"
Mayest thou, O my soul, open thine ear to instruction.

29th. I thought the morning meeting a preciously favoured season,
dear Susanna Horne had a word of encouragement to hand to the mourners in Zion,
and an invitation to the youth, to come, taste,
and see how good the Lord is to those that love and fear his name.
The afternoon not so lively, Susanna Horne had a sitting in brother Kidd`'s family,
and with my beloved Sybilla Turnour in her chamber,
whom she endeavoured to encourage to come forward in the Christian race:
concluding with this passage, "`Come up hither, I will show thee the bride,
the Lamb`'s wife.`"

[.centered]
=== Second Month, 1804.

12th. A variety of circumstances have combined within
the last two weeks to harass my mind,
so much so, as almost entirely to preclude that quiet, and settledness so desirable,
and which I have at seasons pressed after,
and of course disqualified me from minuting down my feelings as they occurred.

19th. Deeply humbling were my views of myself this day;
yet some encouragement was also administered, through adorable condescension.

21st. I have considered the station I stand in as awful,
some looking towards me for example and help.
O that I was indeed qualified for a waymark;
but instead thereof how often have I to mourn over my leanness and poverty.

24th. A time of searching of heart today in our little silent meeting:
an employ I desire to be often found in.

26th. My mind, through unwatchfulness, got entangled in a snare, spread before it,
I doubt not, by the enemy of all good, in order to divert its attention,
on my first sitting down at meeting; but after a while the good Remembrancer,
being also near, showed me my folly; to whom I cried for deliverance,
and was enabled to press through and touch the hem of his garment,
and found healing virtue to flow from him.

[.centered]
=== Third Month, 1804.

3rd. Much beset with evil:
yet trust through divine assistance the warfare is still measurably maintained.

4th. Still weak and poor every way, yet I trust not forsaken.
What a mercy!

7th. Faint yet pursuing.

9th. A little revival of my faith and confidence this morning,
in our little silent gathering.

11th. Came to Guildford to see dear Sarah Birkbeck,
who is in all human probability hastening towards, I trust, a better country.

14th. My time pretty fully taken up, in attending my dear friend;
yet I think I have been preserved in a good degree
of watchfulness and favoured with peaceful serenity.

17th. A trying day and night,
in beholding the conflict of our dear friend in putting off the shackles of mortality;
which she was mercifully released from about twenty
minutes before eight o`'clock this morning,
which we that had been witness to her sufferings esteemed a favour.
Some hours before the solemn close, as dear Morris Birkbeck and I were sitting together,
a sweet calm spread over our minds, which seemed to me like an evidence,
that his dear wife`'s spirit was near centering beyond the reach of pain and sorrow.

18th. Morris Birkbeck was strengthened to get out to meeting today;
where he supplicated for resignation.
It was to my poor wearied mind a refreshing season,
feeling something of the holy unction to rest upon it.

20th. Was desirous of digging deep,
that I might be favoured with the renewed discovery of the ancient foundation,
which was in great condescension vouchsafed.

23rd. Several friends came to attend the burial of dear Sarah Birkbeck.
The meeting was held in silence, but I thought the forepart, particularly,
was covered with a degree of solemnity.

26th. Was jealous over myself that I had not attained
to that strength and stature designed for me,
had I been more watchful and stable.
May this jealousy and fear excite me to ponder well the path of my feet.

29th. Pretty much engaged the remainder of the week, in preparing for leaving home;
yet not I trust to the entire neglect of the one thing needful.
May I ever choose this better part, and then I have faith to believe,
it will never be taken from me.

[.centered]
=== Fourth Month, 1804.

1st. Some renewal of my spiritual strength.
Left home this evening.

3rd. The quarterly meeting.
I thought it a more favoured season than it is often our lot to experience at such times;
and the business got through more satisfactorily;
for which I felt a degree of thankfulness: as well as in beholding some growth,
as I apprehended, in some of our young members.

5th. Set forward for Alton, in company with Morris Birkbeck,
at which place the yearly meeting`'s committee met,
as proposed at parting in the twelfth month.

18th. This morning, after a contriting season together,
our little company began to separate in the fresh feeling of that love,
which had sweetly united us in moving along through this arduous engagement: for which,
with many other blessings dispensed, I desire to be reverently thankful.

21st. Since my return home, although I have felt unusually impoverished,
yet a degree of peaceful quiet has accompanied my mind,
and some aspirations after increasing dedication
and conformity of will to the Divine will.

22nd. Some searching of heart,
and calling to mind the manifold favours of a merciful God,
towards one of the meanest of his works.

25th. Deeply humbled on turning over some of the leaves of my past life,
to see how much goodness and mercy have been extended from time to time,
yea all my life long, to so unworthy a creature.
May it excite to double diligence, for surely the debt I owe is beyond all calculation.
Content not thyself, O my soul, with making these remarks,
but endeavour to dwell and move under an humbling sense of thy obligation.

27th. The prayer of my heart was, that not an impure or offensive thought might arise,
but, that the food most convenient for me might be graciously dispensed.

29th. Instructive seasons to my waiting soul, +++[+++were]
both +++[+++the]
morning and afternoon meetings.

[.centered]
=== Fifth Month, 1804.

1st. Humbled under some affecting considerations.

4th. I thought the Lord was near us today, known as formerly by the breaking of bread,
to the refreshment of the souls of some of us.

6th. Seasons of renewed favour today at meeting,
so that I could adopt the words of the psalmist,
"`What is man that thou art mindful of him,
and the Son of man that thou visitest him,`" etc.

9th. Went to Guildford on business.
Attended the week-day meeting.
I thought the spring of life lay low,
and my mind not sufficiently divested from the business I had been engaged in,
previously to going to meeting, to dig very deep; so that I gained but little by going.

11th. Renewedly besought deliverance from the bondage of corruption,
that I might indeed witness the glorious liberty of the children of Gad.

17th. Though I have been pretty fully occupied with business the last few days,
my mind hath been favoured with sweet serenity,
having been preserved in a good degree within the divine enclosure.
What a mercy!

19th. Had afresh to acknowledge, with humble gratitude,
that good is the Lord and worthy to be praised, and that by the whole house of Israel.

21st. Attended the first sitting of the yearly meeting,
which I thought was owned by condescending goodness.

30th. I thought the last sitting of the yearly meeting eminently favoured.
We separated under a precious solemn covering, and I believe the humble,
grateful language of many minds was, What shall we render unto thee, O Lord,
for all thy benefits?

[.centered]
=== Sixth Month, 1804.

4th. Came home in health, and found my beloved mother so; for which favour,
with many others lately dispensed, I desire to be humbly thankful.

8th. Went to our monthly meeting at Guildford, which proved, contrary to expectation,
an instructive and strengthening season;
yet I feared some present resembled the sluggard who was desirous of a little more sleep,
and a little more slumber, and folding of the hands to sleep.
O that these may be roused to a sense of their danger, lest they "`beg in harvest,
and have nothing.`"

10th. Saw afresh the necessity of watchfulness and prayer;
and desired that I might dwell within this holy enclosure.

14th. On looking back to my last remark, +++[+++I]
may with thankfulness acknowledge that the petition
of my heart hath been mercifully granted:
having been favoured to keep near the centre of good,
and draw my fresh springs from that sacred source.

15th. Desired to hunger patiently this morning at meeting,
rather than presume to carve for myself;
well knowing it is the Lord`'s prerogative to feed his dependant children: which,
after a time of waiting, he condescended to do,
by handing a little of his soul-satisfying food.

17th. Was favoured to sit under the divine anointing in both meetings.
Inestimable privilege!
How lamentable that any should slight it!

19th. An exercising day to my mind through the +++[+++blessed]
cause suffering from +++[+++the]
unfaithfulness of an aged friend.
Endeavoured to clear myself of him;
but did not do it in the way that appeared most satisfactory to myself,
being discouraged.

22nd. Better tidings from Ireland respecting my poor brother, +++[+++which is a]
cause of thankfulness.
May he prize the mercies of a long-suffering God towards him.

24th. In grateful remembrance of the Lord`'s tender
mercies I can this day renewedly set up my Ebenezer,
and say, "`Hitherto the Lord hath helped me.`"

28th. Received the affecting account of my beloved sister Waring`'s being alarmingly ill.
Thus wave upon wave is permitted to follow us;
yet was favoured to feel my mind in a good degree divinely anchored.
What a mercy!

30th. A rather more favourable account of my beloved sister.
May we be sufficiently thankful.

[.centered]
=== Seventh Month, 1804.

1st. Rather a conflicting season at meeting this morning; the evening +++[+++was]
more lively.

3rd. Our quarterly-meeting.
Tabitha Middleton, Susanna Horne, and Thomas Ashby, appeared acceptably,
as did the two former in the meeting for discipline.
I was enabled to get through the business better than my cowardly heart had anticipated;
yet I well know from whence my help came, for which I felt thankful, and I think humble.

6th. A conflicting day to my poor mind, the monthly meeting appointing me an elder;
which though I had reason to expect,
it having been laid before me many months for my consideration,
yet I did not suppose the appointment would be made,
without giving me an opportunity of expressing my feelings on the subject,
an awful one to me truly.

8th. More quiet and comfortable, though led as into the stripping-room,
where I have renewedly seen my own insufficiency for every good work;
yet my faith and confidence +++[+++is]
a little renewed in the sufficiency of God.

10th. A depressing day to my feelings from various causes,
yet a little relieved by writing to an individual whom I sincerely love;
to warn her of her danger, as I apprehend.

12th. Sadness is still the secret covering of my mind.
May I dwell patiently and humbly under it, that so it may tend to my refinement:
then will all work together for good.

13th. I accompanied Tabitha Middleton to Guildford, an exercising meeting.
She spake of the famine in Samaria,
with the king`'s answer to the poor woman when she cried to him for help: which passage^
footnote:[The text is, "`If the Lord do not help thee, whence shall I help thee?`"]
had repeatedly passed my mind before she stood up.

15th. On a strict scrutiny into the motives for action, +++[+++I]
saw that I had been seeking the honour, or at least the approbation,
of poor finite creatures like myself; rather than the honour which comes from God:
which humbled me,
and led me to crave preservation from every snare of an unwearied enemy.

18th. A fresh scene of trial opened: I was desirous of patiently abiding under it.

19th. More comfortable,
and hoped things might turn out better than we had reason to fear,
so that I could adopt the following lines:

[verse]
____
This day, be bread and peace my lot:
All else beneath the sun,
Thou know`'st if best bestowed or not,
And let thy will be done.
____

20th. Went to meeting with a mind much unencumbered, hoping for a good meeting;
but found I was not to eat the bread of idleness, nor did I desire to do so;
but found strength to wrestle for the blessing which was in a good degree answered:
though I thought an unskilful appearance hurt the meeting.

27th. This last week hath been attended with peculiar difficulties; +++[+++so]
that had we not been surrounded with kind friends
who cheerfully shared with us the trial of the day,
+++[+++I]
know not how we should have got on.

29th. Was enabled through divine assistance to mount
a little above the encumbering cares of this life,
and renew my spiritual strength, this morning in our silent meeting;
which I esteemed a great favour, after so harassing a time.

[.centered]
=== Eighth Month, 1804.

5th. Was favoured sweetly to repose all my cares in Him,
who is the health of my countenance and my God.
In our silent sitting in the evening +++[+++I]
saw that it would not do for the faithful, in this day of deep revolt,
of perplexity and treading down, to dwell as in ceiled houses;
but that each should endeavour to put on strength in the name of the Lord,
to arise and build.

9th. Came to Staines.

12th. A time of wading in the morning meeting, for methought the spring of life lay low;
yet was enabled to petition for myself, and for the wanderers present,
that we might be gathered.
In the evening +++[+++I]
was desirous of keeping my heart with all diligence,
that so my evening sacrifice might find acceptance with the Father of mercies:
which I trust was in a good degree the case.

15th. The monthly meeting, and though a pretty many valuable friends attended,
yet I thought it was not a season of rejoicing.

16th. Was favoured this morning in the weekday meeting,
to draw water out of the reach of the archers.
Inestimable privilege!

19th. Having missed my way, a day of deserved humiliation succeeded:
under which I was favoured, through gracious condescension,
to feel something like forgiveness and reconciliation.

22nd. Although made sensible of my manifold infirmities as a creature,
yet was favoured and refreshed with the lifting up
of the light of the Lord`'s countenance upon me.

26th. Mourned over a fallen sister: yet I trust not in a pharisaical spirit; for I felt,
renewedly felt, that my backslidings had been many, though more concealed.
I thought I could willingly have gone and sat by her in
that state of humiliation which I craved for her;
so that she might witness forgiveness,
and endeavour by her future conduct to wipe away the reproach
she hath brought on friends and the Truth.

30th. A time of sweet solace in the week-day meeting,
a favour I esteemed myself unworthy of.

[.centered]
=== Ninth Month, 1804.

1st. Returned home in health and with a peaceful mind.
May I walk worthy +++[+++of]
such unmerited mercies.

2nd. Sat again with my dear friends in our little silent meeting,
in I think a good degree of humble watchfulness.

11th. Have been confined to my chamber, and mostly to my bed, since my last remark,
by an unexpected attack of fever; yet +++[+++I]
have to acknowledge that I have been mercifully dealt with every way:
not only my bodily sufferings mitigated by every
attention that friendship and kindness could suggest:
but (though in the beginning I was tried with the withdrawings of heavenly love and life,
yet afterwards) I was favoured to find Him whom my soul loveth;
yea I sought him on my bed, and found him near, to my great refreshment.
What an unspeakable mercy to one so unworthy!

12th. Notwithstanding the above recited mercies I
behaved foolishly and airy yesterday evening,
for which I felt deserved reproof, and feel today much in the valley;
a safe though lowly situation: may I keep my abiding here.

16th. Gradually recovering;
but the extreme heat of the weather prevents my gaining strength fast,
and also deters me from venturing to meeting today.
I think it was not for want of inclination,
for it would have been pleasant to sit with my friends.
However through gracious condescension I was favoured with
some access to Him who is not confined to space or time,
in my solitary sitting.

20th. The prospect of the approaching quarterly meeting looks awful to me,
being on a weighty appointment.
I have endeavoured this day to repose my care upon that divine
arm of help which alone can qualify for every good word and work.
May I be preserved in childlike simplicity, having no confidence in the flesh.

23rd. Was favoured to renew my strength and confidence in the all-sufficient Arm of help.

24th. Went to Horsham,
and sat with a committee on the consideration of
suitable friends for the station of elders:
a painful sitting indeed!
I was afraid of darkening counsel by words without knowledge;
but through divine assistance was enabled to stand
firm against what I believed a wrong appointment,
in which I found a degree of sweet peace.

25th. The quarterly meeting, an uncommon distressing season.
I desired, when I took my seat,
to be with the true seed whether in suffering or rejoicing;
and truly the former was the portion of divers, if not of most.
We seemed to be enveloped in a cloud of darkness;
such as I scarcely remember to have felt, till near the close;
when a little light arose into dominion,
and a friend present was enabled to sound forth an alarm,
desiring us to search individually into the cause.
The meeting of business +++[+++was]
also trying, some of the answers to the queries manifesting much defection;
yet no way clearly opening for an appointment,
it was judged safest to leave it to future consideration.

28th. The awful situation of things affected my mind and
raised a petition that we might be spared a little longer,
that the heathen might not triumph over us saying, "`Where is their God.`"

30th. Some doubts and fears, lest I should not so run as to obtain,
encompassed my poor mind, soon after my sitting down at meeting this morning:
when some gracious promises were in great condescension brought livingly to my remembrance,
to the lifting up of my head, and confirming my feeble knees.
Thus bountifully is the Lord dealing with one of the meanest of his creatures.
May I ever live to praise and adore his excellent name.

[.centered]
=== Tenth Month, 1804.

5th. Our monthly meeting at Guildford,
wherein I desired to be preserved from hewing out cisterns for myself,
or resting satisfied with any thing short of partaking of the well-spring of life;
which was renewedly revealed to my waiting soul, to my humble admiration:
and I longed that all present might come, taste and see, for themselves,
how good the Lord is.

7th. Desired that I might be enabled to offer a pure offering this morning,
unmixed with the activity of the creature;
that so it might find acceptance with Him who is perfect in holiness.
The afternoon meeting I thought very dull,
nor did I keep so faithfully on the watch as I ought to have done.

10th. Think I have been favoured to move along the
last three days with a good degree of safety.

11th. It was with me a time of deep wrestling, this morning,
before I could find access to the Fountain of living waters,
after which my soul thirsted; yet, thanks be to the holy name,
my labour was not altogether in vain.

14th. I believe a remnant were favoured to sit under their own vine and fig-tree,
and feed as beside the still waters, this morning at meeting.

17th. My mind under depressing sensations from various causes;
under which I have endeavoured to centre near the only source of good and true consolation.

21st. Desired this morning to sit at Wisdom`'s gate,
and to be found waiting at the posts of her door.
How did my soul long that all present knew the preciousness of pure silent worship,
wherein +++[+++the soul]
breathes forth its wants to it`'s heavenly Creator;
who at seasons is pleased to replenish it abundantly:
forever blessed be his excellent name.
He is not saying to the seed of Jacob, "`Seek ye me in vain.`"

28th. Rather stripping seasons +++[+++in]
both morning and afternoon meetings.
I desired to hunger and thirst patiently.

[.centered]
=== Eleventh Month, 1804.

2nd. This morning unexpectedly dear William Jackson (of Pennsylvania) came,
and attended our monthly meeting.
He appeared acceptably in the meeting for worship;
though he said he believed he might appeal to the feelings
of some present that the well was indeed deep,
desiring we might not be discouraged,
neither content ourselves with a traditional belief of the truths of the gospel.

4th. Dear William Jackson +++[+++is]
still with us, and labouring in gospel love,
to gather the outcasts of Israel into the fold of true rest and peace.

6th. I accompanied William Jackson to Alton.
He had a meeting next morning at eleven o`'clock,
in which he was led in an encouraging line to the true mourners,
and sweetly invited the children present to seek the Lord for themselves, etc.
Not finding himself clear of Guildford,
he returned and had a meeting there on sixth-day afternoon,
in which he was led in a close searching testimony,
endeavouring to rouse the lukewarm to a sense of their danger,
and in persuasive language inviting to follow those things that make for peace.

11th. I thought the morning meeting a preciously favoured season,
both in the silent part of it, and under the lively ministry of William;
who was concerned to have a public meeting in the evening,
particularly desiring the company of the poor, and it was mostly this class +++[+++that]
attended.
I thought him remarkably clothed for this service,
explaining with great clearness the nature of true gospel worship,
and directing the attention of the people to the inward teacher.

12th. Our dear friend left us and went forward for Chichester.
We parted in sweet fellowship, of which I thought myself unworthy to partake.

14th. My mind much tried with various discouragements,
under which I have endeavoured to keep in the stillness,
and feel after that Rock which is an anchor sure and steadfast.
O that my abiding was more constantly here:
then should I not be so often the sport of winds and waves.

15th. Still under depressing feelings:
but I have remembered that man is not to live by bread alone,
but by every word that proceedeth out of the mouth of God.
May I patiently abide every humbling dispensation.

18th. Proving seasons, both morning and afternoon meetings; yet +++[+++I]
was favoured not to let go my hold, though my faith was at a low ebb,
and the prayer of my heart was that I might keep the word of the Lord`'s patience,
that so I might be kept from the hour of temptation.

19th. Sackcloth is still the secret covering of my mind,
although I appear not unto men to fast.

23rd. I think my soul was bowed in deep prostration before the God of my life,
who was graciously pleased to own me in this low estate
by the lifting up of the light of his countenance upon me.
May I walk worthy such unmerited mercy.

25th. A day of heaviness of spirit,
yet a little of the oil was graciously dispensed
to my drooping soul in the morning meeting.
In the afternoon mourning was my portion.

28th. Desirous that the day`'s work may keep pace with the day,
yet encompassed with fears, lest it should fall short.
May the Lord be my refuge in the day of trouble, and then let come what will come.

[.centered]
=== Twelfth Month, 1804.

1st. Still moving heavily on my way; discouragements from within and without; yet +++[+++I]
have not let go my confidence, which I esteem a mercy from the Lord.

2nd. Afflictions still await us.
May they have the designed effect, which effect, which is, doubtless,
to wean us from every earthly dependance,
and incite to seek with more fervency an habitation that hath foundations,
eternal in the heavens.
Ah, may I indeed so run as to obtain this enduring treasure;
for here seems no rest for my wearied soul.

3rd.: Thoroughly dissatisfied with myself,
believing I have not been so watchful as I should have been,
and therefore am deservedly disquieted.

6th. Our monthly meeting at Guildford,
an unusually exercising time to me from several causes.
Paid off a little debt to a beloved nephew and niece.

9th. My head a little lifted above the waves of discouragement,
and my soul for a season arrayed with the garment of praise,
being graciously admitted into the presence of its beloved.

11th. In some degree pressing after the mark for the prize.

12th. Felt somewhat of a draft to retirement, but let trifles put me by,
so that it is probable I missed of an intended good: to my shame I record it.

14th. Renewedly besought deliverance from all evil, for I found the tempter near,
spreading his snares in order to catch my weak mind; but being favoured to see the bait,
I repaired to the Name of the Lord, which thanks be to him,
continues to be a strong tower where indeed there is safety.

18th. Came to Guildford and attended the week-day meeting,
in which I was unexpectedly refreshed after a time of digging.

20th. Not enough circumspect, as I saw by bringing my deeds to the light:
yet I think I love the reproofs of instruction, knowing they are the way to life.

23rd. Desired this day +++[+++that]
the Lord`'s hand would not spare, nor his eye pity,
until he had made me what he would have me to be.
May that which is designed for the sword perish by the sword,
that everything that is not of his right-hand planting may be rooted up.
Oh, can I be fit to overlook others vineyards, when I find so much to do in my own,
so much cause for weeding, digging and pruning: surely there is no time for idleness!

24th. Think I have been enabled to step along in
a good degree of safety the last few days,
though I have not been without my exercises.

30th. Went to Horsham, to attend our quarterly meeting,
where I met with dear William Jackson, George and Mary Stacey, etc.
Brother Kidd and myself took our seats in the meeting of ministers and elders;
an awful time to my mind though much encouragement was handed us,
by the beloved friends above-mentioned.

31st +++[+++as well as the 1st, 2nd, and 3rd of the First Month, 1805]. The quarterly meeting.
The meeting for worship I thought a favoured season.
William Jackson first stood up with these words, "`Prepare to meet thy God,
Israel;`" and a second time with, "`Let God arise; let his enemies be scattered.`"
The meeting for discipline +++[+++was]
trying to my feelings.
Here an appointment took place to visit the monthly
meeting of Chichester which somewhat relieved me.
At the conclusion of the meeting for worship,
William Jackson requested to have another next morning at ten o`'clock;
which proved a strengthening, encouraging season to many minds;
also a sitting in the evening,
in which William was led to speak of the parable of the prodigal son,
enlarging on the latter part of it,
the elder son`'s displeasure at his fathers reception of his poor brother,
and his father`'s reply, "`Thou art ever with me,
and all that I have is thine,`" inferring from hence that the righteous should not repine,
+++[+++and]
that their reward is sure.
Spent the evening pleasantly at William Swan`'s, and next morning, after a sitting,
parted in sweet fellowship.
Notwithstanding these abundant unmerited favours, through unwatchfulness,
I returned with the fear of having incurred condemnation,
instead of the sweet reward of peace.
Thus am I staggering on in this important journey, sometimes making a little progress,
and again halting and stumbling; and have the ground to go over again.
May I be enabled so to run as in the end to obtain;
then will all the trials and perplexities of time appear lighter than vanity,
compared with the joys of God`'s salvation.
