== Chapter 15

[.centered]
=== First Month, 1805.

3rd. On my return home, +++[+++I]
met with a fresh trial, in which I was so involved,
that I reaped but little benefit by going to meeting.

7th. Methought the situation of my mind today at meeting resembled
the valley of Jehoshaphat where the Lord pleads with his people;
yet I think I love to meet him even in the way of his judgments,
for these have ever been mixed with mercy.
"`Bless the Lord`" then "`O my soul, and forget not all his benefits;
who redeemeth thy life from destruction,
who crowneth thee with lovingkindness and tender mercies!`"

10th. Too much of a Martha.

11th. Desired that not only the dross and the tin might be taken away,
but also the reprobate silver; everything specious that is not truly solid and valuable;
for nothing else will find acceptance with perfect purity and goodness.

13th. A little animated to press forward, through the crowd of difficulties that present.

14th. A time of digging today in both meetings, for I thought the spring of life lay low,
and but few present concerned to labour for its arising;
or surely we should have been favoured with more of the bubblings-up thereof.

16th. Yielded foolishly to a temptation,
so that sadness is deservedly the covering of my mind.

17th. Have renewedly experienced that strait indeed is the gate,
and narrow the way which leadeth unto life.
May I be one of the few that are enabled, through divine assistance, to walk therein;
though I often fear I shall miss the glorious recompense of reward,
that awaits the righteous.

20th. My dwelling has been for the last two days,
in a land of drought with but little verdure.

21st. Closely beset by the enemy of all good,
nay I thought he pursued me to the very horns of the altar, where I fled for safety;
but thanks be to the God of my life who rebuked him; so that I could say,
"`Hitherto hath the Lord helped me.`"

23rd. Though I have felt very poor the last two days, so that I have at times said,
"`My leanness,
my leanness!`" yet think I have been preserved in a humble resigned frame of mind,
from a deep sense of my utter unworthiness of divine regard.

25th. I trust the warfare is still measurably maintained, though feebly.

26th. I seemed uncommonly empty and stripped of good in the forepart of the meeting,
under which I desired to wait patiently, rather than worship any device of my own;
besides, I considered my unworthiness to approach perfect purity;
yet in this low estate he condescended to favour with access to his life-giving presence,
and measurably arrayed my poor soul with the garment of praise.

28th. I went to meeting this morning in a quiet frame of mind,
hoping to receive spiritual refreshment, and think I laboured according to +++[+++the]
ability received, yet desertion and poverty was my portion,
so that a sigh and a tear seemed all I had to offer;
which was much the case again this afternoon,
so that I thought my offering was not equal to the
turtle doves and pigeons under the law:
yet believed it safest to obtrude nothing of my own.

[.centered]
=== Second Month, 1805.

1st. It continues to be a winter season with me.
May I patiently endure every turning of the divine hand upon me,
in order to cleanse and purify from every defilement,
for I fear I have not so fully surrendered all that is appointed for destruction,
as may have been required.
What a great work is the soul`'s redemption!
Never did it appear more awful, or more precious.

3rd. Our monthly meeting at Guildford.
In the meeting for worship, my soul travelled as in a wilderness country,
and but little light shone on my path; yet, towards the conclusion,
infinite Goodness opened something like a spring in the desert to my great refreshment,
and consolation.
May he ever have the praise of his own works.

4th. Wrestling seasons +++[+++were]
both +++[+++the]
morning and afternoon meetings; yet my labour was not altogether in vain in the Lord.

6th. Felt something like a little greenness,
so that I was enabled to rejoice in God my Saviour.
Inestimable privilege!
May I sufficiently prize it.

8th. I think I did not eat the bread of idleness today at meeting,
nor do I desire to do it, knowing it is my indispensable duty to labour for it,
and that it is well worth all our pains when favoured to partake of it.
And the secret petition of my heart was, that the food most convenient for us,
might be dispensed to each individual present.

11th. Went to Chichester in company with Morris Birkbeck, brother Kidd,
and Elizabeth Moline,
by appointment from the quarterly-meeting to visit that monthly meeting,
where we found things mournfully low, the work resting on an individual or two,
with whom we nearly sympathized, yet could see no way to relieve them.
I stayed the remainder of the week with my kind friends James and Sarah Hack, pleasantly,
+++[+++and]
attended their week-day and first-day meetings,
which were rather laborious seasons to my feeble mind, yet not uninstructive.

18th. Felt weak and poor every way, being considerably indisposed in body.

20th. Returned home, found my beloved mother in good health, which I esteem a favour.

22nd. Our little week-day meeting proved a sweetly solacing season;
in which my faith and confidence in the divine all-sufficiency were renewed.

24th. A time of searching of heart this morning at meeting,
in which I endeavoured to bring my deeds to the light,
to see whether they were such as would find acceptance in the divine sight.
Stayed at home in the afternoon from indisposition.

26th. Felt something of a godly jealousy over myself,
fearing the day`'s work had not kept pace with the day.
Sorrowful indeed would it be, if I should be found without oil in my lamp,
when the midnight cry is sounded within my borders.

[.centered]
=== Third Month, 1805.

1st. Our select meeting this evening; we had the company of dear Sarah Hack,
who handed forth a little encouragement to my feeble mind.

2nd. Our monthly meeting.
I did not attend the meeting for worship, not feeling sufficient strength to attend both.
I was enabled to get through the business better than I expected +++[+++the clerk being
absent]. At this meeting my beloved Sibylla Turnour was received into membership.

4th. Was renewedly desirous of being enabled to fight the good fight, and keep the faith;
that so in the end I may obtain the crown; but remember, O my soul,
that if thou wouldest reign with Christ, thou must also be willing to suffer with him.
Thou must drink of the cup that he drank of for thy sake,
and be baptized with the baptism that he was baptized with.
Canst thou say, with the disciples, that thou art able?
Alas! poor and frail am I,
sensible that I cannot take one step aright without his divine aid.

5th. Have lamented my proneness to centre in visible things,
and my want of fervency of spirit Godward.

6th. Was enabled this morning to draw near to the Fountain and Source of all good,
whereby my spiritual strength was measurably renewed.

11th. "`I remember thee, +++[+++the kindness of thy youth]
and the love of thine espousals,`" etc. was brought with
some degree of freshness into my mind this morning;
and I also remembered the day of precious visitation;
when the Lord in gracious condescension allured my desires after him,
when he took me as to his banqueting house.
His fruit was indeed sweet to my taste, and his banner over me was love;
and though I trust he is still to my heart the "`chiefest amongst ten thousand,`"
yet how often have my hands been weakened by turning aside to follow lying vanities;
or else I believe I should by this time have witnessed
a more complete victory over my souls enemies.

Sixth-day.
Methought my vessel was a little replenished with heavenly oil in our silent meeting.
A favour I esteemed myself unworthy of.
