== Preface

Not many compilations, similar to that presented to the reader in the following pages,
have been of late, if ever, published in our religious Society.
Various excellent and interesting journals have indeed from time to time been printed,
and have met with much acceptance.
These generally consist of two distinct, and well-marked divisions.
The first relates, for the most part, the author`'s early visitations,
his baptismal conflicts, the dangers into which he has fallen,
and the deliverances which he has experienced.
This, though commonly the smaller part,
is often fraught with ample stores of instruction and encouragement;
for as not any work is comparable to the work of Christian redemption; so,
next to the experience of its progress in ourselves,
it is interesting to observe it in others.
It is strengthening to those who are setting out in earnest in the Christian`'s path;
and animating to such as have already made advances in it.

The other part usually informs us of the course which the Christian soldier,
already in good measure trained, has been led in following the Captain of his salvation;
and as these journals are generally those of friends eminent for public services,
this part has much to keep up our attention by its variety,
and to excite our admiration by the magnitude of the services performed.
Here too, sometimes, the depth of the baptism, and the strength of the holy arm,
which carries through it the humble and devoted servant of the Lord,
are conspicuously detailed.

But this diary, though tending to the same purpose, the exaltation of the name of Christ,
our Redeemer, and the encouragement of his humble followers (who,
feeling no might of their own, are glad of the least touch of his assisting hand,
and rejoice in ascribing to him all the praise),
pursues a course sometimes varying from the journals which have been hinted at.
It is indeed that of a private, and with respect to the Society at large,
even in England, almost an obscure individual.
It does not relate her religious exercises in youth;
for it begins with her thirty-first year,
and at a time when most who knew her would probably
think her a fixed character on the side of religion,
and one whose foundations were already well laid on the rock.
As it goes on,
it relates little more than the regular attention
to what are called common and daily duties.
And it is for this very reason, probably,
adapted to the generality of readers in private life;
if they be but such as think it important to attend
daily to the concerns of their immortal part;
and to take, amidst the variety of scenes in which they are engaged,
some time to consider whether their habits,
dispositions and practices are pleasing to God.

To those who neglect this important inquiry, what can be said; what can be written?

Some persons who take up this volume may think that the
frequently repeated relations of experiences nearly similar,
are tedious to be read;
but it may be doubted whether such critics will be found among the hungry souls,
or the abased ones.
These will probably recollect that,
in like manner as the needs of the body recur from the same existing cause,
and are relieved by similar means; the general needs of the soul also,
arising from the operation of causes which are long permanent,
will continue to require a supply of the same remedies.
These also will be likely to perceive that even in
the sameness of the feelings of the writer,
there is a life which not only prevents satiety,
but which diffuses animation over her soliloquies:
in which may be discovered the humble perseverance of a quickened mind,
and abundant glimpses of the unfailing care of the
Head of the church over his suppliant servants.

There is one remarkable particular in this diary,
at which it may be worth while at little to hint, namely the numerous instances,
where good meetings are spoken of, meetings where truth was in dominion.
Some will be likely to question the ability of the relator to judge of this;
will confine these feelings to her own well prepared mind,
and thus may discourage themselves from expecting to find,
in their retirements in spirit, what she found in her lowly waiting upon the Lord.

It is certainly not easy for one man to judge of the mental feelings, industry, or sloth,
of another (and this on the other hand should always make us cautious
of supposing that others do not feel the good which we feel);
nevertheless it is quite consistent with our principles to believe
that a sense may be given to the attentively waiting mind,
of the spiritual situation of its companions.
But be it even as such may be induced to suppose;
is it not still a great encouragement to seek after that state of true hunger and thirst,
which has a quick relish of the least degree of spiritual sustenance;
and to bear with persevering patience those seasons of spiritual poverty,
which excite us to seek aright?
"`Blessed are they who hunger and thirst after righteousness; for they shall be filled.`"
"`Blessed,`" (also,
as the same evangelist relates our Lord to have said
just before)--"`blessed are the poor in spirit,
for theirs is the kingdom of heaven.`"

Another prominent feature in the subsequent pages,
is the frequency of the author`'s private retirements;
which may possibly induce others to seek the same means of consolation and instruction,
which seem to have been singularly blessed to her.
There is reason to believe that retirement is one mode pointed out by the good Shepherd,
to wean tenderly visited persons from associates who would
impede their advancement in the way of the cross;
and to induce them to let their affections centre in spiritual gratifications,
and permanent treasures:
and much is it to be desired that such as at times
feel the gentle attractions of heavenly love,
thus "`to sit alone, and keep silence,`" would yield to the salutary intimation.
They would surely thus experience the Lord to be strength in weakness,
a needful supply in times of want, a safe conductor in the path to salvation.

It is hoped that,
among the various descriptions of readers into whose hands these sheets may fall,
the newly-awakened may derive encouragement to yield up their wills
in simple obedience to the requirings of the Lord,
by observing how much is here exemplified that description of the ways of wisdom,
"`Her ways are ways of pleasantness, and all her paths are peace.`"
And the deliverances from temptation, the consolations in affliction,
and the support in trials and difficulties, here recorded,
may animate the more experienced traveller still to hold on his way,
trusting to the Lord alone, to nothing short of the arm of Omnipotence.
For though the writer appears often to have had a more ready access to the healing waters,
than many think themselves to have attained,
yet she was often deeply humbled under a sense of her infirmities, and unworthiness;
taught that in the presence of the Lord no flesh can glory;
and that He alone is able to begin, to carry on, and finally to accomplish his own work.

Of probably the most valuable part of Mary Waring`'s life,
the diary itself is an accurate account so far as it goes;
and it goes to make the reader acquainted with the inward recesses of her mind.
Of her birth, her youth, her general habits, and of her closing moments,
let maternal love declare, as follows:

[.embedded-content-document.testimony]
--

My beloved daughter Mary Waring was born the 20th of Third Month, 1760.
From a child, she was of an amiable disposition;
but being naturally of a very lively turn, she appeared fond of company,
and discovered some inclination for gaiety;
though far short of several of her intimate acquaintance;
and more readily submitted to parental authority and advice than most.

About the 27th year of her age (according to her own account,
in a little narrative which she wrote of her spiritual progress)
she was favoured with a precious and humbling visitation,
which she readily and happily assented to,
and became circumspectly concerned to fill up the religious,
and other duties called for at her hands.
For though she was not placed in an eminent station,
either in the church or in the world, yet as far as her circumscribed abilities extended,
she discovered the excellency of the Christian character:--in filial duty,
in sisterly affection, in tender love to her friends,
and in a desire to be helpful to all around her.
To attend the chamber of sickness, and, by every endearing consolation in her power,
to smooth the bed of death, appeared to be her peculiar province.
Nor were these duties confined to her relatives and friends;
but she sought out the wretched abodes of poverty, sickness, and distress;
and administered advice, comfort, and substantial relief.
And where her own ability was inadequate to supply their necessities,
she advocated their cause with the more affluent, in which she seldom failed of success;
so that I have sometimes been ready to say with Job, "`When the eye saw her,
then it blessed her; and when the ear heard her, it gave testimony to her.`"

She was a secret mourner for the desolations which appear in our Zion;
and I believe faithfully discharged her duty as an overseer.
Her diligence in attending meetings was exemplary; and her solid sitting therein,
often under the tendering influence of Divine love,
was helpful and encouraging to others;
and her vacant seat is sincerely regretted by her friends,
who were feelingly united to her, and have, several of them,
emphatically expressed not only their own loss, but also their tender sympathy with me,
under the very close trial I have sustained in my
declining years:--to lose such an affectionate child,
who had been for a number of years my endeared companion, my ready assistant,
and true sympathizer under various afflictive dispensations
which it has been my allotment to pass through.
But, although nature was ready to shrink from the bitter cup, yes,
at seasons to sink under it, yet in a firm belief that her day`'s work was done,
and her redemption sealed,
I have at times been favoured to feel a degree of humble resignation,
and to bless the holy hand that both gave, and has taken away;
attended with a secret animating hope,
that I may before long be mercifully permitted to rejoin her spirit
in the peaceful abodes of unalloyed harmony and bliss.

She had for a considerable time been in a debilitated state,
but there appeared no alarming symptoms till about the middle of the Third Month, 1805,
when her complaints increasing,
myself and her other friends became very anxious about her,
and we prevailed on her to go over to Staines, and consult her brother William Tothill.^
footnote:[A medical man.]
She set out, accompanied by her brother Kidd, on First-day morn,
taking a most affectionate farewell of me,
though I believe we neither of us believed it would be the last embrace;
but so it proved.
For though the medicines seemed to take the desired effect,
and on the following Sixth-day, she appeared rather better, had walked in the garden,
and next morning spoke cheerfully to her friend Sybilla Turnour^
footnote:[See Third Month, 1805.]
(who had kindly gone over to see her, and lodged with her); yet,
as her friend was getting up,
she thought she heard her make an uncommon noise in her throat, ran to her,
and called her brother, who came immediately, and had just raised her in his arms, when,
alas! she breathed her last in the easiest and quietest manner, without one struggle.

Her remains were brought to Godalming,
and solemnly interred in our burying ground the 30th of Third month, 1805,
attended by a respectful number of her friends and neighbours: aged forty-five years.

And now, that her beloved nephews and nieces, who revered her living,
and lamented her dead,
and for whose welfare in the most important concern she was earnestly exercised,
may remember the advice she has bestowed on them,
and the example she has set them of submitting to the cross; that, like her,
they may become useful in their lives, and close their days in perfect peace,
is the ardent desire of

[.signed-section-signature]
Sarah Waring

--
