== Chapter 5

[.centered]
=== First Month, 1795.

1st. And now, O my soul,
may you begin this year with renewed dedication of heart to the Lord`'s service.
I desire so to do.
Strengthen my feeble endeavours, O Lord, if it be your will.

9th. A precious season this morning in our little silent gathering,
my soul was prostrated before the Lord in deep reverence and thankfulness that he should
deign to lift up the light of his glorious countenance upon one so unworthy.

13th. Have been favoured at times to commune with my own heart and be still.
By this means we are favoured by the light of truth
to see what need we have of a merciful Redeemer.

15th. Not spent idly as to action, but gave way to vain and roving thoughts,
for which I deservedly feel condemnation.

18th. A precious season this morning at meeting,
I was favoured to feel something of the seal of adoption on my spirit,
for which unmerited mercy, all within me magnified the name of the Lord,
who lives and abides forever.

22nd. My apprehensions afresh awakened on my dear father`'s account;
a poor account also of a dear sister who is confined with a fever;
and what increases my distress is, I cannot leave my dear father, to go and see her.

27th. The cares and perplexities of this world have too much occupied my mind,
some of which I fear I have not borne with that patience
and submission I ought to have done;
yet think I have laboured after this attainment.

30th. A good account of my dear sister.

[.centered]
=== Second Month, 1795.

2nd. A thoroughly busy day, leaving the mind but little leisure for spiritual improvement.

6th. A precious season this morning in our little silent week-day meeting.
O, that our lukewarm professors would but come, taste, and see for themselves,
"`that the Lord is good:`" surely they would not be negligent
in the attendance of these religious opportunities.

11th. Have been confined these several days by indisposition.
I felt poor and weak every way, yet in a pretty quiet frame of mind.

12th. Have this morning waited at Wisdom`'s gate,
where I have been renewedly instructed and shown
my own insufficiency for every good word and work.
I love to be thus emptied and stripped of every filthy rag of self-righteousness,
and to feel the Lord reign whose right it is, and who is alone worthy of all praise,
dominion, and majesty.

20th. Favoured to feel the best of teachers near
this morning in our little silent week-day meeting;
dispensing the bread of life to the hungry soul.

21st. Too impatient with my dear father today.
O, for an increase of this excellent virtue;
which enables to bear all things with meekness.

[.centered]
=== Third Month, 1795.

1st. I thought my mind resembled the barren heath
or wilderness when I sat down in meeting today;
neither dew nor fields of offering:
yet was the Lord graciously pleased to bestow both
these divine blessings after waiting awhile,
to him be the praise who is alone worthy.

5th. My close attention to my dear father, and frequent visits to the sick,
joined to family concerns, has not left me much time for religious retirement this week,
yet I have believed I was in the way of my duty.

6th. Went to monthly-meeting this morning under much depression
of mind (occasioned by my dear father`'s and uncle Kidd`'s illness),
where my strength and confidence in the Lord was renewed,
and I was in a good degree enabled to say "`Your will be done.`"

8th. A precious heart-tendering season at meeting today,
though no ministering friend present;
I thought the minister of the sanctuary was known among us by the breaking of bread.

11th. These several days too much occupied with outward things,
so that the better part has not been improved as much as it probably might,
had I been more retired in my mind.

13th. My soul thirsted this morning for the living God,
who in great condescension appeared to my comfort and refreshment,
may I walk more worthy such unmerited favours.

15th. Though tried with a roving disposition when I first sat down at meeting this morning,
yet the Lord was pleased to bless my feeble endeavours to maintain the warfare,
and graciously to lift up the light of his glorious countenance upon me, and,
removing the spirit of heaviness, to give me the garment of praise.

21st. This week has been pretty fully occupied in close attention to my dear father,
who has been and continues very ill.

22nd. My dear father better; cause of thankfulness.
When I sat down in meeting this morning I thought
I felt the hovering wing of ancient Goodness,
but getting off my watch I lost ground,
and was left for a while in a dry and barren spot.
Yet I was desirous that I might not be tempted in the absence of
my spiritual Moses to make to myself a calf and worship it,
as the Israelites did formerly,
and He who saw the sincerity of my heart was pleased
to appear again with healing under his wings.
O, may I be enabled to make a suitable return for such unmerited goodness and mercy.

27th. Favoured with a little of the brook by the way,
in my solitary sitting this morning in my chamber.

29th. Was led this morning at meeting to number my blessings, and to acknowledge,
in the depth of humility,
my utter unworthiness of the manifold kindness and condescension of the Lord towards me;
and also to crave a continuance of his fatherly care and providence over me,
well knowing, from a fresh feeling thereof, that he was the centre of all good.

31st. My dear father seized with epilepsy,
so that for many hours we had not the least expectation of his recovery.
In this season of sore conflict I found it necessary to retreat to the Rock of my strength,
and had not he graciously sustained me, surely I had fainted,
but in his accustomed goodness he was pleased to walk on the sea, and command a calm,
so that my poor mind was brought into great quietness,
and could in a good degree adopt the language of "`Your will and not mine be done.`"

[.centered]
=== Fourth Month, 1795.

2nd. My dear father worse again; he has been delirious all night, and still remains so:
so that there is fresh need to apply for renewal
of strength and resignation to the divine will.

3rd. Felt the hovering wing of ancient Goodness as
I sat by my dear father`'s bedside today;
and was comforted in believing he was made a partaker of the blessing.

6th. Went to Guildford to attend the quarterly meeting,
beset with many fears lest I should not be able to go through the business.
The meeting for worship I thought a low season,
but was helped in the meeting for discipline to get
through the business to tolerable satisfaction;
to the Lord be the praise,
to whom my soul bows in humble gratitude for all his mercies both ancient and new.

9th. The two last days taken up with company,
etc. yet when in company my soul has at seasons flown to the ark of its rest,
finding none in anything short of the divine excellency.

26th. Though I sat down at meeting this morning in much poverty,
yet through the goodness of the Shepherd of Israel my little store was increased,
and my soul satisfied with his living presence.
Unspeakable favour!

28th. My mind sweetly encouraged and animated to press forward towards the mark,
by reading the account of my dear aunt Townsend`'s last journey into Scotland.
The perfect dedication of heart that appears, is comfortable,
as well as her peaceful close.
May I so walk that my latter end may be like hers.

30th. Had to feel and lament my natural proneness to evil.
Surely, I often think, none is more so, so that unless the Lord,
who hitherto has preserved me (blessed forever be his name!)
be still graciously pleased to watch over me,
I shall yet, I fear, fall by the way: I love to feel my dependance,
and from where my help comes.

[.centered]
=== Fifth Month, 1795.

3rd. Stayed at home with my father in the morning.
In the afternoon laboured according to my ability; when, after a while,
the stone was rolled from the well`'s mouth,
and my thirsty soul refreshed with living water.
Others also I believe were partakers with me in this unmerited blessing.

8th. Under much depression on account of a fresh scene of trial.
O, that He, who has seen it fitting to afflict,
may be pleased to sustain through this trying dispensation.

9th. My mind sweetly encouraged this morning at meeting with a renewed evidence,
that though the Lord afflicts he has not forsaken.
Forever blessed be his holy name.

11th. A time of close inward exercise this morning, at meeting;
was desirous I might not get from under it, or off my watch,
which I was enabled to maintain till the meeting broke up.

15th. Humbled deeply under a sense of some failures;
yet was desirous of abiding under the purifying hand,
that the wound might not be healed deceitfully.

21st. These several days have been fully taken up
with company and attending my dear father;
who has had another alarming seizure.

24th. A time of sweet solace in my solitary sitting in my father`'s chamber;
while the family was at meeting this morning.

27th. A time of much anxiety, my dear father continuing in a very tried situation;
I laboured, though I fear but feebly, after a thorough resignation to the divine will.

[.centered]
=== Sixth Month, 1795.

4th. More comfortable and quiet, for which favour I think I have been truly glad.

5th. I sat down in great weakness this morning at meeting, but after waiting patiently,
the Lord was graciously pleased to arise: then were his enemies scattered,
and my soul permitted to enjoy divine communion with him,
whom I desire to love better than riches or length of days.

7th. I found the adversary busy today at meeting in endeavouring
to draw my attention from its proper centre;
but received strength to overcome his stratagem,
and was enabled to draw water out of his reach.
Forever blessed and praised be Israel`'s Shepherd:
who leads and feeds his dependant children, yes, the least and meanest of his flock.

11th. A quiet and comfortable day.

12th. Several calling in, I was too light in conversation;
in other respects a day not ill spent.

18th. My mind affected,
on hearing of the deviation of several who stood in the foremost rank,
and ought to have been as waymarks.
Surely it is enough to make one of the hindermost of the flock tremble,
when the standard-bearers faint and give way.
Double your watch therefore my soul, lest you also fall a prey to the devourer.
A sweet contriting season in my chamber in the evening.

19th. I think I did my best today at meeting; but thought it a low season,
to which bodily indisposition contributed.

21st. Discharged an apprehended duty, in writing to a friend,
who I believe is straying wide from the true fold.

25th. Think I have been enabled to step along in safety these few last days,
having frequently felt my good guide near.

26th. Though our meeting was silent today (as is often the case),
yet I thought it was good to be there, and could say,
Better is an hour spent in your courts than a thousand elsewhere.

27th. Discharged my duty today as an overseer,
in giving an affectionate caution to a young woman of whom I had heard a painful circumstance;
which she resented highly.
However, I was favoured to feel tolerably peaceful under it,
believing I had not moved in it in my own will.

28th. My mind strengthened in the belief that I had acted
in the above-mentioned affair as became my station,
though it met with so unfriendly a reception.
I was desirous of keeping quiet under it,
and of being preserved from harbouring any resentment, yet keeping firm,
as the cause was not my own, and worth suffering for.

[.centered]
=== Seventh Month, 1795.

2nd. Have dwelt much in the valley these few days,
yet have cause to believe the blessing has rested upon me in my lowly situation,
so that the language of my soul has been, Return to your rest,
for the Lord has dealt bountifully with you.

5th. Went to Wandsworth to attend the quarterly meeting.

6th. The meeting today I thought unusually favoured,
a divine visitation seemed afresh extended to the backsliders in our Israel.
My soul was deeply bowed under a sense thereof.
Oh! the condescending goodness of Infinite Wisdom towards the workmanship of his hands;
the meanest of which I often conclude myself.
Many strangers attended, among them Sarah Harrison and Sarah Birkbeck.
Returned home humble and peaceful.
Found my dear father as well as I left him.
"`What shall I render to the Lord for all his benefits?`"

7th. I fear I have not felt sufficiently grateful today for the favour conferred yesterday.

12th. Stayed at home in the morning with my dear father; went to our afternoon meeting,
where after some close labour I was graciously favoured
with access to the throne of grace;
when my mind was unexpectedly drawn to supplicate for my dear father,
that the Lord would be pleased to sustain him in the solemn hour of death,
whenever permitted, and finally admit him to the mansions of eternal felicity.

13th. My dear father seized this morning with another epileptic attack.

17th. My dear father again better though low.

23rd. This has been hitherto a very trying week,
which I have sometimes borne with a good degree of patience and resignation;
at others not so much so, as I should have done; poor nature being overcharged:
yet I desire to labour after it, and that no repining thought may find room in my heart.

24th. Saw in the light to which I desired to bring my deeds this morning at meeting,
that I had acted disingenuously in a circumstance that had occurred in the morning;
though the motive that induced me was to spare another pain,
yet I am not sure that it was justifiable.
However, notwithstanding this failure, I was graciously admitted to the mercy-seat,
where the sceptre of love was stretched forth.

26th. Sat down at meeting this morning, uncommonly encompassed with infirmity,
having given way too much to unprofitable thoughts;
yet being enabled to press through the crowd,
and touch the hem of the garment which communicates healing virtue,
I found it as infallible as ever, to my comfort and thankfulness.

31st. Sat the forepart of the meeting in a desert
land where I could discern no path for my feet;
but after waiting a while, light was graciously vouchsafed, and,
the spirit of heaviness being removed, my soul became arrayed with the garment of praise.
Yet even in this state I found the enemy near with evil suggestions,
but keeping my eye single, I think he gained no advantage over me.

[.centered]
=== Eighth Month, 1795.

6th. Went with Elizabeth Moline, by appointment of the monthly meeting,
to read the yearly meeting`'s epistles in those friends`'
families who do not attend meetings for discipline.
We were enabled to give, I trust, a little suitable counsel on the occasion.

12th. Fully dissatisfied with myself, and had to exclaim with one formerly,
"`The heart is deceitful above all things:`" under
a humbling sense of which I was deeply contrited,
and begged for an increase of strength and wisdom.

14th. Had much rubbish to dig through this morning at meeting,
before I could get to the pure spring,
yet I had to acknowledge it was well worth my pains;
and that I was an unworthy partaker of such an inestimable blessing.

19th. Renewedly desirous this morning of doubling the watch,
that nothing may be permitted to enter and defile the temple,
which the Holy Lord God is at times graciously pleased to visit.

21st. Was afraid I had done wrong this evening in omitting an apprehended duty,
giving way to creaturely reasoning and fear.

24th. My mind sweet and peaceful under some disquieting circumstances.

[.centered]
=== Ninth Month, 1795.

1st. These several days pretty fully take up with my beloved father,
who had another alarming seizure: under which trial I have felt, as heretofore,
divine support near to sustain.

2nd. An unexpected sweet little opportunity today in my dear father`'s chamber:
in which George Dillwyn had to express his belief that the hope my father
entertained of his future wellbeing would never be permitted to perish.
In a sweet and encouraging manner he enlarged a little on the duty
and advantage of full resignation to the divine will.
He had a public meeting this morning, which was to my apprehension a favoured season.
I spent the rest of the day in sweet society.

4th. Our monthly meeting.
In the silent part of the meeting for worship,
my spirit sweetly tendered under the consideration of the many favours vouchsafed.
George Dillwyn appeared acceptably in testimony.
Went in the evening to Wanborough with some friends, where I spent the day with them,
I trust, in innocent cheerfulness.

6th. Went this morning to Arundel with Morris Birkbeck, Jr.
and the aforesaid friends, where we met with many friends assembled,
and I think it was a season of renewed favour.
George Dillwyn appeared in testimony and supplication.
After meeting I parted with my friends, and returned home in the evening.

8th. A fatiguing day,
yet found a little leisure in the evening to retire to the fountain of sure mercies,
where my spirit was sweetly contrited,
and refreshed under the fresh feeling of the extension of divine regard.

13th. A precious little season in my dear father`'s chamber,
while the family was at meeting this morning.

16th. These last few days spent well as to action, except some little impatience;
but I have too much given way to unprofitable thoughts,
so that at times I have deeply mourned my instability;
yet have again relapsed into the same disposition.
Again I have sought after that Word which makes clean, and though so unworthy,
have felt it to purify my vessel.
I make this remark by no means boastingly, but to show the lovingkindness of the Lord,
who wills our sanctification.

24th. Rather a bustling day.
Retired in the evening to Wisdom`'s gate, where I sat in much poverty and weakness,
and was afresh convinced that nothing short of the key of
David could give access to the fountain of life.

27th. The enemy, ever busy to betray, drew me off my watch today at meeting;
so that I sustained loss, which I lamented.

[.centered]
=== Tenth Month, 1795.

1st. The recollection of some weaknesses accompanied
my mind in looking over yesterday and today;
but at times I have felt the secret touches of my
heavenly Father`'s love in which I had to rejoice.

2nd. Was favoured to sit under the Lord`'s teaching
this morning in our little silent week-day meeting;
for which blessing I desire to improve.
The rest of the day fatiguing, and attended with a painful circumstance to my mind,
to see youth trained up in the way they should not go; and too wise in their own eyes,
to receive instruction from those who have had more experience.

4th. Went to Esher to our quarterly meeting,
but was too ill to attend either of the sittings.

9th. Much better.
A little renewal of strength this morning in my sitting in my father`'s chamber.

14th. Had fresh occasion to lament my proneness to evil,
and to see the subtlety of self-love,
how it creeps into the most trifling actions of our lives.

16th. A sweet contriting and instructive season in our little silent week-day meeting.
Gave way to impatience in the night with my dear father, which cost me some tears,
and I earnestly besought an increase of strength proportioned to the trial of the day.

20th. Renewedly desirous of rising above the weakness of nature,
and that I may know every thought and desire brought into subjection,
and under the government of the Prince of Peace.

23rd. Gave way to anger on a trifling occasion, for which I feel condemnation;
nor has the rest of the day been so much improved as it might have been.

25th. Rather low times both morning and afternoon meetings.
Mary Stacey had a strengthening opportunity, to my mind at least,
in our family in the evening.

29th. My time has been so much taken up this week with company,
attending on my dear father,
etc. as to afford but little opportunity for religious improvement;
yet I think I have been enabled to step along with a good degree of circumspection.

30th. This morning`'s meeting a season to be remembered,
for the fresh descending of heavenly dew;
under which precious influence my soul was secretly and unexpectedly
drawn forth to petition the Lord on my beloved father`'s account,
that he might be his in the day that he made up his jewels;
and the sweetness which accompanied my mind gave
me reason to hope my prayer would be answered.
It is with a heart replete with gratitude that I
thus commemorate the gracious dealings of the Lord.

[.centered]
=== Eleventh Month, 1795.

6th. My beloved father again seized with epilepsy.

8th. My strength and confidence a little renewed this morning at meeting,
which I esteem an inestimable favour.
My dear father gradually recovering.

12th. Have had but little opportunity for religious retirement these few days past;
and when I have found and embraced it,
I have thought my mind much resembled nature as to the outward, a winter season.
I could find but little verdure, or pleasant fruit;
yet at other times have felt the restricting power of truth near,
which has drawn my mind into peaceful quiet;, which I esteem a favour.

15th. A roving lukewarm disposition too much prevailed in the early part of the meeting;
but the good Shepherd graciously condescended to stretch forth the crook of his love,
and gently draw me towards him.
He was in abundant mercy pleased to animate my faith,
by afresh disclosing the beauty and excellent order of the new creation;
with what perfect harmony every duty might be fulfilled,
did we dwell enough under the pure principle of truth; no clashing,
no interfering one with another, but each performed in its allotted season.
Then indeed should we know Jerusalem to be a quiet habitation and a safe hiding-place.

20th. Was favoured to lie down as beside the still waters
this morning in our little silent weekday meeting.
How unworthy, I must still repeat it,
of such a blessing! the rest of the week I fear not much improved,
yet in reviewing it I do not feel much condemnation.

27th. This week has been so fully occupied in attending my dear father,
working for the poor, and visiting the sick,
as to allow scarcely time for religious retirement;
yet I have believed from the peaceful state of my
mind that I have been in my proper allotment.
Should these remarks ever meet any eye but my own,
I hope the reader will not think that they are mentioned as anything meritorious.
Far be it from me! well knowing how very imperfectly I fill up my various duties;
and that the best of us are but unprofitable servants.

[.centered]
=== Twelfth Month, 1795.

6th. Favoured with near access to the throne of grace this morning in our silent meeting.
When thus permitted to ascend the mount,
how are we like Peter wishing to tabernacle there,
unwilling to return again to the earth; but remember, O my soul,
this is not your resting place,
and that the full fruition of the crown is reserved for those who hold out to the end.
Let the foretaste of it animate you to press forward, that you may so run as to obtain.

12th. The duties of this week, I trust, in a good degree fulfilled.
On a strict scrutiny I do not feel anything condemn me; but some little impatience.

17th. When I awoke this morning I found my mind drawn into sweet quiet.
I was soon after summoned to my dear father, who was seized with another attack,
which was very severe indeed:
under which fresh trial I was preserved in a good degree of calm resignation,
and was thankful that my mind had been prepared.

20th. Attended the general meeting at Guildford; which, though unusually small,
was owned by Him who is the crown thereof.
To him be the praise ascribed, who is alone worthy.

27th. A favoured season this morning at meeting, though no outward ministry.
Yet those who centred to the gift in themselves were favoured to know a teacher,
that cannot be removed into a corner.
Blessed privilege!

31st. This week has I think altogether been spent in the service of others hitherto.
I have had but little leisure for religious retirement, yet trust I have been in my place.
