== Chapter 8

=== First Month, 1798.

1st. Attended our quarterly-meeting at Dorking,
where my poor mind laboured under so much discouragement
that I did not seem in a capacity to receive good if offered;
but it appeared to me a low time every way, though there was no lack of words.

3rd. Still moving on under much depression,
and at times my poor mind seems so overcharged that
I think my bodily health will sink under it.

4th. A little revived today, having been enabled to lean on my heavenly anchor,
who can alone command the winds and the waves, and they obey Him.

5th. Our monthly-meeting; in which my confidence in the Lord was sweetly renewed.

12th. This week has passed quietly: I have measurably borne the cross,
in which I have found peace.
A season of refreshment today in our little silent week-day meeting.

19th. I sat down in much weakness today at meeting; yet after labouring a while,
was graciously permitted access to the fountain of living waters,
whereby my soul was sweetly replenished and encouraged to press forward,
through the many hindering things which surround my path.

26th. Met, previously to going to meeting,
with some vexatious occurrences which too much encumbered my mind,
so that it was a long time before I could rise above it;
yet before the meeting concluded I was enabled to mourn over my weaknesses,
and seek help where alone it is to be obtained.

=== Second Month, 1798.

2nd. I believe there were today a few rightly gathered in the name and power of Jesus,
who was graciously pleased to fulfill his promise of presiding among us.
Blessed privilege!
How lamentable that any should slight it, and be content to feed on husks!

15th. My mind having been much outward these several days past,
I sat down at meeting in much strippedness,
scarcely expecting to be favoured with the overshadowing wing,
which however was graciously extended to my humbling admiration;
and my soul was led to recount the Lord`'s mercies,
and enabled to offer the sacrifice of praise.
O may I walk worthy of such unmerited favours.

23rd. Attended the meeting at the Workhouse +++[+++Clerkenwell, London],
where George Dillwyn and William Savery were,
and both appeared acceptably in their ministry;
but though favoured with the company of such eminently gifted instruments,
if the best of ministers^
footnote:[See Heb. 8 2. "`A minister of the sanctuary,
and of the true tabernacle which the Lord pitched, and not man.`"]
had not graciously presided among us, it would not have satisfied the minds of some:
which was mercifully the case.

=== Third Month, 1798.

1st. Returned again to our peaceful habitation in health, not only bodily,
but I humbly trust through divine preservation in a good degree of spiritual freshness;
having often of late felt the sweet descendings of heavenly love,
which I have been led to believe was the gracious reward of some little acts of faithfulness.
Thus bountifully does the Lord deal with the meanest of his works.

13th. Went to Guildford to see a poor friend near her close; who,
though in a suffering state as to body, yet seemed calm and resigned.
I was at the week-day meeting, which I had no cause to repent,
seeing the necessity of embracing every opportunity of renewing my spiritual strength,
by retiring often to the fountain and source of all good.

22nd. This week has been pretty fully engaged with the company of dear brother and sisters;
yet, though surrounded with temporal blessings as on every hand,
I have been thankful to feel my happiness incomplete unless crowned
with that best of blessings which brings no sorrow with it,
and which can alone sanctify every dispensation of a bountiful Providence.

29th. Quarterly meeting at Alton.
I thought it a favoured season, feeling Him to preside among us,
who remains the crown of our religious assemblies.
We had a comfortable sitting in the evening,
in which Thomas Scattergood appeared pretty largely in supplication and testimony,
and was drawn forth in much gospel love to encourage a state
present which seemed sinking under conflict and discouragement.

=== Fourth Month, 1798.

2nd. Our quarterly meeting at Guildford.
Thomas Scattergood appeared largely in the meeting for worship,
indeed he laboured abundantly in much gospel love.
Things appeared very low among us by the reports
brought in from some of our monthly meetings.
After dinner, when some of our friends had taken their leave,
a precious opportunity occurred,
in which Thomas Scattergood appeared in a remarkable manner to individuals;
which I earnestly desired might be blessed to them, and not pass away as the morning dew.

3rd. Our monthly meeting.
Humbled afresh, under a sense of my own weaknesses,
and unworthiness to partake of such unmerited blessings
as had of late been showered upon me;
and desired faithfulness and true dedication of heart might be the return.
Dear Thomas Scattergood was silent.
But before he left us,
we had a baptizing season and parted in sweet fellowship one with another.
I believe there was scarcely one insensible of the
precious influence which spread over us like a mantle.

20th. A stripping proving season in our little silent week-day meeting,
yet not unprofitable.
I hope ever to be thankful to feel the refining hand near for my preservation.

22nd. In my walk to visit the sick this morning, the beauty of the scene around me,
and the sense of multiplied blessings awakened my soul to gratitude and praise:
yet the morning meeting proved uncommonly dull and stripped of good.

27th. Though I long strove with a spirit of lukewarmness,
yet at length I was graciously admitted to the throne of grace,
and had sweet communion with my God.
Inestimable favour bestowed on a worm!

29th. A query, Are you nearer the kingdom than when you first believed?
livingly sprang in my mind, this morning at meeting, and after some searching of heart,
I was comforted in the belief that I had made some small progress in the heavenly race;
though still weak and standing in daily need of supplies of strength
and faith from Him who is the preserver of his dependant children.
In the afternoon I thought my situation somewhat resembled Mary`'s of old,
when she sat at the feet of Jesus washing them with her tears;
and wiping them with the hair of her head.
Blessed employment, precious privilege!
I, like her, have had much forgiven.
May I also resemble her in loving much.

=== Fifth Month, 1798.

10th. Felt renewed desires arise, for preservation from every snare of an unwearied enemy.

11th. Sat down at meeting in a lukewarm state, which prevailed too long;
yet after a while, being humbled under a sense of my faults,
I was once more in mercy permitted to wash in that
fountain which remains to be set open for Jerusalem,
etc. to bathe in.
Unspeakable favour!

21st. Attended the first sitting of the yearly meeting.
Thought it a season of renewed favour.
My poor mind was bowed in humble gratitude before the Father of mercies,
that he had once more permitted me to sit with his children in this large assembly.

24th. We had this morning an acceptable visit in the women`'s meeting from William Savery,
etc. who laboured abundantly among us, chiefly addressing the youth,
using much persuasive language to excite them to build on the ancient foundation,
which the righteous have ever built upon, in every age of the world.
He also exhorted them in a particular manner to refrain from reading unprofitable books.

29th. Two more sittings today, when the business was got through,
some weighty testimonies borne,
and awful supplication put up to the Father of mercies for the
preservation of each other when widely separated in body.
The meeting separated under a precious, solemn covering.

=== Sixth Month, 1798.

3rd. Sat again in our little meeting, I trust, under a thankful sense of past favours,
and laboured according to my small measure therein,
in a silent travail for the arising of the well-spring of life.

12th. My mind comforted and strengthened in the belief,
that love to God and good-will to men were gaining the preeminence in my heart,
above every other consideration; weak and frail as I am often made sensible it still is.
The other part of this week,
though I dare not say it has been so much improved as it might possibly have been,
yet I think has not been spent vainly.

19th. Attended our monthly meeting.
I felt weak and low, and found it no easy matter to get at the well-spring of life;
yet was at length favoured with a little of its arising.

24 A discouraging depressing season this morning at meeting.
It seemed as though I was left a prey to the enemy.
In the afternoon my hope and faith a little revived
by feeling the good hand still near for my preservation.
What a favour!

29th. This has been a week of no small trial to my feelings;
I think I have borne the cross as faithfully as I well could.

=== Seventh Month, 1798.

13th. A day of heaviness on account of a beloved brother who, I have reason to fear,
is departing from that simplicity and integrity of
heart which has hitherto characterized him,
and from whom we had hoped better things:
that he would have proved a standard-bearer in this poor county, Ah me!
I am at times dismayed at the prospect, when I see so many falling,
as on the right hand and on the left.

19th. Came to Newbury, on my way to Bristol.
To know that our Redeemer lives is indeed a great and blessed experience;
which I was favoured with this morning.
As I sat solitary at the inn, waiting for the coach,
he was pleased to break in upon my soul with the overshadowing of his life-giving presence,
which is more precious than the increase of corn, wine, or oil.
May I ever esteem it so.

21st. Attended the Bristol week-day meeting.
William Savery was led in close doctrine to reprove the hypocrites,
which brought me to much searching of heart, lest I should be found among that number.
He stood up a second time,
saying it frequently happened that deeply humbled minds took what did not belong to them,
and were ready to query, Lord is it I, who am about to betray you?
with more to that effect; which cheered my drooping soul.

=== Eighth Month, 1798.

1st. Went with a very large party to cousin George
Fisher`'s to breakfast with William Savery;
and from there to Pill to see him embark.
Before we separated, we had a precious, contriting season together,
in which he recounted the Lord`'s gracious dealings with him,
during his visit to the continent, and to this nation; and said,
though he was bound to acknowledge himself a very unprofitable servant,
yet he was now at parting enabled to adopt the language, "`Return unto your rest,
O my soul,
for the Lord has dealt bountifully with you:`" with much more expressive
of the peace he felt to crown his labour of love in this land.
We parted in near love and fellowship, and though it was trying to my feelings,
yet it was truly consoling to see him so comfortably
released from the present field of labour.

7th. Rather a low time at meeting; yet I trust the warfare was measurably maintained.

9th. Awoke this morning with a sweet and lively impression,
that the Lord`'s mercy was over all his works, even to me, the meanest of them.

16th. Wrote to a beloved brother, who I feared was departing from the simplicity of truth.

17th. Returned from meeting as from the washing pool sweetened and refreshed,
though I can but account myself unworthy.

20th. Received a gentle correction from the divine hand, which I kissed with submission.

24th. Afresh encouraged and animated to press forward in
the Christian race this morning at the silent week-day meeting.

25th. Heard some affecting accounts of further declensions
of some of the high and wise in our society:
enough to dismay such a poor weak creature as myself in the prospect,
did I not know that the word of the Lord endures forever.

31st. A deeply humbling season today at meeting;
in which however my poor tried mind was brought into sweet tranquillity.

=== Ninth Month, 1798.

7th. It was a low time today at meeting;
yet I think resignation and humility were the clothing of my mind.

9th. Was permitted through adorable condescension, to lean upon the Beloved of souls,
this morning at meeting; which I esteemed a precious privilege.
The evening meeting I thought a dull time.

20th. Went to take leave of my kind friends in this place +++[+++Bristol.]
Was favoured with a precious, cementing opportunity at dear Hannah Stephenson`'s;
seasonable it was to my mind, faith being at a low ebb.

30th. Went to Ryegate in order to attend our quarterly meeting.
The covering of my mind this day and for several
past may well be compared to sackcloth and ashes:
because of the slain of the daughter of the Lord`'s people.

=== Tenth Month, 1798.

1st. Our quarterly meeting.
A season of close trial to my mind on various accounts.

13th. This life is truly a cup of mixtures.
Many bitters have been infused into mine of late;
some of which have been very unpalatable to my taste;
yet I have desired to drink it with resignation;
which I trust I have been enabled to do in a good degree.
On the other hand many blessings have also accompanied me,
which I desire to be humbly thankful for, well knowing how little I deserve.

17th. My drooping mind a little refreshed, by retreating to the well-spring of life;
and renewed desires after preservation, from the various snares which surround my path,
were raised to Him who alone knows them, and how to sustain and carry through.

=== Eleventh Month, 1798.

4th. An unsubjected will prevented my access to the Fountain of sure mercies this morning:
to my shame I record it.
In the afternoon wrestled hard to have it brought into the state of passive clay,
which I was favoured in a good degree to experience; and thankful was I,
to feel every power and faculty of the soul brought into subjection,
and prostrated at the feet of a merciful Saviour.

7th. I trust, I still love above all things to sit at the feet of a crucified Saviour.
Blessed name!
How lightly esteemed at this day; yes, set at nought, and your divinity denied!
Mournful truths!
I believe with my whole heart,
that there is no other name under heaven by which mankind can be saved.

9th. Sat up last night with a neighbour; yet did not feel easy to stay from meeting,
which proved a sweet, solacing season, so that I could say,
it was good for me to be there:
ever desiring to esteem the lovingkindness of the Lord the greatest of all blessings.

11th. Mourning for myself and others has been much the portion of this day;
yet I got off my watch too soon, both in the morning and afternoon meeting

22nd. Received comfortable intelligence respecting a relation
having applied for admission into the society,
on the ground of convincement.
Truly pleasant it is, to hear some are gathering home to the true fold;
while so many are deviating and wandering as sheep without a shepherd,
and endeavouring to draw others after them.

30th. Though I did not maintain the watch so steadily as I ought to have done,
today at meeting; yet while my mind was properly centred,
I was favoured with the precious incomes of life and love:
a favour I thought myself unworthy of.

=== Twelfth Month, 1798.

4th. Our monthly meeting at Guildford.
My mind was bowed in the meeting for worship,
under a renewed sense of the omnipotence and omnipresence of God.

14th. A day of inquietude and weakness,
so that I could not get my mind properly stayed at meeting.

16th. My dwelling was much in the valley, today at meeting;
and through adorable goodness I was favoured to feel the dew rest upon my branches.

31st. Thus ends the year 1798.
A consciousness of manifold weaknesses attends me;
yet I feel humbly thankful that I am still preserved alive.
