== Chapter 9

=== First Month, 1799.

3rd. This has been a week of some trial of faith;
yet I think I have been enabled to bear the cross with some degree of faithfulness.

11th. After a time of conflict today at meeting I
was enabled to rise above a wrong disposition,
and approach Him who is the health of my countenance;
before whom my soul bowed in deep prostration and deep abasement of self.

16th. My mind has been too much outward for several days past, O,
for a closer walk with God.

19th. Hastened to Wanborough, dear +++_______+++ being thought near his end.
I found an afflicted house;
yet was favoured to feel my mind preserved in much tranquillity.

28th. What a severe scene has again taken place!
We had flattered ourselves the bitterness of death was passed,
when dear +++_______+++ was again plunged as it were to the very gates of it.
The doctors give no hopes: one of the poor lads is dead.
How awful are the approaches of such a messenger!

30th. +++_______+++ again reviving; and hope once more cheers this dwelling;
though we are almost afraid to entertain so welcome a guest.

=== Second Month, 1799.

15th. Came to Godalming.
Attended our weekday meeting, which proved a refreshing season to my poor mind,
which I thought myself unworthy of.
It was pleasant to sit again with my friends after such an absence:
indeed it was a season of mutual rejoicing.
I was thankful to see them again in health,
and they expressed much gladness at seeing me preserved from the contagion,
to which I have been exposed.
I felt my own unworthiness of such marks of tender regard.

=== Third Month, 1799.

1st. +++_______+++ continues mending.
I went to our monthly meeting, where I sat under a humbling sense of my weakness,
and inability for every good word and work,
both in the meeting for worship and discipline;
yet I felt a degree of heavenly sweetness accompany this frame of mind;
which led me to hope it was not altogether unacceptable to the Father of mercies.

3rd. Left my dear friends at Wanborough.
Attended both meetings, which were trying seasons to me,
for lack of more watchfulness on my part.

8th. The accoutrement of a true Christian was brought with
freshness to my mind soon after I sat down in meeting;
and fervent desires raised, after so excellent an attainment,
that I might thereby be enabled to withstand the varied assaults of an unwearied enemy.
It was a strengthening season to my poor mind.

15th. A season of sweet solace in our little week-day meeting.
I could not but lament that others should miss so great
a privilege by letting trifling things keep them at home,
or, if at meeting,
allowing a lukewarm disposition to deprive them of this best of blessings,
communion with their God.

23rd. The rest of this week mostly spent in the service of others,
and not wholly unprofitably, I trust.

29th. My tried mind instructed in my silent sitting today at meeting;
and renewedly led to number my blessings, and see how much I owed unto the Lord.

=== Fourth Month, 1799.

1st. Our quarterly meeting.
I thought the meeting for worship a season of renewed favour to our youth in particular.
The meeting for discipline was very trying to my feelings from various causes.

4th. Our friends Mary Watson, Mary Alexander, and John Kirkham sat with us this morning.
It proved a strengthening season to the drooping minds of some.
"`Blessed are they that mourn,`" was the encouraging language.
Surely we have abundant cause of mourning,
because of the increasing desolation in our society:
the prospect whereof is ready to dismay the feeble travellers towards Zion.

8th. A precious, contriting season this morning,
previous to our beloved friends leaving us:
in which the dear young folks were affectionately
encouraged to follow on to know the Lord.
Dear W. T. was particularly addressed,
our friends believing his tender mind had been preciously visited.
How did all that was within me covet that the good seed which, I did believe,
had been sown in the hearts of some of them might be cherished,
and bring forth in due season fruits to the praise of the great and good Husbandman.

19th. Heaviness of spirit has been my portion this day,
discouragements of various kinds pressing hard upon me.

21st. A day of mourning because of the desolation in our Zion,
when those that should have been standard-bearers desert a cause so precious.

=== Fifth Month, 1799.

1st. After a season of conflict, my will was once more reduced,
and I was enabled to adopt the language of, Not my will, O Lord, but yours be done.

5th. Shamefully lukewarm this morning at meeting.
In the afternoon a little strength was given to labour,
which I think I did according to my small measure.

10th. My mind has enjoyed for several days past a sweet tranquillity,
to which it has of late been much a stranger.
I feel, I trust, humbly thankful for this favour,
well knowing I cannot attain to it of myself.

=== Sixth Month, 1799.

5th. Renewed desires after preservation,
feeling myself much stripped of the sensible presence of Him,
who is I trust the beloved of my soul.

6th. My dear brother and sister Waring left us, which was no small trial to our feelings.
We parted, I believe, in best love, and desires for each other`'s preservation.

7th. Favoured in our little silent gathering with
sweet access to the inexhaustible Source of all good.
My heart overflowed with gratitude for blessings ancient and new.

9th. Baptized afresh into a deep sense of my own nothingness;
and the need I stand in of renewed supplies of strength; which I earnestly craved,
that I might walk uprightly in humility and fear all my days.

11th. Went to Guildford to meet dear Deborah Darby and Rebecca Young.
Was not a little disappointed in finding they had passed us by.
Sat with the few in silence, where after a dipping season,
my soul was refreshed by the renewed incomes of life and love.
How unworthy do I esteem myself of such inestimable favours!

16th. The general meeting at Guildford.^
footnote:[On which day Godalming meeting is suspended.]
In the morning I was favoured with ability to centre deep.
In the afternoon I thought we sat down a poor company indeed,
and found it hard work to keep on the watch.

18th. Read a little pamphlet, written by a German, a woman of rank in life.
Was humbled under the consideration of her faithfulness in following a crucified Saviour;
while I with superior advantages remain but a babe, I often fear a dwarf, in religion.

20th. My weak mind being too much off its guard, I was caught with a temptation.
Remorse soon followed.

21st. Mourned my folly, and renewedly besought forgiveness, and future preservation.

23rd. A day of some conflict of spirit.

30th. Went to Wandsworth to our quarterly meeting.
The morning meeting, I thought a favoured season; the afternoon heavy and laborious;
though towards the close a little life arose.
A committee from the yearly meeting attended; a choice little band.

=== Seventh Month, 1799.

1st. Afresh did the crook of divine love seem extended towards a backsliding generation,
in adorable mercy and condescension.
Our dear friends laboured among us in much love;
and I thought a good degree of harmony prevailed,
and I was comforted in observing much more openness than I expected in the visited;
so that I think the committee had an opportunity of seeing pretty clearly the low,
very low state of things among us.

5th. The above-mentioned committee came here +++[+++Godalming]
last evening.
My soul was renewedly humbled under the consideration
of the continued kindness of a gracious God,
in thus sending his faithful servants and hand-maidens to labour among us;
which was strengthening to the feeble minds of some of us.
Spent the evening at brother Kidd`'s. The dear young folks were afresh invited to come,
taste, and see for themselves how good the Lord is.

6th. Our dear friends left us.
Samuel Alexander, John Abbott,
and Hannah Wigham had a sitting with us just before we parted;
which proved a precious opportunity,
in which our souls were nearly united in the heavenly fellowship,
and sweetly refreshed together.

7th. Renewedly convinced that it would not suffice
the soul to feed on the manna gathered yesterday;
but that it must be daily waited for,
if we would indeed witness a being nourished up unto everlasting life.

14th. A renewed call to faithfulness this morning at our silent meeting:
the afternoon was dull and heavy in the forepart;
but towards the close life arose into a good degree of dominion.

17th. Dear uncle Kidd spent the day with us;
the first visit he has paid I believe for near a twelvemonth.
His quiet, peaceful frame of mind was instructive and encouraging.

20th. The rest of this week has passed serenely away; I would hope not wholly unimproved.
How many blessings have I to be thankful for!

21st. A degree of favour attended both meetings,
and I trust a degree of right exercise was for a season maintained in each of them;
but I think I did not keep so faithfully on my watch as I should have done,
particularly in the evening.

25th. Have seemed left to myself, and as a prey to the cruel enemy for several days past;
yet have been enabled at times to bemoan my condition,
being ready to conclude there are few if any who are more propense to evil than me:
a humbling consideration indeed!

26th. Sat down at meeting this morning under the belief
that I was altogether unworthy of divine regard,
or of approaching Him who is perfect Purity;
yet after sitting a while in this reduced state before him,
he was pleased in wondrous love and mercy to stretch forth the sceptre of his love,
and once more permit me to praise his holy name, who is eternally worthy.

=== Eighth Month, 1799.

2nd. Seemed uncommonly lukewarm and indifferent on sitting down at meeting,
to which I too much yielded for a while; but after some struggle,
was favoured with near access to the inexhaustible Source of all good.

6th. Have been led to ponder on the depravity of the human heart,
and particularly of my own; believing few if any have more propensity to evil;
also led to call to mind the gracious dealings of a merciful, long-suffering God,
who has sustained me and preserved me unto this very hour.
O, that he would also be pleased to give additional stability,
that I may be enabled to walk before him with a perfect heart.

9th. A time of searching of heart today at meeting, a profitable employ!
I think I love to bring my deeds to the light,
and feel all the evil brought into judgment,
and sit under the purifying operations of the Spirit of truth: O,
may I be careful to keep my garments from defilement.

15th. Brother Tothill came,
and brought with him a little good tidings respecting the labours of David Sands.

18th. Our general meeting at Guildford.
My mind measurably gathered to the true centre, in the morning.
In the afternoon, I thought, we sat down a poor little company.
The poor soldier^
footnote:[A soldier quartered at Guildford, who frequented the meetings of friends,
and appeared under convincement.]
was present, which brought an awful fear over me,
lest he should be turned aside by observing unwatchfulness
and a lukewarm disposition prevail;
and the prayer and exercise of my heart was that we might all, both he and we,
be preserved in our different allotments and found faithful therein.

25th. My mind much tossed this morning at meeting:
the way proved deeply humbling and instructive.

30th. Was renewedly desirous that my dwelling might ever be in the low vale of humility,
where the dew rests.

=== Ninth Month, 1799.

6th. A day of profitable humiliation, I trust.
I desire to prize every dispensation that tends to reduce self,
however hard to the natural part.

7th. Still learning the hard lesson of suffering patiently.

11th. Many are the cogitations of my poor mind, sometimes unprofitable:
at others pure desires after more stability and holy circumspection in thought, word,
and deed, prevail.

15th. Could set up my Ebenezer and say, Hitherto has the Lord helped me.
Forever blessed be his name!
In the afternoon the dreadful end of the hypocrite impressed my mind,
with strong desires that I might be preserved from it.

20th. Rather a low time at meeting this morning,
yet I have felt a comfortable degree of quiet for several days past.

22nd. A time of conflict this morning,
in which I hope the enemy gained but little advantage.
The afternoon proved, contrary to expectation, a refreshing season.

27th. Gave way to a roving disposition in the forepart of the meeting,
which produced shame and remorse, and the language of the poor publican,
"`God be merciful to me a sinner.`"

29th. Lowliness and fear were in a good degree the companions of my mind this day.

=== Tenth Month, 1799.

7th. Went to Ryegate to our quarterly meeting.
I think the meetings were favoured seasons; though cause of discouragement still remains.
The committee (John Abbott excepted) were there, also Phebe Speakman and companion.
Met with an accident on our return, but were preserved from harm:
which I esteemed a favour.

11th. A time of sweet solace this morning at meeting.
My soul panted after the refreshing streams of Shiloh; and was abundantly replenished.
Unspeakable mercy!

17th. Phebe Speakman and Mary Townsend left us: a day of no small trial to my feelings.
Seeing the depression the said friends were under, Mary Townsend wishing to return home,
and Phebe Speakman unwilling to detain her,
I thought myself called upon to offer to accompany the latter for a few weeks as a servant.
The sacrifice is offered, whether it will be accepted is yet uncertain.

20th. Was renewedly desirous that I might be preserved in
a single dependance on the Lord in my approaching journey,
for preservation every way, and have no confidence in the flesh;
believing that those who trust in the Lord shall never be confounded.

24th. Parted with my beloved connections, which was trying; yet felt peaceful,
which induces me to believe that I am in my right place.
Reached Chichester this evening,
where I met with dear Phebe Speakman who appeared glad to see me.

26th. Left our kind friends at Chichester, and reached Alton in the evening.

27th. Attended both meetings,
which were measurably favoured with the descendings of heavenly dew.
I thought Phebe Speakman appeared excellently.

28th. Parted with my dear sister, and came to Basingstoke.
Was desirous that I might be preserved in humility and fear;
and that my deportment might not in any degree disgrace the cause
dear Phebe Speakman is engaged so earnestly to promote.

30th. Was at the week-day meeting at Whitchurch, a little company indeed;
yet I thought the crook of divine love was afresh extended in order
to gather the outcasts of Israel and the dispersed of Judah.

31st. Attended the week-day meeting at Andover,
which was to my feelings a preciously favoured season.
May it prove so to some who were present, and not pass away like the early dew.
I thought Phebe eminently favoured to divide the word aright.

=== Eleventh Month, 1799.

4th. Came to Ringwood, where my mind was dipped into a low spot,
from some discouraging circumstances.
Was at the week-day meeting,
where I think I was renewedly enabled to offer up my own will,
desiring the Lord`'s might be done.

6th. Attended the week-day meeting at Pool, a season to be remembered by me,
for the fresh descendings of heavenly dew.
A laborious season to dear Phebe, who was led in a close line to rouse the lukewarm.
Had a sweet little opportunity in a friend`'s family in the evening.
Phebe finding we could not go to Guernsey, but in an armed vessel,
felt her mind unexpectedly released from the voyage;
which was a great relief to my poor mind.

15th. Came to Sherborne.
Met unexpectedly and pleasantly with John Wigham and John Abbott,
who were on their way to Guernsey.
Here we got a fresh dip, respecting going there.
Phebe had a meeting at the above-mentioned place:
a precious season to my mind during the silent part of it.

19th. Went to Somerton; dear Phebe laboured abundantly among the little flock here.

21st. Came to Bristol,
where I had the satisfaction of meeting my beloved connections in health,
and my dear sister better than I had expected;
which I esteemed a great favour added to the many,
the very many received in my late journey;
the chief of which I reckon was the Lord`'s condescending goodness
in owning and refreshing my spirit in every meeting I sat in.

=== Twelfth Month, 1799.

8th. Sat in a low spot this morning at meeting,
under a humbling sense of my unworthiness to approach perfect Goodness;
yet was favoured to feel the healing waters administered.
In the evening I was shamefully unwatchful: poor unstable creature!

9th. Parted with my endeared friend Phebe Speakman,
which was no small trial to my feelings.

11th. Attended the quarterly meeting at Bridgewater.
I think the meetings were favoured seasons,
but I did not derive so much benefit from them as I might have done,
had I kept more steadily on the watch.
David Sands gave us much of his company at the inn,
and appeared several times acceptably, and once remarkably.

13th. I wrestled today at meeting as in the night season,
and my endeavours were not altogether unblessed.

18th. My mind has been much tried for some days past,
yet this has been its humble language, Shall I not drink of the cup that you hand me;
although its mixture be wormwood and gall?

20th. Some degree of sweetness and resignation.

22nd. A precious season to my poor soul,
being graciously permitted to lean upon its beloved.

24th. A trying day in taking leave of some near relations and dear friends at Bristol.
A contriting season at dear Hannah Stephenson`'s.
We parted under a precious covering and near sympathy.

27th. Came home.
Found dear uncle Kidd in a very weak state, but better than I expected.

31st. Thus another year is passed away; in which I have, I trust,
endured some conflict with a good degree of resignation,
yet a sense of manifold infirmities is still my companion.
May He who has hitherto been my Rock and my Shield
be graciously pleased to preserve from falling,
and enable me to follow him, though in a crucifying path.
