== Chapter 10

=== First Month, 1800.

3rd. Our Monthly meeting; which I thought a low season.
Afresh pained at the increasing departure of a beloved brother from the true foundation,
as I believe.

8th. Our quarterly meeting at Esher.
Mourning and heaviness of spirit were much the clothing of my mind,
the forepart of the meeting;
yet afterwards I was a little encouraged by the animating testimony of John Wigham,
under a belief that a renewed visitation was extended to a backsliding generation.
How excellently did he point out the way to life,
and the many stratagems of an unwearied enemy to lead from it!

14th. Some disappointments attending, I have felt a disposition bordering on repining;
to which at times I have too much yielded; at others, I have striven against it.

16th. Have felt renewedly,
pure desires begotten in my heart after a total resignation of my will to the Lord`'s;
which I esteem a favour from his bountiful hand.

17th. Was enabled this morning at meeting to cast
down every crown at the footstool of a merciful Saviour:
and renewedly to crave preservation and conformity to his will:
which he alone can produce.

19th. Again struggled after resignation,
and was enabled to repose all my cares on a merciful Providence;
who cares for the ravens,
and who knows best what to dispense to the workmanship of his holy hand.

24th. My mind has enjoyed a good degree of quiet and resignation for several days past.

24th. Saw into the beauty and excellency of walking by faith.
O this divine anchor to the soul!
Without its support how often should I have fainted by the way!

=== Second Month, 1800.

2nd. Am fearful my offerings were not sufficiently unmixed with creaturely zeal;
although I think my desires were sincere that they might be so.

9th. This morning I had renewedly to number my blessings,
and see how much I owed unto the Lord.
In the afternoon meeting the enemy threw discouragements like a cloud over my mind:
which caused me sore conflict.

19th. In my solitary walk to visit the poor, the address of the angel to Cornelius,
"`Your prayers and your alms are come up for a memorial
before God,`" sweetly impressed my mind;
not that I believed it applicable to myself,
well knowing how improperly I perform my duty in these respects, as well as others;
yet it brought me into contrition and a humble resigned frame of mind.

24th. My beloved uncle Kidd appears hastening quickly to the solemn close,
crowned with sweet peace.
He said today, all would be well; he never before had such a prospect of it;
he thought he saw the angels waiting to receive him.

25th. Still drawing nearer to his everlasting habitation.
We thought him going this evening,
but he revived again and said he was going to leave a troublesome world.
A truth we could feelingly subscribe to.

=== Third Month, 1800.

7th. A time of wrestling today at meeting; found it hard work to get my mind centred.

9th. Went to meeting under depressing sensations on account
of the increasing deviation of a beloved friend;
yet have thankfully to acknowledge,
my faith in the divine all-sufficiency was renewed
by the fresh extensions of heavenly love.

10th. The company of dear Thomas Colley was as unexpected as it was pleasant.
He came this afternoon and had a public meeting in the evening:
in which he laboured abundantly to gather the people home to Christ the true foundation,
inviting them to buy milk and wine without money and without price.
These words to me appeared fitly spoken,
comparable to apples of gold in pictures of silver.

11th. Accompanied Thomas Colley to Guildford, and attended the week-day meeting.
He was again led forth to invite the strayed sheep to the true fold,
believing there were present who had been brought out of Egypt;
but because of unbelief had loitered long in the wilderness.
To these he believed the call was extended, "`Come out of the wilderness;
you have compassed this mountain long enough:`" adding, "`O you of little faith,
why did you doubt?`"
A public meeting in the evening, owned I think by the Master of our assemblies.

15th. My revered uncle Kidd quietly departed this life about
twenty minutes past ten o`'clock this morning.
Peaceful was his close; may my latter end be like his.

23rd. Many friends came to attend the burial of dear uncle Kidd,
so that the remains were honourably attended,
and borne to the grave by his friends who had long known his worth.
I thought the forepart of the meeting covered with solemnity.

27th. Calm and peaceful, and I trust humbly thankful for unmerited blessings.

30th. My strength renewed in the all-sufficiency of him,
under the shadow of whose wing I ever desire to put my trust.

=== Fourth Month, 1800.

1st. Our quarterly meeting.
The meeting for worship was an exercising time,
yet owned by him who remains to be the crown of our religious assemblies.
I was enabled to get through the business of the
meeting with some degree of satisfaction to myself,
and I would hope to that of my friends.
May I ever acknowledge with thankfulness from where my help comes,
well knowing that I can do nothing aright of myself.

5th. Think I have been profitably employed most of this week as to action.
I wish I could add my mind had been equally so; but fear that is not the case.

10th. My feelings have been uncommonly trying for several days past.
The Lord alone knows the conflicts of a weak heart.

11th. Once more, after a severe struggle, I was enabled to surrender my will,
and all that belongs to me, into the hands of a merciful Creator:
well knowing that he will order all things aright and eventually for my good;
although at times faith may be at so low an ebb, I may not be able to see it.

13th. Retreated as to the washing-pool, from which I returned sweetly refreshed.

15th. Came to London in order to assist A. Newman
in nursing her two infants who are dangerously ill.
Found them removed to Hampstead.
An affecting scene presented, sweet delicate Mary stretched on her cot,
little more than a corpse; and Thomas almost as ill on a bed near.

23rd. The sweet lambs still living, but the physicians give no hopes of their recovery.
How inscrutable to us short-sighted mortals are the ways of that wisdom which cannot err.

30th. Dear Thomas breathed his last about half past
six o`'clock this morning without a struggle.
What a merciful release from pain and sorrow;
while his darling sister is left to struggle a while longer;
and her sufferings are a considerable addition to the grief of their afflicted parents;
who however are supported to admiration.

=== Fifth Month, 1800.

8th. Was at the week-day meeting at Chelmsford; and though I had nothing to boast of,
yet I have to acknowledge, that my mind was preserved in a degree of peaceful quiet.

12th. Came to Stansted to the peaceful habitation of William Grover and wife.

13th. Attended their week-day meeting,
which proved a sweetly refreshing season to my mind.

+++[+++Here some pages were cut out of the original manuscript.]

=== Sixth Month, 1800.

2nd. Came home after attending the yearly meeting,
which on the whole was I think eminently favoured
with the overshadowing of heavenly love and life,
of which my mind was permitted at seasons to partake;
though I consider myself altogether unworthy of such a mark of divine regard;
yet at others my faith was tried as to a hair`'s-breadth,
and it seemed as if the enemy would have been permitted
to have destroyed every good resolution.
The waves indeed rose high, but the Lord in matchless mercy rebuked them,
or else they had gone over my head.

6th. A precious baptizing season in our little week-day meeting,
in which my faith was renewed in the all-sufficiency of God,
and my soul was brought into a humble acquiescence to his will.

8th. Once more was I permitted to lean as upon the breast of the Beloved of souls,
and cast all my cares upon him; craving preservation,
and that I might be enabled to walk before him with a perfect heart.

10th. Affecting intelligence indeed that defection of principle has appeared;
surely it is a time for lamentation.

12th. Much in the valley;
surely the proper allotments for all concerned for the precious cause of truth.

15th. Think my mind was in a good degree profitably
exercised both in the morning and afternoon meetings.

17th. A degree of peaceful serenity has been much the covering of my mind this day;
which has excited thankfulness.

22nd. This day and yesterday have been seasons of conflict.
Discouragements like a cloud have come over my poor mind.
I think I should have fainted had not the Lord sustained me.

24th. More discouraging circumstances!
Adverse winds seem to blow from all quarters.
May I be preserved in humility and patience.

29th. Favoured with near access to the Fountain of light and life.
Blessed privilege!
May I make suitable returns.

30th. Went to Wandsworth, under very depressed feelings,
hearing some were likely to attend our quarterly meeting, who were opposed to the truth,
as it is in Jesus.

=== Seventh Month, 1800.

1st. I could compare our sitting down today at meeting
to nothing short of two armies in battle array.
In great abasedness of soul did a remnant approach the Lord,
beseeching that he would arise for the sake of his oppressed seed,
and surely I thought he fought for us; and marvellous it was in the eyes of some of us,
who rendered the praise where it was alone due.

10th. The last few days rather unsettled,
having been in daily expectation of going from home, and as often disappointed,
yet the better part not wholly neglected, I trust.

11th. My spiritual strength and confidence renewed today in our little silent gathering.
How often do I lament that so few come up to these solemn feasts,
for lack of a right exercise of mind and attention to the gift within themselves.
Came to Alton.

13th. Dear Elizabeth Coggeshall and Abigail Pim came.
A degree of divine favour attended both meetings;
though the evening meeting was heavy towards the conclusion.

19th. My mind sweetly consoled,
in the belief that it has of late been a time of increasing watchfulness,
and I would hope of some little growth.

22nd. Rather a laborious meeting for lack of united exercise of spirit.
Oh! what avails our presenting our bodies, if our hearts are wandering?
Surely God will not be mocked.
Such as we sow, such shall we reap: an awful consideration!
May it excite to greater diligence.

27th. The enemy of all good desires was busy this morning at meeting,
in endeavouring to draw my mind from its proper centre;
yet trust he did not gain much advantage over me.
I went in the evening under discouragement, but it proved, contrary to my expectation,
a sweetly refreshing season, feeling the dew of heaven rest upon my branches.
Thus bountiful is God to the workmanship of his hand.

30th. A trying meeting, in part owing to the extreme heat of the weather.
I waited long without obtaining; but before the meeting closed, the Lord,
in great condescension, satisfied my soul with his life-giving presence.

=== Eighth Month, 1800.

1st. A day of trial; yet I think resignation was in good degree attained to:
for which I was thankful, well knowing it is not at my command.

3rd. Sat at Wisdom`'s gate, where my soul was secretly and sweetly instructed.

6th. Favoured with near access to that river the
streams whereof make glad the whole heritage of God.
Returned from meeting sweetly refreshed.

8th. A degree of sweet resignation to suffer whatever the
Lord should see fit to dispense to his unworthy creature,
was the covering of my spirit this day.

17th. The prayer of Agur was adopted by me today.
Both morning and evening were precious seasons to my waiting soul.

23rd. The last three days have been wholly occupied
in attending the dying bed of cousin Agnes Blose,
of Alton, who had a long conflict; which was affecting to our affectionate feelings:
yet we had the consoling hope that the better part
was safely centred beyond the reach of the enemy;
and that she was not sensible of bodily suffering.
She breathed her last about four o`'clock this morning,
and her wearied spirit I doubt not is at rest.
I trust I am profitably humbled under a sense of
some weaknesses I fell into through unwatchfulness.

27th. Love to God and good will to men have been much the
disposition of my heart for several days past.

=== Ninth Month, 1800.

4th. Oh this warfare!
When will it be accomplished?
May it be faithfully maintained on my part, is my sincere desire;
yet without divine assistance I know I am unequal,
and therefore humbly crave its continuance: for surely the Lord has hitherto helped me,
else I had long ago perished.

10th. Met with a trying circumstance before I went to meeting this morning,
which so unsettled my mind that I reaped but little advantage from going.
John Newton and his niece dined with us.
He appeared a tender-spirited man, which is ever beautiful in old age.
He gave us some interesting information respecting his friend Cowper;
whom he could not mention without tears.

13 Came home and found my dear relations well, which I esteem a favour.

17th. A large number of the labouring poor assembled together,
to the number of one hundred, on account of the high price of provisions;
but were prevailed upon to disperse without doing any mischief, as they had threatened.
It was an awful season, but my mind was mercifully preserved calm, trusting in Him, who,
I knew, could set bounds to the wrath of man.
Without this unshaken confidence where could we flee for succour,
in the time of conflict and trial.

21st. I studied to be quiet and mind my own business,
but found it hard work to keep in this frame of mind.

23rd. Attended our monthly meeting; a humbling season to my mind.
Drank tea with a beloved friend, on whose account I felt more than I can express.
O, that he may yet be brought back to the true fold, was and is,
the ardent desire of my soul!

27th. Felt something of a real hunger after the bread of life.

28th. Was desirous of hungering and thirsting patiently today at meeting;
believing it was not a season of rejoicing.

=== Tenth Month, 1800.

1st. Attended our quarterly meeting at Ryegate,
where I trust I was enabled to bear my portion of suffering without murmuring.
It was in truth a low time.

3rd. My spiritual strength measurably renewed.

16th. "`Be still and know that I am God,`" sweetly impressed my mind in the morning;
an injunction I was desirous of obeying.

19th. The week-day meeting.
Had to remember the Lord`'s gracious dealings with me from my youth,
and see how vast my debt is to the Lord.

23rd. Had to trace back some painful steps I have taken in the crucifying path;
when my will was once more reduced, yes,
all that was within me bowed at the name of Jesus,
and I had renewedly to feel something of adoption rest upon me:
an experience more precious then rubies!

=== Eleventh Month, 1800.

2nd. Had to go again into the stripping-room, and renewedly to acknowledge that in me,
as a creature, dwells no good thing.

7th. My dwelling has been much in the valley for several days past;
and at times I have been favoured to feel something of the dew rest upon me,
in this solitary situation.

9th. An unusual sadness, has been the covering of my mind of late.
What it portends I know not;
but I have desired to leave all to the disposal of that wisdom which cannot err.

10th. How often do I think my will slain; and that I desire nothing but the will of God!
Yet again and again do I find a disposition that would be choosing and carving for itself.
Oh, this continued warfare!
When will it be accomplished, and my wearied spirit find rest?

14th. Some little time ago,
I was favoured with the sustaining belief that I was increasing in holy stability,
and in some degree in the saving knowledge of God;
but of late I have seemed so left to a sense of my own weakness and insufficiency,
that I have been ready to fear at times I should become a prey to the devourer.

16th. A little of the hidden manna in great mercy dispensed to my hungry soul,
in my silent waiting today at meeting.

19th. More tranquil and comfortable;
which I esteem an unmerited favour bestowed upon a worm.

21st. Favoured with some degree of heavenly communion
in my silent waiting today at meeting.
Inestimable privilege!
May I ever prize it, as it deserves.

23rd. My state of mind today at meeting much resembled that of the poor publican.
I was impressed with so deep a sense of my infirmities,
that I thought myself unworthy to hold communion with him who is perfect purity.

29th. This week has passed peacefully away, and I would hope not wholly unimproved.

=== Twelfth Month, 1800.

2nd. Our monthly meeting, a day of exercise and mourning to me,
from the increasing deviation of some, from whom we had hoped better things.

5th. Was enabled to discharge my duty as an overseer, though in a cross to my own will.

12th. Sat in a good degree of nothingness today at meeting.

14th. Was favoured with an extraordinary degree of divine favour,
in my silent waiting this morning.
I thought it somewhat resembled the morning stars singing together for joy.
I thought before I left the meeting, it was preparatory to some fresh trial,
and so it proved;
for soon after I met with a circumstance which severely wounded my best life;
so that heaviness of heart was my portion the rest of the day.

15th. Think I have faithfully discharged my duty towards a beloved friend;
yet feel much tried and borne down with grief.

19th. Still desirous that my dwelling may be in the valley;
and sometimes think how light the afflictions of time will appear,
if in the end I am but favoured to reach the haven of rest:
where all tears will be wiped away, and sighing and sorrow cease.

20th. My feelings afresh wounded.

21st. My faith and confidence renewed in the all-sufficiency of God.
Without this divine anchor, how often should I have fainted by the way.

23rd. O,
that I may be enabled to walk more in the path of simplicity and self-renunciation.

24th. A day of renewed exercise and trial of faith and patience.

29th. Unpleasant intelligence from various quarters.
O, to keep quiet and patient under the trials of the day.

30th. Much depressed.
And now I am come another year nearer the end of this probationary state:
which feels rather pleasant,
having little to expect in this life but a succession of trial,
every pleasant picture being stained in view, doubtless for wise and good purposes.
O, that the Lord who has hitherto been my helper, my sun and my shield,
may be still pleased to preserve me in a state of humble daily dependance upon him,
resigning all into his holy hand.
