== Chapter 13

[.centered]
=== First Month, 1803.

1st. I rose this morning with renewed desires after holiness, hoping to have a good day;
but alas!
I found the tempter near spreading his baits, to catch the feet of my unwary mind:
in which he too well succeeded, so that sorrow and self-abasement were justly my portion.

3rd. Went to Horsham, in order to attend the quarterly meeting.^
footnote:[Two of the monthly meetings of Surry were
at that time joined to the quarterly meeting of Sussex.]
We went through some deep water without injury, which some of us esteemed a favour.

4th. I sat down at meeting this morning, under a humbling sense of my own unworthiness;
yet the great Shepherd of Israel, in his customary goodness,
was pleased to overshadow the minds of some of us with his life-giving presence:
an unmerited mercy.

5th and 6th. Days of humiliation, having missed my way.

9th. Once more was the royal scepter in great mercy extended to a poor penitent.
What return, O my soul; can you make unto the Lord for all his benefits?

12th. Trust I have stepped along the last few days,
with some degree of watchfulness and safety.

14th. I desired not to eat the bread of idleness today at meeting;
and think I laboured according to the ability received; which was not in vain,
my soul being sweetly replenished.

16th. My soul bowed under a sense of multiplied blessings, both ancient and new,
and the poor return I had to make to an all-bountiful Creator.
In the afternoon had a fresh combat with my spiritual enemies.

17th. Renewedly desirous of walking uprightly in
the heavenly image in which man was at first created.

23rd. A day of conflict of spirit, in which the enemy prevailed for a season;
yet I think he was silenced and put to flight, through divine assistance.

27th. I think thus far of the week has been literally spent in the service of my neighbours;
yet I trust the better part has not been wholly neglected.

29th. Somewhat comforted with the belief, on a retrospect,
that the day`'s work is in some measure keeping pace with the day.

[.centered]
=== Second Month, 1803.

1st. Our monthly meeting at Guildford,
in which I was according to my measure dipped into the low state of things among us;
so that heaviness of heart was my portion.

4th. By giving way to a roving disposition on first sitting down at meeting,
my way became so hedged up, that I could not discern a path; but,
after struggling a while, I was enabled to press through the crowd of difficulties,
and approach Him who is the health of my countenance, and my God.

6th. I fear my concern today, though not unprofitable in itself,
was beside the proper business.

9th. Some renewal of my spiritual strength, and confidence in the divine All-sufficiency,
this morning.

11th. A precious, contriting season at our little silent meeting today.

12th. When led to see the evil propensities of my heart,
I am at times ready to compare myself to poor Mary of old,
out of whom our Saviour cast seven devils, and having had much forgiven,
am I trust sincerely desirous of imitating her in my love towards him.

18th. My spirit sweetly contrited on reading some
account of the close of dear Samuel Emlen,
of Philadelphia, which raised renewed desires that I might live the life,
and so be prepared to die the death, of the righteous.

24th. The last few days much taken up with company;
yet I trust not altogether unprofitably so.

25th. Retreated as to the measuring line,
where I desired to be made sensible of my deficiencies,
and enabled to bear every refining operation necessary for my complete sanctification.

27th. My spirit sweetly centered in the morning; in the afternoon too unwatchful.
O, when will my mind resemble the garden enclosed, every hurtful thing shut out.

[.centered]
=== Third Month, 1803.

2nd. The last few days have passed serenely away;
and the watch I trust has been in a good degree maintained;
yet I know that I stand in jeopardy every hour, having an unwearied enemy,
who is often seeking to lay waste every good desire.

4th. Goodness and mercy are still following me.
What return, O my soul, can you make for such unmerited favours?
May you endeavour to walk in humility and fear, all the days of your life.

9th. The last few days have been busily spent, as to action:
but my mind has wandered often unprofitably;
which at seasons has been cause of mourning and heaviness of heart.

11th. I sat down at meeting, I think I may venture to say, in self-abasedness,
and I was shown that if I kept nearer that power which can alone give the victory,
I should not so often have found my spiritual enemies prevail against me,
and the petition of my heart was for more stability,
and that the woeful portion of the hypocrite might never be mine.
The morning meeting measurably favoured with the
overshadowings of heavenly love and life,
in great mercy extended to the seeking, waiting soul.
A few of this number, I trust, were thus gathered.

16th. Something like a renewal of covenant this morning.
Oh, how ardently did I desire, that I might henceforward walk with unerring steps,
in the path of humility and self-denial:
counting every inferior enjoyment but as dross and dung, so that I might win Christ;
but alas! when I consider my frailty and proneness to self-indulgence,
I have much reason to fear that I shall yet have to mourn many missteppings in my pilgrimage.

19th. A day of some vexation, which I fear I did not bear with sufficient meekness.

20th. My soul afresh bowed before the Father of mercies,
craving the continuance of his preserving power and care over me.

27th. Think I was enabled to cease from my own imaginations,
and in a good degree favoured with true silence, in my sittings today at meeting.

30th. My time has been this week much devoted to the sick and poor,
being surrounded with sickness;^
footnote:[Influenza, probably.]
but our family is at present in health, which calls for gratitude:
as well as the many other blessings showered upon us,
and of which I trust we are not insensible.

[.centered]
=== Fourth Month, 1803.

3rd. A sweetly refreshing season to my poor mind at meeting, this morning.

5th. Our quarterly meeting at Brighton.
The meeting for worship was not very lively to my feelings;
the business was got through more satisfactorily than sometimes.

8th. This day I have passed through a most distressing scene, dear Mary Holland,
a few hours after her infant was born, was removed by death.
Never while memory remains, shall I forget, at seasons, this affecting scene.
It seemed almost too much for nature to support, unassisted by Divine Power.
But Oh!
I trust she was in abundant mercy received where
pain and sorrow will never more annoy her.

19th. Weak and languid from my late exertion:
but was favoured in my silent sitting to feel something of the healing waters,
dispensed to my poor drooping mind.

13th. Still occupied in visiting the abodes of sickness and sorrow;
yet feel my strength in some measure recruited, through mercy.

17th. A preciously favoured season, in our little silent meeting this morning.

20th. Much taken up with company;
yet my mind has at some seasons aspired after the alone Source of good,
at others it has been too much scattered.

22nd. A day to be long remembered by me, I trust,
for the fresh descendings of heavenly dew!
O, that I may be enabled to walk worthy such unmerited favours.

24th. My mind renewedly instructed in my silent waiting today at meeting.
How much is it to be lamented, that any should be slighting so great a privilege!

27th. Still busied about many things;
though a consciousness of many attendant weaknesses is my present companion;
yet I trust I am in some degree pursuing the one thing needful.
O, that it was with more ardency of spirit, is my constant aim.

30th. A fresh scene of trial and affliction opened upon us,
may it be sanctified to us and those more immediately concerned.

[.centered]
=== Fifth Month, 1803.

1st. Graciously permitted to lean upon the Beloved of souls,
in my silent sittings before him today.

3rd. Was shamefully thrown off my guard for lack
of a more close attention to my unerring Guide.
Self abasement is justly my portion this day.

6th. Favoured with some beams of divine consolation, in my lowly sitting this day.

8th. Travailed, according to my measure, for the dead,
that they might be favoured to hear the voice of the Son of God and live.

11th. Have been confined this week with a sore throat,
but have been gently dealt with and tenderly nursed by my kind friends; and, above all,
been favoured at seasons to feel the Comforter near.
May you deeply ponder, O my soul, how much you owe to so merciful a God,
and walk worthy of such unmerited privileges.

17th. Came to Walworth in order to attend the yearly meeting,
after a pretty agreeable journey,
and under a grateful sense of past as well as present favours.

26th. A sitting of the yearly meeting in the afternoon, where to my great surprise,
Mary Bevan proposed my name to the meeting as one
of the committee to visit Hampshire and Dorsetshire.
It bowed me exceedingly,
believing myself by no means qualified for such an important service;
but after pleading my disqualification, and desiring my name to be withdrawn,
I submitted to the judgment of the meeting: in fear, I think I may say.

27th. Feel more tranquil, and am favoured with a degree of acquiescence,
accompanied with the hope that this dispensation may prove profitable to myself;
although I may not afford strength to my companions.

30th. Accompanied my kind friends William and Isabel Grover to Stansted.
The next day attended their monthly meeting; the forepart of which was exercising to me,
but afterwards proved a strengthening season.

[.centered]
=== Sixth Month, 1803.

2nd. A day of heaviness of heart.

3rd. Tranquil and resigned.

5th. Favoured to retreat to the quiet habitation, where my spiritual strength was renewed.

6th. Went to Colchester, in order to attend the quarterly meeting for Essex:
a large gathering today, and a considerable number of solid friends.
I think it was an eminently favoured season.

8th. Stayed over the week-day meeting, in which dear Elizabeth Gibson and Mary Alexander,
etc. laboured abundantly in gospel love, to gather the outcasts in our Israel.
It was a season that I trust will not soon be forgotten by some present.

11th. Left my dear and valued friends at Stansted,
and the next day was at meeting at Hertford.
I thought from my feelings that the spring of life lay low;
and that all present were not sufficiently engaged to dig for its arising.

14th. Too inattentive to my best interest, and so suffered loss.
Came to town, met with affecting tidings,
which with a sense of my missteppings caused deservedly heaviness of heart.

19th. Went to Gracechurch-street meeting, in which, though rather a low time,
I thought my soul was bowed under a sense of past, as well as present, mercies.

20th. Came home and found my dear friends generally well,
which I hope I esteemed a favour.

21st. Fresh trials and perplexities attend;
yet I think I have in a good degree kissed the hand that has permitted them.
Is it not better to partake in the afflictions of
Joseph than to enjoy the pleasures of sin for a season?
May I ever prefer it.

26th. Renewedly desirous of having my feet directed in the path of self-denial,
and of being enabled to take up my cross daily and follow a crucified Saviour.

29th. Trust I have moved along the last few days with a
good degree of circumspection and lowliness of heart.

[.centered]
=== Seventh Month, 1803.

1st. My mind much bowed down with renewed trials and exercises.
O, that patience may have its perfect work.

4th. Came to Ryegate in order to attend the quarterly meeting.
Here we met with dear Deborah Darby, Rebecca Byrd, Elizabeth Hoyland, and Martha Smith,
who were truly welcome to some of us.
The meeting for worship was a favoured season;
the latter meeting was very trying to my feelings; but, as Rebecca Byrd had to testify,
we are not to live by bread alone,
but by every word that proceeds out of the mouth of God;
and if the various trials that are permitted do but tend to the great work of sanctification,
it will be all well in the end:
which is what I at this time covet beyond riches or length of days.

10th. Was desirous this morning at meeting,
that not an offensive thought might arise in my heart;
and think I was preserved in a good degree of watchfulness.

12th. Think the bent of my desires the last two days has been much heavenward.
May it continue so, is my earnest desire.
This morning have performed my duty as an overseer according to ability received.

15th. Have been renewedly convinced that every vessel in the Lord`'s
house must have the inscription of "`holiness`" upon it;
and the desire of my heart has been that I may be fitted to bear this divine impression;
though only as a door-keeper, or one of the meanest servants employed therein.

20th. Pretty fully occupied with company,
etc. but I trust not wholly to the neglect of the one thing needful.

23rd. Endeavoured to shake off every encumbering thing,
and retreat to the Source of true help: nor was my feeble effort altogether unblessed.

27th. Retired a while in order to commune with my own heart and be still:
but met with frequent interruptions.

29th. Went to meeting with the hope of meeting with the Beloved of souls;
when I thought the enemy pursued me to the very horns of the altar;
yet being mercifully enabled, in a good degree, to keep my hold,
I trust he gained but little advantage over me.

[.centered]
=== Eighth Month, 1803.

4th. Though perhaps not so watchful as is right,
yet I feel but little condemnation in looking over the last few days.

5th. Our monthly meeting at Guildford, where, though discouragements abound,
I was thankful that a little strength was given to support the discipline.

9th. Some degree of hunger and thirst after righteousness!
What a favour, believing it is of the Lord`'s creating: nothing of the creature.

12th. Sarah Bleckley and Hannah Evans were at our meeting and appeared acceptably:
as the former did in a sitting in the evening,
and both of them next morning before we parted.

14th. A laborious meeting this morning, in which I was enabled to maintain the warfare,
and was crowned with some degree of victory.
What an unspeakable favour.

18th. Was off my guard on my first sitting down at meeting today,
and got busied beside my proper business, which made it hard work to get centered,
which I was favoured to do for a short time.

20th. An awakening call this morning in the sudden removal of John Sweetapple,
who has left an afflicted wife and eight children, to deplore his loss.
How inscrutable are the ways of Providence to us, shortsighted mortals.

22nd. Was renewedly desirous of redeeming my time, because evil does indeed abound.

23rd. Spent the day with the afflicted family at Catshall,
to whom I trust the Lord will fulfill his gracious promise,
of being a husband to the widow, and a father to the fatherless.

25th. Felt a little portion of that peace, which passes the natural understanding,
rest upon my poor mind: and renewed desires were raised, that in my approaching journey,
I might be preserved from doing my own will;
that if I am not enabled to do anything to advance the cause of truth,
I may do nothing against it.

30th. Consciousness of attendant weakness is my present companion.

[.centered]
=== Ninth Month, 1803.

2nd. Left home under depressing sensations from various causes, so stripped of good,
that I could scarcely breathe for preservation,
though convinced that I stood in abundant need of it.
Slept that night at Wanborough; and after some difficulty proceeded to Salisbury,
at which place we were favoured to arrive in safety, though much fatigued and exhausted:
yet a degree of peaceful serenity was vouchsafed.
The next day attended both meetings,
and was painfully struck with the loose manner of their gathering.
Here my renewed petition was that I might be preserved
in humility and singleness of heart,
as well as from doing my own will in the impending visit;
but simply attend to the portion of labour assigned,
though it might be only to suffer in secret.

+++[+++The interval between the last date and the succeeding was employed in the visit,
by appointment of the yearly meeting,
to the quarterly meetings of Dorsetshire and Hampshire.]

25th. Returned home.
I feel languid;
yet I trust I am not unmindful of the many blessings with which I am surrounded.

27th. This week has mostly been spent in attention to my dear niece H+++_______+++,
who has been alarmingly ill,
yet I have at seasons felt the good Hand near to preserve and sustain my mind,
in a degree of peaceful serenity.

[.centered]
=== Tenth Month, 1803.

2nd. Again favoured to retire to the Rock of my strength,
where my thirsty soul was replenished.

4th. Our quarterly meeting at Horsham.
Several strangers were present, yet I thought life did not arise into much dominion.

9th. I thought the morning meeting a favoured season.
John Kincey appeared acceptably.
The afternoon was a trying one.
From some cause or other there evidently felt an obstruction to the circulation of life.

12th. Fulfilled an appointment of the monthly-meeting in visiting a delinquent;
who manifested much tenderness, and a true sense of the kindness of friends.

14th. Think I sat in a good degree of true silence today at meeting,
in which I was owned by the Father and Fountain of all our sure mercies.

21st. Found on my sitting down today at meeting that
it would not do to feed upon the manna of yesterday;
but that it must be renewedly waited for, and I was favoured with a little portion of it.

23rd. Had afresh to call to mind the gracious dealings of
the Lord with me from my youth up to this very day.

24th. "`I will set the Lord always before me;`" said David;
and the desire of my heart has been,
that I may always consider myself as in his presence,
and so fear to offend him in thought, word, or deed.

30th. Both morning and afternoon meetings were seasons of conflict to my poor mind;
yet I trust the enemy did not gain much ascendancy over me.

[.centered]
=== Eleventh Month, 1803.

2nd. The two last days my dwelling has been much in the valley.
I was favoured today in my silent sitting with something of that heavenly
union and communion which is with the Father and with the Son.
Inestimable privilege!
May my future steppings evince that I retain a deep sense of its value.

5th. Set off in company with Richard Reynolds for Bristol.
Reached Melksham first-day morning.
The meeting in the morning, held in silence,
proved an instructive season to my waiting soul.

7th. Left my kind friends at Chapel-Nap, and reached Bristol in the evening,
where I found my beloved relations in usual health, which I hope to esteem a favour.
Dear Hannah Stephenson, who is at present an inmate in my brother`'s family,
was also better than expected.

10th. Some friends dining here,
dear Hannah Stephenson appeared in a lively testimony after dinner,
pressing to faithfulness, and testifying from her own experience,
that the Lord was a rich rewarder of all those that diligently seek him.

13th. I trust the warfare was measurably maintained, though in much weakness.
I thought the meetings painfully laborious, especially that in the evening.
A precious opportunity occurred in the afternoon in the family,
in which Hannah Stephenson sweetly addressed parents and children.

14th. Off my guard, which brought with it a degree of self-condemnation.

15th. Retreated to the washing-pool, from which I returned refreshed.
Having company, dear Hannah Stephenson addressed a young woman,
sweetly inviting her to bend her neck to the yoke of Christ,
and then it would be made easy,
and what is called his burden would be light indeed to the subjected will.

18th. Although I sat down at meeting this morning encompassed with infirmity;
yet endeavouring to dig deep, through divine assistance,
I was enabled to approach the Throne of Grace,
and to put up my petition for continued preservation from every hurtful thing.

21st. Was fearful that I was not deep enough in my spirit,
but moved too much on the surface;
therefore desired that I might increase in every Christian virtue,
and that my heart might be fortified with divine
grace to resist the assaults of an unwearied enemy.

24th. Dear Hannah Stephenson had a sweet opportunity as we sat round her bed this evening,
which refreshed our spirits.

25th. "`Open your doors, O Lebanon,
that the fire may devour your cedars,`" impressed
my mind soon after I sat down at meeting this morning;
and the desire of my heart was, that the fire of the Lord, which is his power,
might indeed enter, and destroy everything that is offensive to his purity.

27th. Trust the duties of this day have been measurably fulfilled.

30th. Dear Hannah Stephenson had a trying day and appeared very low this evening,
and worn with pain.
She desired that when favoured with ability, we would pray for her,
that patience might have its perfect work in her; saying,
"`What a sad thing it would be if I should prove a stumbling-block at last.`"

[.centered]
=== Twelfth Month, 1803.

4th. Both morning and evening meetings were preciously
favoured seasons to my waiting soul.
I did not eat the bread of idleness.

5th. My time this week has been fully engaged, one way or another, but not, I trust,
to the exclusion of the better part.
I have been favoured with some watering refreshing seasons,
unworthy as I esteem myself of such a favour; and on looking back do not feel much,
if any, condemnation.

15th. I feel conscious that I have not stepped along with that circumspection
which is required of a professed follower of a crucified Saviour.

17th. Came to Chapel-Nap, where I met with an affectionate reception,
and attended Melksham meetings next day, which I thought rather low seasons.

20th. Reached Shaftsbury, where we found most of our little band^
footnote:[The yearly meeting`'s committee before-mentioned.]
assembled, and as we had parted in sweet fellowship,
so it was pleasant to feel it revive again on our sitting down together.

28th. Spent most of this week at Alton, where I met with my beloved mother.
Returned home the 30th, when on a review of the manifold blessings,
and favours bestowed upon me, the humble language of my soul was,
What shall I render unto you, O Lord, for all your benefits?
May increasing dedication of heart mark the few remaining steps of my pilgrimage,
and evince that I have not only sung of your mercies, but endeavoured,
by obedience to your divine law, to improve them.
